/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation(libs.guava)

    implementation(libs.jackson.databind)

    implementation(libs.web3j.crypto)

    // Netty for WebSocket support (high-performance async I/O)
    implementation(libs.netty.codec.http)
    implementation(libs.netty.handler.proxy)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.register<JavaExec>("liveTest") {
    classpath = sourceSets["test"].runtimeClasspath
    mainClass.set("io.github.ccxt.types.LiveTest")
    javaLauncher = javaToolchains.launcherFor {
        languageVersion = JavaLanguageVersion.of(21)
    }
    if (project.hasProperty("args")) {
        args = (project.property("args") as String).split(" ").toList()
    }
}

tasks.register<JavaExec>("wsTest") {
    classpath = sourceSets["test"].runtimeClasspath
    mainClass.set("io.github.ccxt.ws.BinanceDemoWsTest")
    javaLauncher = javaToolchains.launcherFor { languageVersion = JavaLanguageVersion.of(21) }
    standardOutput = System.out
    errorOutput = System.err
    environment("BINANCE_APIKEY", System.getenv("BINANCE_APIKEY") ?: "")
    environment("BINANCE_SECRET", System.getenv("BINANCE_SECRET") ?: "")
}

tasks.register<JavaExec>("restTest") {
    classpath = sourceSets["test"].runtimeClasspath
    mainClass.set("io.github.ccxt.ws.BinanceDemoRestTest")
    javaLauncher = javaToolchains.launcherFor { languageVersion = JavaLanguageVersion.of(21) }
    standardOutput = System.out
    errorOutput = System.err
    environment("BINANCE_APIKEY", System.getenv("BINANCE_APIKEY") ?: "")
    environment("BINANCE_SECRET", System.getenv("BINANCE_SECRET") ?: "")
}

tasks.register<JavaExec>("proxyLiveTest") {
    classpath = sourceSets["test"].runtimeClasspath
    mainClass.set("io.github.ccxt.ProxyLiveTest")
    javaLauncher = javaToolchains.launcherFor { languageVersion = JavaLanguageVersion.of(21) }
    standardOutput = System.out
    errorOutput = System.err
    environment("PROXY_HOST", System.getenv("PROXY_HOST") ?: "127.0.0.1")
    environment("PROXY_PORT", System.getenv("PROXY_PORT") ?: "18911")
}

tasks.register<JavaExec>("watchOrderBook") {
    classpath = sourceSets["test"].runtimeClasspath
    mainClass.set("io.github.ccxt.ws.WatchOrderBookExample")
    javaLauncher = javaToolchains.launcherFor { languageVersion = JavaLanguageVersion.of(21) }
    standardOutput = System.out
    errorOutput = System.err
    environment("BINANCE_APIKEY", System.getenv("BINANCE_APIKEY") ?: "")
    environment("BINANCE_SECRET", System.getenv("BINANCE_SECRET") ?: "")
}

tasks.register<JavaExec>("example") {
    classpath = sourceSets["test"].runtimeClasspath
    mainClass.set("io.github.ccxt.types.FetchOrderBooksExample")
    javaLauncher = javaToolchains.launcherFor {
        languageVersion = JavaLanguageVersion.of(21)
    }
}
