package tests.exchange;
import tests.BaseTest;
import io.github.ccxt.Helpers;
import io.github.ccxt.Exchange;
import io.github.ccxt.errors.*;


// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


public class TestFetchTradingFees extends BaseTest {
    public java.util.concurrent.CompletableFuture<Object> testFetchTradingFees(Exchange exchange, Object skippedProperties)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

        Object method = "fetchTradingFees";
        Object fees = (exchange.fetchTradingFees()).join();
        Object symbols = new java.util.ArrayList<Object>(((java.util.Map<String, Object>)fees).keySet());
        TestSharedMethods.AssertNonEmtpyArray(exchange, skippedProperties, method, symbols);
        for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(symbols)); i++)
        {
            Object symbol = Helpers.GetValue(symbols, i);
            TestTradingFee.testTradingFee(exchange, skippedProperties, method, symbol, Helpers.GetValue(fees, symbol));
        }
        return true;
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

}