// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package io.github.ccxt.api;
import io.github.ccxt.Exchange;

public class BydfiApi extends Exchange
{

    public BydfiApi () {
        super();
    }

    public BydfiApi (Object options) {
        super(options);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetV1PublicApiLimits (Object... optionalArgs)
    {
        return this.callAsync ("publicGetV1PublicApiLimits", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetV1SwapMarketExchangeInfo (Object... optionalArgs)
    {
        return this.callAsync ("publicGetV1SwapMarketExchangeInfo", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetV1SwapMarketDepth (Object... optionalArgs)
    {
        return this.callAsync ("publicGetV1SwapMarketDepth", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetV1SwapMarketTrades (Object... optionalArgs)
    {
        return this.callAsync ("publicGetV1SwapMarketTrades", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetV1SwapMarketKlines (Object... optionalArgs)
    {
        return this.callAsync ("publicGetV1SwapMarketKlines", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetV1SwapMarketTicker24hr (Object... optionalArgs)
    {
        return this.callAsync ("publicGetV1SwapMarketTicker24hr", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetV1SwapMarketTickerPrice (Object... optionalArgs)
    {
        return this.callAsync ("publicGetV1SwapMarketTickerPrice", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetV1SwapMarketMarkPrice (Object... optionalArgs)
    {
        return this.callAsync ("publicGetV1SwapMarketMarkPrice", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetV1SwapMarketFundingRate (Object... optionalArgs)
    {
        return this.callAsync ("publicGetV1SwapMarketFundingRate", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetV1SwapMarketFundingRateHistory (Object... optionalArgs)
    {
        return this.callAsync ("publicGetV1SwapMarketFundingRateHistory", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetV1SwapMarketRiskLimit (Object... optionalArgs)
    {
        return this.callAsync ("publicGetV1SwapMarketRiskLimit", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetV1AccountAssets (Object... optionalArgs)
    {
        return this.callAsync ("privateGetV1AccountAssets", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetV1AccountTransferRecords (Object... optionalArgs)
    {
        return this.callAsync ("privateGetV1AccountTransferRecords", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetV1SpotDepositRecords (Object... optionalArgs)
    {
        return this.callAsync ("privateGetV1SpotDepositRecords", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetV1SpotWithdrawRecords (Object... optionalArgs)
    {
        return this.callAsync ("privateGetV1SpotWithdrawRecords", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetV1SwapTradeOpenOrder (Object... optionalArgs)
    {
        return this.callAsync ("privateGetV1SwapTradeOpenOrder", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetV1SwapTradePlanOrder (Object... optionalArgs)
    {
        return this.callAsync ("privateGetV1SwapTradePlanOrder", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetV1SwapTradeLeverage (Object... optionalArgs)
    {
        return this.callAsync ("privateGetV1SwapTradeLeverage", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetV1SwapTradeHistoryOrder (Object... optionalArgs)
    {
        return this.callAsync ("privateGetV1SwapTradeHistoryOrder", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetV1SwapTradeHistoryTrade (Object... optionalArgs)
    {
        return this.callAsync ("privateGetV1SwapTradeHistoryTrade", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetV1SwapTradePositionHistory (Object... optionalArgs)
    {
        return this.callAsync ("privateGetV1SwapTradePositionHistory", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetV1SwapTradePositions (Object... optionalArgs)
    {
        return this.callAsync ("privateGetV1SwapTradePositions", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetV1SwapAccountBalance (Object... optionalArgs)
    {
        return this.callAsync ("privateGetV1SwapAccountBalance", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetV1SwapUserDataAssetsMargin (Object... optionalArgs)
    {
        return this.callAsync ("privateGetV1SwapUserDataAssetsMargin", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetV1SwapUserDataPositionSideDual (Object... optionalArgs)
    {
        return this.callAsync ("privateGetV1SwapUserDataPositionSideDual", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetV1AgentTeams (Object... optionalArgs)
    {
        return this.callAsync ("privateGetV1AgentTeams", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetV1AgentAgentLinks (Object... optionalArgs)
    {
        return this.callAsync ("privateGetV1AgentAgentLinks", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetV1AgentRegularOverview (Object... optionalArgs)
    {
        return this.callAsync ("privateGetV1AgentRegularOverview", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetV1AgentAgentSubOverview (Object... optionalArgs)
    {
        return this.callAsync ("privateGetV1AgentAgentSubOverview", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetV1AgentPartenerUserDeposit (Object... optionalArgs)
    {
        return this.callAsync ("privateGetV1AgentPartenerUserDeposit", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetV1AgentPartenerUsersData (Object... optionalArgs)
    {
        return this.callAsync ("privateGetV1AgentPartenerUsersData", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetV1AgentAffiliateUids (Object... optionalArgs)
    {
        return this.callAsync ("privateGetV1AgentAffiliateUids", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetV1AgentAffiliateCommission (Object... optionalArgs)
    {
        return this.callAsync ("privateGetV1AgentAffiliateCommission", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetV1AgentInternalWithdrawalStatus (Object... optionalArgs)
    {
        return this.callAsync ("privateGetV1AgentInternalWithdrawalStatus", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePostV1AccountTransfer (Object... optionalArgs)
    {
        return this.callAsync ("privatePostV1AccountTransfer", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePostV1SwapTradePlaceOrder (Object... optionalArgs)
    {
        return this.callAsync ("privatePostV1SwapTradePlaceOrder", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePostV1SwapTradeBatchPlaceOrder (Object... optionalArgs)
    {
        return this.callAsync ("privatePostV1SwapTradeBatchPlaceOrder", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePostV1SwapTradeEditOrder (Object... optionalArgs)
    {
        return this.callAsync ("privatePostV1SwapTradeEditOrder", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePostV1SwapTradeBatchEditOrder (Object... optionalArgs)
    {
        return this.callAsync ("privatePostV1SwapTradeBatchEditOrder", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePostV1SwapTradeCancelAllOrder (Object... optionalArgs)
    {
        return this.callAsync ("privatePostV1SwapTradeCancelAllOrder", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePostV1SwapTradeLeverage (Object... optionalArgs)
    {
        return this.callAsync ("privatePostV1SwapTradeLeverage", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePostV1SwapTradeBatchLeverageMargin (Object... optionalArgs)
    {
        return this.callAsync ("privatePostV1SwapTradeBatchLeverageMargin", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePostV1SwapUserDataMarginType (Object... optionalArgs)
    {
        return this.callAsync ("privatePostV1SwapUserDataMarginType", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePostV1SwapUserDataPositionSideDual (Object... optionalArgs)
    {
        return this.callAsync ("privatePostV1SwapUserDataPositionSideDual", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePostV1AgentInternalWithdrawal (Object... optionalArgs)
    {
        return this.callAsync ("privatePostV1AgentInternalWithdrawal", optionalArgs);
    }

}