// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package io.github.ccxt.api;
import io.github.ccxt.Exchange;

public class OceanexApi extends Exchange
{

    public OceanexApi () {
        super();
    }

    public OceanexApi (Object options) {
        super(options);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetMarkets (Object... optionalArgs)
    {
        return this.callAsync ("publicGetMarkets", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetTickersPair (Object... optionalArgs)
    {
        return this.callAsync ("publicGetTickersPair", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetTickersMulti (Object... optionalArgs)
    {
        return this.callAsync ("publicGetTickersMulti", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetOrderBook (Object... optionalArgs)
    {
        return this.callAsync ("publicGetOrderBook", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetOrderBookMulti (Object... optionalArgs)
    {
        return this.callAsync ("publicGetOrderBookMulti", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetFeesTrading (Object... optionalArgs)
    {
        return this.callAsync ("publicGetFeesTrading", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetTrades (Object... optionalArgs)
    {
        return this.callAsync ("publicGetTrades", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetTimestamp (Object... optionalArgs)
    {
        return this.callAsync ("publicGetTimestamp", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicPostK (Object... optionalArgs)
    {
        return this.callAsync ("publicPostK", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetKey (Object... optionalArgs)
    {
        return this.callAsync ("privateGetKey", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetMembersMe (Object... optionalArgs)
    {
        return this.callAsync ("privateGetMembersMe", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetOrders (Object... optionalArgs)
    {
        return this.callAsync ("privateGetOrders", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privateGetOrdersFilter (Object... optionalArgs)
    {
        return this.callAsync ("privateGetOrdersFilter", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePostOrders (Object... optionalArgs)
    {
        return this.callAsync ("privatePostOrders", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePostOrdersMulti (Object... optionalArgs)
    {
        return this.callAsync ("privatePostOrdersMulti", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePostOrderDelete (Object... optionalArgs)
    {
        return this.callAsync ("privatePostOrderDelete", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePostOrderDeleteMulti (Object... optionalArgs)
    {
        return this.callAsync ("privatePostOrderDeleteMulti", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePostOrdersClear (Object... optionalArgs)
    {
        return this.callAsync ("privatePostOrdersClear", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePostWithdrawsSpecialNew (Object... optionalArgs)
    {
        return this.callAsync ("privatePostWithdrawsSpecialNew", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePostDepositAddress (Object... optionalArgs)
    {
        return this.callAsync ("privatePostDepositAddress", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePostDepositAddresses (Object... optionalArgs)
    {
        return this.callAsync ("privatePostDepositAddresses", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePostDepositHistory (Object... optionalArgs)
    {
        return this.callAsync ("privatePostDepositHistory", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  privatePostWithdrawHistory (Object... optionalArgs)
    {
        return this.callAsync ("privatePostWithdrawHistory", optionalArgs);
    }

}