// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package io.github.ccxt.api;
import io.github.ccxt.Exchange;

public class TimexApi extends Exchange
{

    public TimexApi () {
        super();
    }

    public TimexApi (Object options) {
        super(options);
    }

    public java.util.concurrent.CompletableFuture<Object>  addressbookGetMe (Object... optionalArgs)
    {
        return this.callAsync ("addressbookGetMe", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  addressbookPost (Object... optionalArgs)
    {
        return this.callAsync ("addressbookPost", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  addressbookPostIdId (Object... optionalArgs)
    {
        return this.callAsync ("addressbookPostIdId", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  addressbookPostIdIdRemove (Object... optionalArgs)
    {
        return this.callAsync ("addressbookPostIdIdRemove", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  custodyGetCredentials (Object... optionalArgs)
    {
        return this.callAsync ("custodyGetCredentials", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  custodyGetCredentialsHHash (Object... optionalArgs)
    {
        return this.callAsync ("custodyGetCredentialsHHash", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  custodyGetCredentialsKKey (Object... optionalArgs)
    {
        return this.callAsync ("custodyGetCredentialsKKey", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  custodyGetCredentialsMe (Object... optionalArgs)
    {
        return this.callAsync ("custodyGetCredentialsMe", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  custodyGetCredentialsMeAddress (Object... optionalArgs)
    {
        return this.callAsync ("custodyGetCredentialsMeAddress", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  custodyGetDepositAddresses (Object... optionalArgs)
    {
        return this.callAsync ("custodyGetDepositAddresses", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  custodyGetDepositAddressesHHash (Object... optionalArgs)
    {
        return this.callAsync ("custodyGetDepositAddressesHHash", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  historyGetOrders (Object... optionalArgs)
    {
        return this.callAsync ("historyGetOrders", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  historyGetOrdersDetails (Object... optionalArgs)
    {
        return this.callAsync ("historyGetOrdersDetails", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  historyGetOrdersExportCsv (Object... optionalArgs)
    {
        return this.callAsync ("historyGetOrdersExportCsv", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  historyGetTrades (Object... optionalArgs)
    {
        return this.callAsync ("historyGetTrades", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  historyGetTradesExportCsv (Object... optionalArgs)
    {
        return this.callAsync ("historyGetTradesExportCsv", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  currenciesGetAAddress (Object... optionalArgs)
    {
        return this.callAsync ("currenciesGetAAddress", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  currenciesGetIId (Object... optionalArgs)
    {
        return this.callAsync ("currenciesGetIId", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  currenciesGetSSymbol (Object... optionalArgs)
    {
        return this.callAsync ("currenciesGetSSymbol", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  currenciesPostPerform (Object... optionalArgs)
    {
        return this.callAsync ("currenciesPostPerform", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  currenciesPostPrepare (Object... optionalArgs)
    {
        return this.callAsync ("currenciesPostPrepare", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  currenciesPostRemovePerform (Object... optionalArgs)
    {
        return this.callAsync ("currenciesPostRemovePerform", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  currenciesPostSSymbolRemovePrepare (Object... optionalArgs)
    {
        return this.callAsync ("currenciesPostSSymbolRemovePrepare", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  currenciesPostSSymbolUpdatePerform (Object... optionalArgs)
    {
        return this.callAsync ("currenciesPostSSymbolUpdatePerform", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  currenciesPostSSymbolUpdatePrepare (Object... optionalArgs)
    {
        return this.callAsync ("currenciesPostSSymbolUpdatePrepare", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  managerGetDeposits (Object... optionalArgs)
    {
        return this.callAsync ("managerGetDeposits", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  managerGetTransfers (Object... optionalArgs)
    {
        return this.callAsync ("managerGetTransfers", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  managerGetWithdrawals (Object... optionalArgs)
    {
        return this.callAsync ("managerGetWithdrawals", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  marketsGetIId (Object... optionalArgs)
    {
        return this.callAsync ("marketsGetIId", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  marketsGetSSymbol (Object... optionalArgs)
    {
        return this.callAsync ("marketsGetSSymbol", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  marketsPostPerform (Object... optionalArgs)
    {
        return this.callAsync ("marketsPostPerform", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  marketsPostPrepare (Object... optionalArgs)
    {
        return this.callAsync ("marketsPostPrepare", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  marketsPostRemovePerform (Object... optionalArgs)
    {
        return this.callAsync ("marketsPostRemovePerform", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  marketsPostSSymbolRemovePrepare (Object... optionalArgs)
    {
        return this.callAsync ("marketsPostSSymbolRemovePrepare", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  marketsPostSSymbolUpdatePerform (Object... optionalArgs)
    {
        return this.callAsync ("marketsPostSSymbolUpdatePerform", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  marketsPostSSymbolUpdatePrepare (Object... optionalArgs)
    {
        return this.callAsync ("marketsPostSSymbolUpdatePrepare", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetCandles (Object... optionalArgs)
    {
        return this.callAsync ("publicGetCandles", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetCurrencies (Object... optionalArgs)
    {
        return this.callAsync ("publicGetCurrencies", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetMarkets (Object... optionalArgs)
    {
        return this.callAsync ("publicGetMarkets", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetOrderbook (Object... optionalArgs)
    {
        return this.callAsync ("publicGetOrderbook", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetOrderbookRaw (Object... optionalArgs)
    {
        return this.callAsync ("publicGetOrderbookRaw", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetOrderbookV2 (Object... optionalArgs)
    {
        return this.callAsync ("publicGetOrderbookV2", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetTickers (Object... optionalArgs)
    {
        return this.callAsync ("publicGetTickers", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  publicGetTrades (Object... optionalArgs)
    {
        return this.callAsync ("publicGetTrades", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  statisticsGetAddress (Object... optionalArgs)
    {
        return this.callAsync ("statisticsGetAddress", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  tradingGetBalances (Object... optionalArgs)
    {
        return this.callAsync ("tradingGetBalances", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  tradingGetFees (Object... optionalArgs)
    {
        return this.callAsync ("tradingGetFees", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  tradingGetOrders (Object... optionalArgs)
    {
        return this.callAsync ("tradingGetOrders", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  tradingPostOrders (Object... optionalArgs)
    {
        return this.callAsync ("tradingPostOrders", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  tradingPostOrdersJson (Object... optionalArgs)
    {
        return this.callAsync ("tradingPostOrdersJson", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  tradingPutOrders (Object... optionalArgs)
    {
        return this.callAsync ("tradingPutOrders", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  tradingPutOrdersJson (Object... optionalArgs)
    {
        return this.callAsync ("tradingPutOrdersJson", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  tradingDeleteOrders (Object... optionalArgs)
    {
        return this.callAsync ("tradingDeleteOrders", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  tradingDeleteOrdersJson (Object... optionalArgs)
    {
        return this.callAsync ("tradingDeleteOrdersJson", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  tradingviewGetConfig (Object... optionalArgs)
    {
        return this.callAsync ("tradingviewGetConfig", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  tradingviewGetHistory (Object... optionalArgs)
    {
        return this.callAsync ("tradingviewGetHistory", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  tradingviewGetSymbolInfo (Object... optionalArgs)
    {
        return this.callAsync ("tradingviewGetSymbolInfo", optionalArgs);
    }

    public java.util.concurrent.CompletableFuture<Object>  tradingviewGetTime (Object... optionalArgs)
    {
        return this.callAsync ("tradingviewGetTime", optionalArgs);
    }

}