package io.github.ccxt.wrappers;

import io.github.ccxt.Exchange;
import io.github.ccxt.ExchangeTyped;
import io.github.ccxt.types.*;

import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.util.stream.Collectors;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

/**
 * Typed wrapper for binance exchange.
 * Only exposes methods that binance actually supports.
 */
@SuppressWarnings("unchecked")
public class Binance extends ExchangeTyped {

    public Binance() {
        super(Exchange.dynamicallyCreateInstance("binance", null));
    }

    public Binance(Map<String, Object> config) {
        super(Exchange.dynamicallyCreateInstance("binance", config));
    }

    public Binance(Exchange exchange) {
        super(exchange);
    }

    public Currencies fetchCurrencies(Map<String, Object> params) {
        Object res = exchange.fetchCurrencies(params).join();
        return new Currencies(res);
    }
    public Currencies fetchCurrencies() { return fetchCurrencies(null); }
    public CompletableFuture<Currencies> fetchCurrenciesAsync(Map<String, Object> params) {
        return exchange.fetchCurrencies(params).thenApply(Currencies::new);
    }

    public List<MarketInterface> fetchMarkets(Map<String, Object> params) {
        Object res = exchange.fetchMarkets(params).join();
        return toTypedList(res, MarketInterface::new);
    }
    public List<MarketInterface> fetchMarkets() { return fetchMarkets(null); }
    public CompletableFuture<List<MarketInterface>> fetchMarketsAsync(Map<String, Object> params) {
        return exchange.fetchMarkets(params).thenApply(res -> toTypedList(res, MarketInterface::new));
    }

    public List<Trade> fetchTrades(String symbol, Long since, Long limit, Map<String, Object> params) {
        Object res = exchange.fetchTrades(symbol, since, limit, params).join();
        return toTypedList(res, Trade::new);
    }
    public List<Trade> fetchTrades(String symbol) { return fetchTrades(symbol, null, null, null); }
    public CompletableFuture<List<Trade>> fetchTradesAsync(String symbol, Long since, Long limit, Map<String, Object> params) {
        return exchange.fetchTrades(symbol, since, limit, params).thenApply(res -> toTypedList(res, Trade::new));
    }

    public OrderBook fetchOrderBook(String symbol, Long limit, Map<String, Object> params) {
        Object res = exchange.fetchOrderBook(symbol, limit, params).join();
        return new OrderBook(res);
    }
    public OrderBook fetchOrderBook(String symbol) { return fetchOrderBook(symbol, null, null); }
    public CompletableFuture<OrderBook> fetchOrderBookAsync(String symbol, Long limit, Map<String, Object> params) {
        return exchange.fetchOrderBook(symbol, limit, params).thenApply(OrderBook::new);
    }

    public MarginMode fetchMarginMode(String symbol, Map<String, Object> params) {
        Object res = exchange.fetchMarginMode(symbol, params).join();
        return new MarginMode(res);
    }
    public MarginMode fetchMarginMode(String symbol) { return fetchMarginMode(symbol, null); }
    public CompletableFuture<MarginMode> fetchMarginModeAsync(String symbol, Map<String, Object> params) {
        return exchange.fetchMarginMode(symbol, params).thenApply(MarginMode::new);
    }

    public MarginModes fetchMarginModes(List<String> symbols, Map<String, Object> params) {
        Object res = exchange.fetchMarginModes(symbols, params).join();
        return new MarginModes(res);
    }
    public MarginModes fetchMarginModes() { return fetchMarginModes(null, null); }
    public CompletableFuture<MarginModes> fetchMarginModesAsync(List<String> symbols, Map<String, Object> params) {
        return exchange.fetchMarginModes(symbols, params).thenApply(MarginModes::new);
    }

    public Long fetchTime(Map<String, Object> params) {
        Object res = exchange.fetchTime(params).join();
        return (res instanceof Number n) ? n.longValue() : null;
    }
    public Long fetchTime() { return fetchTime(null); }
    public CompletableFuture<Long> fetchTimeAsync(Map<String, Object> params) {
        return exchange.fetchTime(params).thenApply(res -> (res instanceof Number n) ? n.longValue() : null);
    }

    public IsolatedBorrowRates fetchIsolatedBorrowRates(Map<String, Object> params) {
        Object res = exchange.fetchIsolatedBorrowRates(params).join();
        return new IsolatedBorrowRates(res);
    }
    public IsolatedBorrowRates fetchIsolatedBorrowRates() { return fetchIsolatedBorrowRates(null); }
    public CompletableFuture<IsolatedBorrowRates> fetchIsolatedBorrowRatesAsync(Map<String, Object> params) {
        return exchange.fetchIsolatedBorrowRates(params).thenApply(IsolatedBorrowRates::new);
    }

    public LeverageTiers fetchLeverageTiers(List<String> symbols, Map<String, Object> params) {
        Object res = exchange.fetchLeverageTiers(symbols, params).join();
        return new LeverageTiers(res);
    }
    public LeverageTiers fetchLeverageTiers() { return fetchLeverageTiers(null, null); }
    public CompletableFuture<LeverageTiers> fetchLeverageTiersAsync(List<String> symbols, Map<String, Object> params) {
        return exchange.fetchLeverageTiers(symbols, params).thenApply(LeverageTiers::new);
    }

    public FundingRates fetchFundingRates(List<String> symbols, Map<String, Object> params) {
        Object res = exchange.fetchFundingRates(symbols, params).join();
        return new FundingRates(res);
    }
    public FundingRates fetchFundingRates() { return fetchFundingRates(null, null); }
    public CompletableFuture<FundingRates> fetchFundingRatesAsync(List<String> symbols, Map<String, Object> params) {
        return exchange.fetchFundingRates(symbols, params).thenApply(FundingRates::new);
    }

    public FundingRates fetchFundingIntervals(List<String> symbols, Map<String, Object> params) {
        Object res = exchange.fetchFundingIntervals(symbols, params).join();
        return new FundingRates(res);
    }
    public FundingRates fetchFundingIntervals() { return fetchFundingIntervals(null, null); }
    public CompletableFuture<FundingRates> fetchFundingIntervalsAsync(List<String> symbols, Map<String, Object> params) {
        return exchange.fetchFundingIntervals(symbols, params).thenApply(FundingRates::new);
    }

    public TransferEntry transfer(String code, Double amount, String fromAccount, String toAccount, Map<String, Object> params) {
        Object res = exchange.transfer(code, amount, fromAccount, toAccount, params).join();
        return new TransferEntry(res);
    }
    public TransferEntry transfer(String code, Double amount, String fromAccount, String toAccount) { return transfer(code, amount, fromAccount, toAccount, null); }
    public CompletableFuture<TransferEntry> transferAsync(String code, Double amount, String fromAccount, String toAccount, Map<String, Object> params) {
        return exchange.transfer(code, amount, fromAccount, toAccount, params).thenApply(TransferEntry::new);
    }

    public Transaction withdraw(String code, Double amount, String address, String tag, Map<String, Object> params) {
        Object res = exchange.withdraw(code, amount, address, tag, params).join();
        return new Transaction(res);
    }
    public Transaction withdraw(String code, Double amount, String address) { return withdraw(code, amount, address, null, null); }
    public CompletableFuture<Transaction> withdrawAsync(String code, Double amount, String address, String tag, Map<String, Object> params) {
        return exchange.withdraw(code, amount, address, tag, params).thenApply(Transaction::new);
    }

    public Leverages fetchLeverages(List<String> symbols, Map<String, Object> params) {
        Object res = exchange.fetchLeverages(symbols, params).join();
        return new Leverages(res);
    }
    public Leverages fetchLeverages() { return fetchLeverages(null, null); }
    public CompletableFuture<Leverages> fetchLeveragesAsync(List<String> symbols, Map<String, Object> params) {
        return exchange.fetchLeverages(symbols, params).thenApply(Leverages::new);
    }

    public List<LongShortRatio> fetchLongShortRatioHistory(String symbol, String timeframe, Long since, Long limit, Map<String, Object> params) {
        Object res = exchange.fetchLongShortRatioHistory(symbol, timeframe, since, limit, params).join();
        return toTypedList(res, LongShortRatio::new);
    }
    public List<LongShortRatio> fetchLongShortRatioHistory() { return fetchLongShortRatioHistory(null, null, null, null, null); }
    public CompletableFuture<List<LongShortRatio>> fetchLongShortRatioHistoryAsync(String symbol, String timeframe, Long since, Long limit, Map<String, Object> params) {
        return exchange.fetchLongShortRatioHistory(symbol, timeframe, since, limit, params).thenApply(res -> toTypedList(res, LongShortRatio::new));
    }

    public List<MarginModification> fetchMarginAdjustmentHistory(String symbol, String type, Double since, Double limit, Map<String, Object> params) {
        Object res = exchange.fetchMarginAdjustmentHistory(symbol, type, since, limit, params).join();
        return toTypedList(res, MarginModification::new);
    }
    public List<MarginModification> fetchMarginAdjustmentHistory() { return fetchMarginAdjustmentHistory(null, null, null, null, null); }
    public CompletableFuture<List<MarginModification>> fetchMarginAdjustmentHistoryAsync(String symbol, String type, Double since, Double limit, Map<String, Object> params) {
        return exchange.fetchMarginAdjustmentHistory(symbol, type, since, limit, params).thenApply(res -> toTypedList(res, MarginModification::new));
    }

    public List<OpenInterest> fetchOpenInterestHistory(String symbol, String timeframe, Long since, Long limit, Map<String, Object> params) {
        Object res = exchange.fetchOpenInterestHistory(symbol, timeframe, since, limit, params).join();
        return toTypedList(res, OpenInterest::new);
    }
    public List<OpenInterest> fetchOpenInterestHistory(String symbol) { return fetchOpenInterestHistory(symbol, "1h", null, null, null); }
    public CompletableFuture<List<OpenInterest>> fetchOpenInterestHistoryAsync(String symbol, String timeframe, Long since, Long limit, Map<String, Object> params) {
        return exchange.fetchOpenInterestHistory(symbol, timeframe, since, limit, params).thenApply(res -> toTypedList(res, OpenInterest::new));
    }

    public OpenInterest fetchOpenInterest(String symbol, Map<String, Object> params) {
        Object res = exchange.fetchOpenInterest(symbol, params).join();
        return new OpenInterest(res);
    }
    public OpenInterest fetchOpenInterest(String symbol) { return fetchOpenInterest(symbol, null); }
    public CompletableFuture<OpenInterest> fetchOpenInterestAsync(String symbol, Map<String, Object> params) {
        return exchange.fetchOpenInterest(symbol, params).thenApply(OpenInterest::new);
    }

    public List<OHLCV> fetchOHLCV(String symbol, String timeframe, Long since, Long limit, Map<String, Object> params) {
        Object res = exchange.fetchOHLCV(symbol, timeframe, since, limit, params).join();
        return toTypedList(res, OHLCV::new);
    }
    public List<OHLCV> fetchOHLCV(String symbol) { return fetchOHLCV(symbol, "1m", null, null, null); }
    public CompletableFuture<List<OHLCV>> fetchOHLCVAsync(String symbol, String timeframe, Long since, Long limit, Map<String, Object> params) {
        return exchange.fetchOHLCV(symbol, timeframe, since, limit, params).thenApply(res -> toTypedList(res, OHLCV::new));
    }

    public Order editOrder(String id, String symbol, String type, String side, Double amount, Double price, Map<String, Object> params) {
        Object res = exchange.editOrder(id, symbol, type, side, amount, price, params).join();
        return new Order(res);
    }
    public Order editOrder(String id, String symbol, String type, String side) { return editOrder(id, symbol, type, side, null, null, null); }
    public CompletableFuture<Order> editOrderAsync(String id, String symbol, String type, String side, Double amount, Double price, Map<String, Object> params) {
        return exchange.editOrder(id, symbol, type, side, amount, price, params).thenApply(Order::new);
    }

    public Position fetchPosition(String symbol, Map<String, Object> params) {
        Object res = exchange.fetchPosition(symbol, params).join();
        return new Position(res);
    }
    public Position fetchPosition(String symbol) { return fetchPosition(symbol, null); }
    public CompletableFuture<Position> fetchPositionAsync(String symbol, Map<String, Object> params) {
        return exchange.fetchPosition(symbol, params).thenApply(Position::new);
    }

    public List<Position> fetchPositions(List<String> symbols, Map<String, Object> params) {
        Object res = exchange.fetchPositions(symbols, params).join();
        return toTypedList(res, Position::new);
    }
    public List<Position> fetchPositions() { return fetchPositions(null, null); }
    public CompletableFuture<List<Position>> fetchPositionsAsync(List<String> symbols, Map<String, Object> params) {
        return exchange.fetchPositions(symbols, params).thenApply(res -> toTypedList(res, Position::new));
    }

    public List<Position> fetchPositionsRisk(List<String> symbols, Map<String, Object> params) {
        Object res = exchange.fetchPositionsRisk(symbols, params).join();
        return toTypedList(res, Position::new);
    }
    public List<Position> fetchPositionsRisk() { return fetchPositionsRisk(null, null); }
    public CompletableFuture<List<Position>> fetchPositionsRiskAsync(List<String> symbols, Map<String, Object> params) {
        return exchange.fetchPositionsRisk(symbols, params).thenApply(res -> toTypedList(res, Position::new));
    }

    public Tickers fetchBidsAsks(List<String> symbols, Map<String, Object> params) {
        Object res = exchange.fetchBidsAsks(symbols, params).join();
        return new Tickers(res);
    }
    public Tickers fetchBidsAsks() { return fetchBidsAsks(null, null); }
    public CompletableFuture<Tickers> fetchBidsAsksAsync(List<String> symbols, Map<String, Object> params) {
        return exchange.fetchBidsAsks(symbols, params).thenApply(Tickers::new);
    }

    public List<BorrowInterest> fetchBorrowInterest(String code, String symbol, Long since, Long limit, Map<String, Object> params) {
        Object res = exchange.fetchBorrowInterest(code, symbol, since, limit, params).join();
        return toTypedList(res, BorrowInterest::new);
    }
    public List<BorrowInterest> fetchBorrowInterest() { return fetchBorrowInterest(null, null, null, null, null); }
    public CompletableFuture<List<BorrowInterest>> fetchBorrowInterestAsync(String code, String symbol, Long since, Long limit, Map<String, Object> params) {
        return exchange.fetchBorrowInterest(code, symbol, since, limit, params).thenApply(res -> toTypedList(res, BorrowInterest::new));
    }

    public List<LedgerEntry> fetchLedger(String code, Long since, Long limit, Map<String, Object> params) {
        Object res = exchange.fetchLedger(code, since, limit, params).join();
        return toTypedList(res, LedgerEntry::new);
    }
    public List<LedgerEntry> fetchLedger() { return fetchLedger(null, null, null, null); }
    public CompletableFuture<List<LedgerEntry>> fetchLedgerAsync(String code, Long since, Long limit, Map<String, Object> params) {
        return exchange.fetchLedger(code, since, limit, params).thenApply(res -> toTypedList(res, LedgerEntry::new));
    }

    public LedgerEntry fetchLedgerEntry(String id, String code, Map<String, Object> params) {
        Object res = exchange.fetchLedgerEntry(id, code, params).join();
        return new LedgerEntry(res);
    }
    public LedgerEntry fetchLedgerEntry(String id) { return fetchLedgerEntry(id, null, null); }
    public CompletableFuture<LedgerEntry> fetchLedgerEntryAsync(String id, String code, Map<String, Object> params) {
        return exchange.fetchLedgerEntry(id, code, params).thenApply(LedgerEntry::new);
    }

    public Balances fetchBalance(Map<String, Object> params) {
        Object res = exchange.fetchBalance(params).join();
        return new Balances(res);
    }
    public Balances fetchBalance() { return fetchBalance(null); }
    public CompletableFuture<Balances> fetchBalanceAsync(Map<String, Object> params) {
        return exchange.fetchBalance(params).thenApply(Balances::new);
    }

    public CrossBorrowRate fetchCrossBorrowRate(String code, Map<String, Object> params) {
        Object res = exchange.fetchCrossBorrowRate(code, params).join();
        return new CrossBorrowRate(res);
    }
    public CrossBorrowRate fetchCrossBorrowRate(String code) { return fetchCrossBorrowRate(code, null); }
    public CompletableFuture<CrossBorrowRate> fetchCrossBorrowRateAsync(String code, Map<String, Object> params) {
        return exchange.fetchCrossBorrowRate(code, params).thenApply(CrossBorrowRate::new);
    }

    public IsolatedBorrowRate fetchIsolatedBorrowRate(String symbol, Map<String, Object> params) {
        Object res = exchange.fetchIsolatedBorrowRate(symbol, params).join();
        return new IsolatedBorrowRate(res);
    }
    public IsolatedBorrowRate fetchIsolatedBorrowRate(String symbol) { return fetchIsolatedBorrowRate(symbol, null); }
    public CompletableFuture<IsolatedBorrowRate> fetchIsolatedBorrowRateAsync(String symbol, Map<String, Object> params) {
        return exchange.fetchIsolatedBorrowRate(symbol, params).thenApply(IsolatedBorrowRate::new);
    }

    public Ticker fetchTicker(String symbol, Map<String, Object> params) {
        Object res = exchange.fetchTicker(symbol, params).join();
        return new Ticker(res);
    }
    public Ticker fetchTicker(String symbol) { return fetchTicker(symbol, null); }
    public CompletableFuture<Ticker> fetchTickerAsync(String symbol, Map<String, Object> params) {
        return exchange.fetchTicker(symbol, params).thenApply(Ticker::new);
    }

    public Ticker fetchMarkPrice(String symbol, Map<String, Object> params) {
        Object res = exchange.fetchMarkPrice(symbol, params).join();
        return new Ticker(res);
    }
    public Ticker fetchMarkPrice(String symbol) { return fetchMarkPrice(symbol, null); }
    public CompletableFuture<Ticker> fetchMarkPriceAsync(String symbol, Map<String, Object> params) {
        return exchange.fetchMarkPrice(symbol, params).thenApply(Ticker::new);
    }

    public Tickers fetchTickers(List<String> symbols, Map<String, Object> params) {
        Object res = exchange.fetchTickers(symbols, params).join();
        return new Tickers(res);
    }
    public Tickers fetchTickers() { return fetchTickers(null, null); }
    public CompletableFuture<Tickers> fetchTickersAsync(List<String> symbols, Map<String, Object> params) {
        return exchange.fetchTickers(symbols, params).thenApply(Tickers::new);
    }

    public Tickers fetchMarkPrices(List<String> symbols, Map<String, Object> params) {
        Object res = exchange.fetchMarkPrices(symbols, params).join();
        return new Tickers(res);
    }
    public Tickers fetchMarkPrices() { return fetchMarkPrices(null, null); }
    public CompletableFuture<Tickers> fetchMarkPricesAsync(List<String> symbols, Map<String, Object> params) {
        return exchange.fetchMarkPrices(symbols, params).thenApply(Tickers::new);
    }

    public Order fetchOrder(String id, String symbol, Map<String, Object> params) {
        Object res = exchange.fetchOrder(id, symbol, params).join();
        return new Order(res);
    }
    public Order fetchOrder(String id) { return fetchOrder(id, null, null); }
    public CompletableFuture<Order> fetchOrderAsync(String id, String symbol, Map<String, Object> params) {
        return exchange.fetchOrder(id, symbol, params).thenApply(Order::new);
    }

    public Order createOrder(String symbol, String type, String side, Double amount, Double price, Map<String, Object> params) {
        Object res = exchange.createOrder(symbol, type, side, amount, price, params).join();
        return new Order(res);
    }
    public Order createOrder(String symbol, String type, String side, Double amount) { return createOrder(symbol, type, side, amount, null, null); }
    public CompletableFuture<Order> createOrderAsync(String symbol, String type, String side, Double amount, Double price, Map<String, Object> params) {
        return exchange.createOrder(symbol, type, side, amount, price, params).thenApply(Order::new);
    }

    public Conversion createConvertTrade(String id, String fromCode, String toCode, Double amount, Map<String, Object> params) {
        Object res = exchange.createConvertTrade(id, fromCode, toCode, amount, params).join();
        return new Conversion(res);
    }
    public Conversion createConvertTrade(String id, String fromCode, String toCode) { return createConvertTrade(id, fromCode, toCode, null, null); }
    public CompletableFuture<Conversion> createConvertTradeAsync(String id, String fromCode, String toCode, Double amount, Map<String, Object> params) {
        return exchange.createConvertTrade(id, fromCode, toCode, amount, params).thenApply(Conversion::new);
    }

    public Conversion fetchConvertTrade(String id, String code, Map<String, Object> params) {
        Object res = exchange.fetchConvertTrade(id, code, params).join();
        return new Conversion(res);
    }
    public Conversion fetchConvertTrade(String id) { return fetchConvertTrade(id, null, null); }
    public CompletableFuture<Conversion> fetchConvertTradeAsync(String id, String code, Map<String, Object> params) {
        return exchange.fetchConvertTrade(id, code, params).thenApply(Conversion::new);
    }

    public List<Conversion> fetchConvertTradeHistory(String code, Long since, Long limit, Map<String, Object> params) {
        Object res = exchange.fetchConvertTradeHistory(code, since, limit, params).join();
        return toTypedList(res, Conversion::new);
    }
    public List<Conversion> fetchConvertTradeHistory() { return fetchConvertTradeHistory(null, null, null, null); }
    public CompletableFuture<List<Conversion>> fetchConvertTradeHistoryAsync(String code, Long since, Long limit, Map<String, Object> params) {
        return exchange.fetchConvertTradeHistory(code, since, limit, params).thenApply(res -> toTypedList(res, Conversion::new));
    }

    public Order createMarketOrderWithCost(String symbol, String side, Double cost, Map<String, Object> params) {
        Object res = exchange.createMarketOrderWithCost(symbol, side, cost, params).join();
        return new Order(res);
    }
    public Order createMarketOrderWithCost(String symbol, String side, Double cost) { return createMarketOrderWithCost(symbol, side, cost, null); }
    public CompletableFuture<Order> createMarketOrderWithCostAsync(String symbol, String side, Double cost, Map<String, Object> params) {
        return exchange.createMarketOrderWithCost(symbol, side, cost, params).thenApply(Order::new);
    }

    public Order createMarketBuyOrderWithCost(String symbol, Double cost, Map<String, Object> params) {
        Object res = exchange.createMarketBuyOrderWithCost(symbol, cost, params).join();
        return new Order(res);
    }
    public Order createMarketBuyOrderWithCost(String symbol, Double cost) { return createMarketBuyOrderWithCost(symbol, cost, null); }
    public CompletableFuture<Order> createMarketBuyOrderWithCostAsync(String symbol, Double cost, Map<String, Object> params) {
        return exchange.createMarketBuyOrderWithCost(symbol, cost, params).thenApply(Order::new);
    }

    public Order createMarketSellOrderWithCost(String symbol, Double cost, Map<String, Object> params) {
        Object res = exchange.createMarketSellOrderWithCost(symbol, cost, params).join();
        return new Order(res);
    }
    public Order createMarketSellOrderWithCost(String symbol, Double cost) { return createMarketSellOrderWithCost(symbol, cost, null); }
    public CompletableFuture<Order> createMarketSellOrderWithCostAsync(String symbol, Double cost, Map<String, Object> params) {
        return exchange.createMarketSellOrderWithCost(symbol, cost, params).thenApply(Order::new);
    }

    public List<Order> createOrders(Object orders, Map<String, Object> params) {
        Object res = exchange.createOrders(orders, params).join();
        return toTypedList(res, Order::new);
    }
    public List<Order> createOrders(Object orders) { return createOrders(orders, null); }
    public CompletableFuture<List<Order>> createOrdersAsync(Object orders, Map<String, Object> params) {
        return exchange.createOrders(orders, params).thenApply(res -> toTypedList(res, Order::new));
    }

    public List<Order> editOrders(Object orders, Map<String, Object> params) {
        Object res = exchange.editOrders(orders, params).join();
        return toTypedList(res, Order::new);
    }
    public List<Order> editOrders(Object orders) { return editOrders(orders, null); }
    public CompletableFuture<List<Order>> editOrdersAsync(Object orders, Map<String, Object> params) {
        return exchange.editOrders(orders, params).thenApply(res -> toTypedList(res, Order::new));
    }

    public Order cancelOrder(String id, String symbol, Map<String, Object> params) {
        Object res = exchange.cancelOrder(id, symbol, params).join();
        return new Order(res);
    }
    public Order cancelOrder(String id) { return cancelOrder(id, null, null); }
    public CompletableFuture<Order> cancelOrderAsync(String id, String symbol, Map<String, Object> params) {
        return exchange.cancelOrder(id, symbol, params).thenApply(Order::new);
    }

    public List<Order> cancelOrders(Object ids, String symbol, Map<String, Object> params) {
        Object res = exchange.cancelOrders(ids, symbol, params).join();
        return toTypedList(res, Order::new);
    }
    public List<Order> cancelOrders(Object ids) { return cancelOrders(ids, null, null); }
    public CompletableFuture<List<Order>> cancelOrdersAsync(Object ids, String symbol, Map<String, Object> params) {
        return exchange.cancelOrders(ids, symbol, params).thenApply(res -> toTypedList(res, Order::new));
    }

    public List<Order> cancelAllOrders(String symbol, Map<String, Object> params) {
        Object res = exchange.cancelAllOrders(symbol, params).join();
        return toTypedList(res, Order::new);
    }
    public List<Order> cancelAllOrders() { return cancelAllOrders(null, null); }
    public CompletableFuture<List<Order>> cancelAllOrdersAsync(String symbol, Map<String, Object> params) {
        return exchange.cancelAllOrders(symbol, params).thenApply(res -> toTypedList(res, Order::new));
    }

    public List<Order> fetchOrders(String symbol, Long since, Long limit, Map<String, Object> params) {
        Object res = exchange.fetchOrders(symbol, since, limit, params).join();
        return toTypedList(res, Order::new);
    }
    public List<Order> fetchOrders() { return fetchOrders(null, null, null, null); }
    public CompletableFuture<List<Order>> fetchOrdersAsync(String symbol, Long since, Long limit, Map<String, Object> params) {
        return exchange.fetchOrders(symbol, since, limit, params).thenApply(res -> toTypedList(res, Order::new));
    }

    public List<Trade> fetchOrderTrades(String id, String symbol, Long since, Long limit, Map<String, Object> params) {
        Object res = exchange.fetchOrderTrades(id, symbol, since, limit, params).join();
        return toTypedList(res, Trade::new);
    }
    public List<Trade> fetchOrderTrades(String id) { return fetchOrderTrades(id, null, null, null, null); }
    public CompletableFuture<List<Trade>> fetchOrderTradesAsync(String id, String symbol, Long since, Long limit, Map<String, Object> params) {
        return exchange.fetchOrderTrades(id, symbol, since, limit, params).thenApply(res -> toTypedList(res, Trade::new));
    }

    public List<Order> fetchOpenOrders(String symbol, Long since, Long limit, Map<String, Object> params) {
        Object res = exchange.fetchOpenOrders(symbol, since, limit, params).join();
        return toTypedList(res, Order::new);
    }
    public List<Order> fetchOpenOrders() { return fetchOpenOrders(null, null, null, null); }
    public CompletableFuture<List<Order>> fetchOpenOrdersAsync(String symbol, Long since, Long limit, Map<String, Object> params) {
        return exchange.fetchOpenOrders(symbol, since, limit, params).thenApply(res -> toTypedList(res, Order::new));
    }

    public List<Order> fetchClosedOrders(String symbol, Long since, Long limit, Map<String, Object> params) {
        Object res = exchange.fetchClosedOrders(symbol, since, limit, params).join();
        return toTypedList(res, Order::new);
    }
    public List<Order> fetchClosedOrders() { return fetchClosedOrders(null, null, null, null); }
    public CompletableFuture<List<Order>> fetchClosedOrdersAsync(String symbol, Long since, Long limit, Map<String, Object> params) {
        return exchange.fetchClosedOrders(symbol, since, limit, params).thenApply(res -> toTypedList(res, Order::new));
    }

    public List<Order> fetchCanceledAndClosedOrders(String symbol, Long since, Long limit, Map<String, Object> params) {
        Object res = exchange.fetchCanceledAndClosedOrders(symbol, since, limit, params).join();
        return toTypedList(res, Order::new);
    }
    public List<Order> fetchCanceledAndClosedOrders() { return fetchCanceledAndClosedOrders(null, null, null, null); }
    public CompletableFuture<List<Order>> fetchCanceledAndClosedOrdersAsync(String symbol, Long since, Long limit, Map<String, Object> params) {
        return exchange.fetchCanceledAndClosedOrders(symbol, since, limit, params).thenApply(res -> toTypedList(res, Order::new));
    }

    public List<Trade> fetchMyTrades(String symbol, Long since, Long limit, Map<String, Object> params) {
        Object res = exchange.fetchMyTrades(symbol, since, limit, params).join();
        return toTypedList(res, Trade::new);
    }
    public List<Trade> fetchMyTrades() { return fetchMyTrades(null, null, null, null); }
    public CompletableFuture<List<Trade>> fetchMyTradesAsync(String symbol, Long since, Long limit, Map<String, Object> params) {
        return exchange.fetchMyTrades(symbol, since, limit, params).thenApply(res -> toTypedList(res, Trade::new));
    }

    public List<Liquidation> fetchMyLiquidations(String symbol, Long since, Long limit, Map<String, Object> params) {
        Object res = exchange.fetchMyLiquidations(symbol, since, limit, params).join();
        return toTypedList(res, Liquidation::new);
    }
    public List<Liquidation> fetchMyLiquidations() { return fetchMyLiquidations(null, null, null, null); }
    public CompletableFuture<List<Liquidation>> fetchMyLiquidationsAsync(String symbol, Long since, Long limit, Map<String, Object> params) {
        return exchange.fetchMyLiquidations(symbol, since, limit, params).thenApply(res -> toTypedList(res, Liquidation::new));
    }

    public Greeks fetchGreeks(String symbol, Map<String, Object> params) {
        Object res = exchange.fetchGreeks(symbol, params).join();
        return new Greeks(res);
    }
    public Greeks fetchGreeks(String symbol) { return fetchGreeks(symbol, null); }
    public CompletableFuture<Greeks> fetchGreeksAsync(String symbol, Map<String, Object> params) {
        return exchange.fetchGreeks(symbol, params).thenApply(Greeks::new);
    }

    public List<Greeks> fetchAllGreeks(List<String> symbols, Map<String, Object> params) {
        Object res = exchange.fetchAllGreeks(symbols, params).join();
        return toTypedList(res, Greeks::new);
    }
    public List<Greeks> fetchAllGreeks() { return fetchAllGreeks(null, null); }
    public CompletableFuture<List<Greeks>> fetchAllGreeksAsync(List<String> symbols, Map<String, Object> params) {
        return exchange.fetchAllGreeks(symbols, params).thenApply(res -> toTypedList(res, Greeks::new));
    }

    public Option fetchOption(String symbol, Map<String, Object> params) {
        Object res = exchange.fetchOption(symbol, params).join();
        return new Option(res);
    }
    public Option fetchOption(String symbol) { return fetchOption(symbol, null); }
    public CompletableFuture<Option> fetchOptionAsync(String symbol, Map<String, Object> params) {
        return exchange.fetchOption(symbol, params).thenApply(Option::new);
    }

    public Conversion fetchConvertQuote(String fromCode, String toCode, Double amount, Map<String, Object> params) {
        Object res = exchange.fetchConvertQuote(fromCode, toCode, amount, params).join();
        return new Conversion(res);
    }
    public Conversion fetchConvertQuote(String fromCode, String toCode) { return fetchConvertQuote(fromCode, toCode, null, null); }
    public CompletableFuture<Conversion> fetchConvertQuoteAsync(String fromCode, String toCode, Double amount, Map<String, Object> params) {
        return exchange.fetchConvertQuote(fromCode, toCode, amount, params).thenApply(Conversion::new);
    }

    public List<Transaction> fetchDeposits(String code, Long since, Long limit, Map<String, Object> params) {
        Object res = exchange.fetchDeposits(code, since, limit, params).join();
        return toTypedList(res, Transaction::new);
    }
    public List<Transaction> fetchDeposits() { return fetchDeposits(null, null, null, null); }
    public CompletableFuture<List<Transaction>> fetchDepositsAsync(String code, Long since, Long limit, Map<String, Object> params) {
        return exchange.fetchDeposits(code, since, limit, params).thenApply(res -> toTypedList(res, Transaction::new));
    }

    public List<Transaction> fetchWithdrawals(String code, Long since, Long limit, Map<String, Object> params) {
        Object res = exchange.fetchWithdrawals(code, since, limit, params).join();
        return toTypedList(res, Transaction::new);
    }
    public List<Transaction> fetchWithdrawals() { return fetchWithdrawals(null, null, null, null); }
    public CompletableFuture<List<Transaction>> fetchWithdrawalsAsync(String code, Long since, Long limit, Map<String, Object> params) {
        return exchange.fetchWithdrawals(code, since, limit, params).thenApply(res -> toTypedList(res, Transaction::new));
    }

    public List<FundingRateHistory> fetchFundingRateHistory(String symbol, Long since, Long limit, Map<String, Object> params) {
        Object res = exchange.fetchFundingRateHistory(symbol, since, limit, params).join();
        return toTypedList(res, FundingRateHistory::new);
    }
    public List<FundingRateHistory> fetchFundingRateHistory() { return fetchFundingRateHistory(null, null, null, null); }
    public CompletableFuture<List<FundingRateHistory>> fetchFundingRateHistoryAsync(String symbol, Long since, Long limit, Map<String, Object> params) {
        return exchange.fetchFundingRateHistory(symbol, since, limit, params).thenApply(res -> toTypedList(res, FundingRateHistory::new));
    }

    public List<FundingHistory> fetchFundingHistory(String symbol, Long since, Long limit, Map<String, Object> params) {
        Object res = exchange.fetchFundingHistory(symbol, since, limit, params).join();
        return toTypedList(res, FundingHistory::new);
    }
    public List<FundingHistory> fetchFundingHistory() { return fetchFundingHistory(null, null, null, null); }
    public CompletableFuture<List<FundingHistory>> fetchFundingHistoryAsync(String symbol, Long since, Long limit, Map<String, Object> params) {
        return exchange.fetchFundingHistory(symbol, since, limit, params).thenApply(res -> toTypedList(res, FundingHistory::new));
    }

    public DepositAddress fetchDepositAddress(String code, Map<String, Object> params) {
        Object res = exchange.fetchDepositAddress(code, params).join();
        return new DepositAddress(res);
    }
    public DepositAddress fetchDepositAddress(String code) { return fetchDepositAddress(code, null); }
    public CompletableFuture<DepositAddress> fetchDepositAddressAsync(String code, Map<String, Object> params) {
        return exchange.fetchDepositAddress(code, params).thenApply(DepositAddress::new);
    }

    public LastPrices fetchLastPrices(List<String> symbols, Map<String, Object> params) {
        Object res = exchange.fetchLastPrices(symbols, params).join();
        return new LastPrices(res);
    }
    public LastPrices fetchLastPrices() { return fetchLastPrices(null, null); }
    public CompletableFuture<LastPrices> fetchLastPricesAsync(List<String> symbols, Map<String, Object> params) {
        return exchange.fetchLastPrices(symbols, params).thenApply(LastPrices::new);
    }

    public TradingFees fetchTradingFees(Map<String, Object> params) {
        Object res = exchange.fetchTradingFees(params).join();
        return new TradingFees(res);
    }
    public TradingFees fetchTradingFees() { return fetchTradingFees(null); }
    public CompletableFuture<TradingFees> fetchTradingFeesAsync(Map<String, Object> params) {
        return exchange.fetchTradingFees(params).thenApply(TradingFees::new);
    }

    public TradingFeeInterface fetchTradingFee(String symbol, Map<String, Object> params) {
        Object res = exchange.fetchTradingFee(symbol, params).join();
        return new TradingFeeInterface(res);
    }
    public TradingFeeInterface fetchTradingFee(String symbol) { return fetchTradingFee(symbol, null); }
    public CompletableFuture<TradingFeeInterface> fetchTradingFeeAsync(String symbol, Map<String, Object> params) {
        return exchange.fetchTradingFee(symbol, params).thenApply(TradingFeeInterface::new);
    }

    public Currencies fetchConvertCurrencies(Map<String, Object> params) {
        Object res = exchange.fetchConvertCurrencies(params).join();
        return new Currencies(res);
    }
    public Currencies fetchConvertCurrencies() { return fetchConvertCurrencies(null); }
    public CompletableFuture<Currencies> fetchConvertCurrenciesAsync(Map<String, Object> params) {
        return exchange.fetchConvertCurrencies(params).thenApply(Currencies::new);
    }

    public FundingRate fetchFundingRate(String symbol, Map<String, Object> params) {
        Object res = exchange.fetchFundingRate(symbol, params).join();
        return new FundingRate(res);
    }
    public FundingRate fetchFundingRate(String symbol) { return fetchFundingRate(symbol, null); }
    public CompletableFuture<FundingRate> fetchFundingRateAsync(String symbol, Map<String, Object> params) {
        return exchange.fetchFundingRate(symbol, params).thenApply(FundingRate::new);
    }

    public List<TransferEntry> fetchTransfers(String code, Long since, Long limit, Map<String, Object> params) {
        Object res = exchange.fetchTransfers(code, since, limit, params).join();
        return toTypedList(res, TransferEntry::new);
    }
    public List<TransferEntry> fetchTransfers() { return fetchTransfers(null, null, null, null); }
    public CompletableFuture<List<TransferEntry>> fetchTransfersAsync(String code, Long since, Long limit, Map<String, Object> params) {
        return exchange.fetchTransfers(code, since, limit, params).thenApply(res -> toTypedList(res, TransferEntry::new));
    }

}
