package io.github.ccxt.wrappers;

import io.github.ccxt.Exchange;
import io.github.ccxt.ExchangeTyped;
import io.github.ccxt.types.*;

import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.util.stream.Collectors;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

/**
 * Typed wrapper for poloniex exchange.
 * Only exposes methods that poloniex actually supports.
 */
@SuppressWarnings("unchecked")
public class Poloniex extends ExchangeTyped {

    public Poloniex() {
        super(Exchange.dynamicallyCreateInstance("poloniex", null));
    }

    public Poloniex(Map<String, Object> config) {
        super(Exchange.dynamicallyCreateInstance("poloniex", config));
    }

    public Poloniex(Exchange exchange) {
        super(exchange);
    }

    public Currencies fetchCurrencies(Map<String, Object> params) {
        Object res = exchange.fetchCurrencies(params).join();
        return new Currencies(res);
    }
    public Currencies fetchCurrencies() { return fetchCurrencies(null); }
    public CompletableFuture<Currencies> fetchCurrenciesAsync(Map<String, Object> params) {
        return exchange.fetchCurrencies(params).thenApply(Currencies::new);
    }

    public List<MarketInterface> fetchMarkets(Map<String, Object> params) {
        Object res = exchange.fetchMarkets(params).join();
        return toTypedList(res, MarketInterface::new);
    }
    public List<MarketInterface> fetchMarkets() { return fetchMarkets(null); }
    public CompletableFuture<List<MarketInterface>> fetchMarketsAsync(Map<String, Object> params) {
        return exchange.fetchMarkets(params).thenApply(res -> toTypedList(res, MarketInterface::new));
    }

    public List<Trade> fetchTrades(String symbol, Long since, Long limit, Map<String, Object> params) {
        Object res = exchange.fetchTrades(symbol, since, limit, params).join();
        return toTypedList(res, Trade::new);
    }
    public List<Trade> fetchTrades(String symbol) { return fetchTrades(symbol, null, null, null); }
    public CompletableFuture<List<Trade>> fetchTradesAsync(String symbol, Long since, Long limit, Map<String, Object> params) {
        return exchange.fetchTrades(symbol, since, limit, params).thenApply(res -> toTypedList(res, Trade::new));
    }

    public OrderBook fetchOrderBook(String symbol, Long limit, Map<String, Object> params) {
        Object res = exchange.fetchOrderBook(symbol, limit, params).join();
        return new OrderBook(res);
    }
    public OrderBook fetchOrderBook(String symbol) { return fetchOrderBook(symbol, null, null); }
    public CompletableFuture<OrderBook> fetchOrderBookAsync(String symbol, Long limit, Map<String, Object> params) {
        return exchange.fetchOrderBook(symbol, limit, params).thenApply(OrderBook::new);
    }

    public Long fetchTime(Map<String, Object> params) {
        Object res = exchange.fetchTime(params).join();
        return (res instanceof Number n) ? n.longValue() : null;
    }
    public Long fetchTime() { return fetchTime(null); }
    public CompletableFuture<Long> fetchTimeAsync(Map<String, Object> params) {
        return exchange.fetchTime(params).thenApply(res -> (res instanceof Number n) ? n.longValue() : null);
    }

    public TransferEntry transfer(String code, Double amount, String fromAccount, String toAccount, Map<String, Object> params) {
        Object res = exchange.transfer(code, amount, fromAccount, toAccount, params).join();
        return new TransferEntry(res);
    }
    public TransferEntry transfer(String code, Double amount, String fromAccount, String toAccount) { return transfer(code, amount, fromAccount, toAccount, null); }
    public CompletableFuture<TransferEntry> transferAsync(String code, Double amount, String fromAccount, String toAccount, Map<String, Object> params) {
        return exchange.transfer(code, amount, fromAccount, toAccount, params).thenApply(TransferEntry::new);
    }

    public Transaction withdraw(String code, Double amount, String address, String tag, Map<String, Object> params) {
        Object res = exchange.withdraw(code, amount, address, tag, params).join();
        return new Transaction(res);
    }
    public Transaction withdraw(String code, Double amount, String address) { return withdraw(code, amount, address, null, null); }
    public CompletableFuture<Transaction> withdrawAsync(String code, Double amount, String address, String tag, Map<String, Object> params) {
        return exchange.withdraw(code, amount, address, tag, params).thenApply(Transaction::new);
    }

    public DepositAddress createDepositAddress(String code, Map<String, Object> params) {
        Object res = exchange.createDepositAddress(code, params).join();
        return new DepositAddress(res);
    }
    public DepositAddress createDepositAddress(String code) { return createDepositAddress(code, null); }
    public CompletableFuture<DepositAddress> createDepositAddressAsync(String code, Map<String, Object> params) {
        return exchange.createDepositAddress(code, params).thenApply(DepositAddress::new);
    }

    public Leverage fetchLeverage(String symbol, Map<String, Object> params) {
        Object res = exchange.fetchLeverage(symbol, params).join();
        return new Leverage(res);
    }
    public Leverage fetchLeverage(String symbol) { return fetchLeverage(symbol, null); }
    public CompletableFuture<Leverage> fetchLeverageAsync(String symbol, Map<String, Object> params) {
        return exchange.fetchLeverage(symbol, params).thenApply(Leverage::new);
    }

    public List<OHLCV> fetchOHLCV(String symbol, String timeframe, Long since, Long limit, Map<String, Object> params) {
        Object res = exchange.fetchOHLCV(symbol, timeframe, since, limit, params).join();
        return toTypedList(res, OHLCV::new);
    }
    public List<OHLCV> fetchOHLCV(String symbol) { return fetchOHLCV(symbol, "1m", null, null, null); }
    public CompletableFuture<List<OHLCV>> fetchOHLCVAsync(String symbol, String timeframe, Long since, Long limit, Map<String, Object> params) {
        return exchange.fetchOHLCV(symbol, timeframe, since, limit, params).thenApply(res -> toTypedList(res, OHLCV::new));
    }

    public Order editOrder(String id, String symbol, String type, String side, Double amount, Double price, Map<String, Object> params) {
        Object res = exchange.editOrder(id, symbol, type, side, amount, price, params).join();
        return new Order(res);
    }
    public Order editOrder(String id, String symbol, String type, String side) { return editOrder(id, symbol, type, side, null, null, null); }
    public CompletableFuture<Order> editOrderAsync(String id, String symbol, String type, String side, Double amount, Double price, Map<String, Object> params) {
        return exchange.editOrder(id, symbol, type, side, amount, price, params).thenApply(Order::new);
    }

    public List<Position> fetchPositions(List<String> symbols, Map<String, Object> params) {
        Object res = exchange.fetchPositions(symbols, params).join();
        return toTypedList(res, Position::new);
    }
    public List<Position> fetchPositions() { return fetchPositions(null, null); }
    public CompletableFuture<List<Position>> fetchPositionsAsync(List<String> symbols, Map<String, Object> params) {
        return exchange.fetchPositions(symbols, params).thenApply(res -> toTypedList(res, Position::new));
    }

    public Balances fetchBalance(Map<String, Object> params) {
        Object res = exchange.fetchBalance(params).join();
        return new Balances(res);
    }
    public Balances fetchBalance() { return fetchBalance(null); }
    public CompletableFuture<Balances> fetchBalanceAsync(Map<String, Object> params) {
        return exchange.fetchBalance(params).thenApply(Balances::new);
    }

    public Ticker fetchTicker(String symbol, Map<String, Object> params) {
        Object res = exchange.fetchTicker(symbol, params).join();
        return new Ticker(res);
    }
    public Ticker fetchTicker(String symbol) { return fetchTicker(symbol, null); }
    public CompletableFuture<Ticker> fetchTickerAsync(String symbol, Map<String, Object> params) {
        return exchange.fetchTicker(symbol, params).thenApply(Ticker::new);
    }

    public Tickers fetchTickers(List<String> symbols, Map<String, Object> params) {
        Object res = exchange.fetchTickers(symbols, params).join();
        return new Tickers(res);
    }
    public Tickers fetchTickers() { return fetchTickers(null, null); }
    public CompletableFuture<Tickers> fetchTickersAsync(List<String> symbols, Map<String, Object> params) {
        return exchange.fetchTickers(symbols, params).thenApply(Tickers::new);
    }

    public Order fetchOrder(String id, String symbol, Map<String, Object> params) {
        Object res = exchange.fetchOrder(id, symbol, params).join();
        return new Order(res);
    }
    public Order fetchOrder(String id) { return fetchOrder(id, null, null); }
    public CompletableFuture<Order> fetchOrderAsync(String id, String symbol, Map<String, Object> params) {
        return exchange.fetchOrder(id, symbol, params).thenApply(Order::new);
    }

    public String fetchOrderStatus(String id, String symbol, Map<String, Object> params) {
        Object res = exchange.fetchOrderStatus(id, symbol, params).join();
        return (String) res;
    }
    public String fetchOrderStatus(String id) { return fetchOrderStatus(id, null, null); }
    public CompletableFuture<String> fetchOrderStatusAsync(String id, String symbol, Map<String, Object> params) {
        return exchange.fetchOrderStatus(id, symbol, params).thenApply(res -> (String) res);
    }

    public Order createOrder(String symbol, String type, String side, Double amount, Double price, Map<String, Object> params) {
        Object res = exchange.createOrder(symbol, type, side, amount, price, params).join();
        return new Order(res);
    }
    public Order createOrder(String symbol, String type, String side, Double amount) { return createOrder(symbol, type, side, amount, null, null); }
    public CompletableFuture<Order> createOrderAsync(String symbol, String type, String side, Double amount, Double price, Map<String, Object> params) {
        return exchange.createOrder(symbol, type, side, amount, price, params).thenApply(Order::new);
    }

    public Order cancelOrder(String id, String symbol, Map<String, Object> params) {
        Object res = exchange.cancelOrder(id, symbol, params).join();
        return new Order(res);
    }
    public Order cancelOrder(String id) { return cancelOrder(id, null, null); }
    public CompletableFuture<Order> cancelOrderAsync(String id, String symbol, Map<String, Object> params) {
        return exchange.cancelOrder(id, symbol, params).thenApply(Order::new);
    }

    public List<Order> cancelAllOrders(String symbol, Map<String, Object> params) {
        Object res = exchange.cancelAllOrders(symbol, params).join();
        return toTypedList(res, Order::new);
    }
    public List<Order> cancelAllOrders() { return cancelAllOrders(null, null); }
    public CompletableFuture<List<Order>> cancelAllOrdersAsync(String symbol, Map<String, Object> params) {
        return exchange.cancelAllOrders(symbol, params).thenApply(res -> toTypedList(res, Order::new));
    }

    public List<Trade> fetchOrderTrades(String id, String symbol, Long since, Long limit, Map<String, Object> params) {
        Object res = exchange.fetchOrderTrades(id, symbol, since, limit, params).join();
        return toTypedList(res, Trade::new);
    }
    public List<Trade> fetchOrderTrades(String id) { return fetchOrderTrades(id, null, null, null, null); }
    public CompletableFuture<List<Trade>> fetchOrderTradesAsync(String id, String symbol, Long since, Long limit, Map<String, Object> params) {
        return exchange.fetchOrderTrades(id, symbol, since, limit, params).thenApply(res -> toTypedList(res, Trade::new));
    }

    public List<Order> fetchOpenOrders(String symbol, Long since, Long limit, Map<String, Object> params) {
        Object res = exchange.fetchOpenOrders(symbol, since, limit, params).join();
        return toTypedList(res, Order::new);
    }
    public List<Order> fetchOpenOrders() { return fetchOpenOrders(null, null, null, null); }
    public CompletableFuture<List<Order>> fetchOpenOrdersAsync(String symbol, Long since, Long limit, Map<String, Object> params) {
        return exchange.fetchOpenOrders(symbol, since, limit, params).thenApply(res -> toTypedList(res, Order::new));
    }

    public List<Order> fetchClosedOrders(String symbol, Long since, Long limit, Map<String, Object> params) {
        Object res = exchange.fetchClosedOrders(symbol, since, limit, params).join();
        return toTypedList(res, Order::new);
    }
    public List<Order> fetchClosedOrders() { return fetchClosedOrders(null, null, null, null); }
    public CompletableFuture<List<Order>> fetchClosedOrdersAsync(String symbol, Long since, Long limit, Map<String, Object> params) {
        return exchange.fetchClosedOrders(symbol, since, limit, params).thenApply(res -> toTypedList(res, Order::new));
    }

    public List<Trade> fetchMyTrades(String symbol, Long since, Long limit, Map<String, Object> params) {
        Object res = exchange.fetchMyTrades(symbol, since, limit, params).join();
        return toTypedList(res, Trade::new);
    }
    public List<Trade> fetchMyTrades() { return fetchMyTrades(null, null, null, null); }
    public CompletableFuture<List<Trade>> fetchMyTradesAsync(String symbol, Long since, Long limit, Map<String, Object> params) {
        return exchange.fetchMyTrades(symbol, since, limit, params).thenApply(res -> toTypedList(res, Trade::new));
    }

    public List<Transaction> fetchDepositsWithdrawals(String code, Long since, Long limit, Map<String, Object> params) {
        Object res = exchange.fetchDepositsWithdrawals(code, since, limit, params).join();
        return toTypedList(res, Transaction::new);
    }
    public List<Transaction> fetchDepositsWithdrawals() { return fetchDepositsWithdrawals(null, null, null, null); }
    public CompletableFuture<List<Transaction>> fetchDepositsWithdrawalsAsync(String code, Long since, Long limit, Map<String, Object> params) {
        return exchange.fetchDepositsWithdrawals(code, since, limit, params).thenApply(res -> toTypedList(res, Transaction::new));
    }

    public List<Transaction> fetchDeposits(String code, Long since, Long limit, Map<String, Object> params) {
        Object res = exchange.fetchDeposits(code, since, limit, params).join();
        return toTypedList(res, Transaction::new);
    }
    public List<Transaction> fetchDeposits() { return fetchDeposits(null, null, null, null); }
    public CompletableFuture<List<Transaction>> fetchDepositsAsync(String code, Long since, Long limit, Map<String, Object> params) {
        return exchange.fetchDeposits(code, since, limit, params).thenApply(res -> toTypedList(res, Transaction::new));
    }

    public List<Transaction> fetchWithdrawals(String code, Long since, Long limit, Map<String, Object> params) {
        Object res = exchange.fetchWithdrawals(code, since, limit, params).join();
        return toTypedList(res, Transaction::new);
    }
    public List<Transaction> fetchWithdrawals() { return fetchWithdrawals(null, null, null, null); }
    public CompletableFuture<List<Transaction>> fetchWithdrawalsAsync(String code, Long since, Long limit, Map<String, Object> params) {
        return exchange.fetchWithdrawals(code, since, limit, params).thenApply(res -> toTypedList(res, Transaction::new));
    }

    public DepositAddress fetchDepositAddress(String code, Map<String, Object> params) {
        Object res = exchange.fetchDepositAddress(code, params).join();
        return new DepositAddress(res);
    }
    public DepositAddress fetchDepositAddress(String code) { return fetchDepositAddress(code, null); }
    public CompletableFuture<DepositAddress> fetchDepositAddressAsync(String code, Map<String, Object> params) {
        return exchange.fetchDepositAddress(code, params).thenApply(DepositAddress::new);
    }

    public TradingFees fetchTradingFees(Map<String, Object> params) {
        Object res = exchange.fetchTradingFees(params).join();
        return new TradingFees(res);
    }
    public TradingFees fetchTradingFees() { return fetchTradingFees(null); }
    public CompletableFuture<TradingFees> fetchTradingFeesAsync(Map<String, Object> params) {
        return exchange.fetchTradingFees(params).thenApply(TradingFees::new);
    }

}
