package io.github.ccxt.exchanges;
import io.github.ccxt.api.BtcalphaApi;
import io.github.ccxt.base.Precise;
import io.github.ccxt.errors.*;
import io.github.ccxt.Helpers;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

public class Btcalpha extends BtcalphaApi
{
   public Btcalpha () {
       super();
   }

   public Btcalpha (Object options) {
       super(options);
   }

    public Object describe()
    {
        return this.deepExtend(super.describe(), new java.util.HashMap<String, Object>() {{
            put( "id", "btcalpha" );
            put( "name", "BTC-Alpha" );
            put( "countries", new java.util.ArrayList<Object>(java.util.Arrays.asList("US")) );
            put( "version", "v1" );
            put( "rateLimit", 10 );
            put( "has", new java.util.HashMap<String, Object>() {{
                put( "CORS", null );
                put( "spot", true );
                put( "margin", false );
                put( "swap", false );
                put( "future", false );
                put( "option", false );
                put( "addMargin", false );
                put( "borrowCrossMargin", false );
                put( "borrowIsolatedMargin", false );
                put( "borrowMargin", false );
                put( "cancelOrder", true );
                put( "closeAllPositions", false );
                put( "closePosition", false );
                put( "createDepositAddress", false );
                put( "createOrder", true );
                put( "createOrderWithTakeProfitAndStopLoss", false );
                put( "createOrderWithTakeProfitAndStopLossWs", false );
                put( "createPostOnlyOrder", false );
                put( "createReduceOnlyOrder", false );
                put( "createStopLimitOrder", false );
                put( "createStopMarketOrder", false );
                put( "createStopOrder", false );
                put( "fetchBalance", true );
                put( "fetchBorrowInterest", false );
                put( "fetchBorrowRate", false );
                put( "fetchBorrowRateHistories", false );
                put( "fetchBorrowRateHistory", false );
                put( "fetchBorrowRates", false );
                put( "fetchBorrowRatesPerSymbol", false );
                put( "fetchClosedOrders", true );
                put( "fetchCrossBorrowRate", false );
                put( "fetchCrossBorrowRates", false );
                put( "fetchCurrencies", false );
                put( "fetchDeposit", false );
                put( "fetchDepositAddress", false );
                put( "fetchDepositAddresses", false );
                put( "fetchDepositAddressesByNetwork", false );
                put( "fetchDeposits", true );
                put( "fetchFundingHistory", false );
                put( "fetchFundingInterval", false );
                put( "fetchFundingIntervals", false );
                put( "fetchFundingRate", false );
                put( "fetchFundingRateHistory", false );
                put( "fetchFundingRates", false );
                put( "fetchGreeks", false );
                put( "fetchIndexOHLCV", false );
                put( "fetchIsolatedBorrowRate", false );
                put( "fetchIsolatedBorrowRates", false );
                put( "fetchIsolatedPositions", false );
                put( "fetchL2OrderBook", true );
                put( "fetchLeverage", false );
                put( "fetchLeverages", false );
                put( "fetchLeverageTiers", false );
                put( "fetchLiquidations", false );
                put( "fetchLongShortRatio", false );
                put( "fetchLongShortRatioHistory", false );
                put( "fetchMarginAdjustmentHistory", false );
                put( "fetchMarginMode", false );
                put( "fetchMarginModes", false );
                put( "fetchMarketLeverageTiers", false );
                put( "fetchMarkets", true );
                put( "fetchMarkOHLCV", false );
                put( "fetchMarkPrices", false );
                put( "fetchMyLiquidations", false );
                put( "fetchMySettlementHistory", false );
                put( "fetchMyTrades", true );
                put( "fetchOHLCV", true );
                put( "fetchOpenInterest", false );
                put( "fetchOpenInterestHistory", false );
                put( "fetchOpenInterests", false );
                put( "fetchOpenOrders", true );
                put( "fetchOption", false );
                put( "fetchOptionChain", false );
                put( "fetchOrder", true );
                put( "fetchOrderBook", true );
                put( "fetchOrders", true );
                put( "fetchPosition", false );
                put( "fetchPositionHistory", false );
                put( "fetchPositionMode", false );
                put( "fetchPositions", false );
                put( "fetchPositionsForSymbol", false );
                put( "fetchPositionsHistory", false );
                put( "fetchPositionsRisk", false );
                put( "fetchPremiumIndexOHLCV", false );
                put( "fetchSettlementHistory", false );
                put( "fetchTicker", true );
                put( "fetchTickers", true );
                put( "fetchTrades", true );
                put( "fetchTradingFee", false );
                put( "fetchTradingFees", false );
                put( "fetchTransfer", false );
                put( "fetchTransfers", false );
                put( "fetchVolatilityHistory", false );
                put( "fetchWithdrawal", false );
                put( "fetchWithdrawals", true );
                put( "reduceMargin", false );
                put( "repayCrossMargin", false );
                put( "repayIsolatedMargin", false );
                put( "repayMargin", false );
                put( "setLeverage", false );
                put( "setMargin", false );
                put( "setMarginMode", false );
                put( "setPositionMode", false );
                put( "transfer", false );
                put( "withdraw", false );
            }} );
            put( "timeframes", new java.util.HashMap<String, Object>() {{
                put( "5m", "5" );
                put( "15m", "15" );
                put( "30m", "30" );
                put( "1h", "60" );
                put( "4h", "240" );
                put( "1d", "D" );
            }} );
            put( "urls", new java.util.HashMap<String, Object>() {{
                put( "logo", "https://github.com/user-attachments/assets/dce49f3a-61e5-4ba0-a2fe-41d192fd0e5d" );
                put( "api", new java.util.HashMap<String, Object>() {{
                    put( "rest", "https://btc-alpha.com/api" );
                }} );
                put( "www", "https://btc-alpha.com" );
                put( "doc", "https://btc-alpha.github.io/api-docs" );
                put( "fees", "https://btc-alpha.com/fees/" );
                put( "referral", "https://btc-alpha.com/?r=123788" );
            }} );
            put( "api", new java.util.HashMap<String, Object>() {{
                put( "public", new java.util.HashMap<String, Object>() {{
                    put( "get", new java.util.HashMap<String, Object>() {{
                        put( "currencies/", 1 );
                        put( "pairs/", 1 );
                        put( "orderbook/{pair_name}", 1 );
                        put( "exchanges/", 1 );
                        put( "charts/{pair}/{type}/chart/", 1 );
                        put( "ticker/", 1 );
                    }} );
                }} );
                put( "private", new java.util.HashMap<String, Object>() {{
                    put( "get", new java.util.HashMap<String, Object>() {{
                        put( "wallets/", 50 );
                        put( "orders/own/", 50 );
                        put( "order/{id}/", 50 );
                        put( "exchanges/own/", 50 );
                        put( "deposits/", 50 );
                        put( "withdraws/", 50 );
                    }} );
                    put( "post", new java.util.HashMap<String, Object>() {{
                        put( "order/", 50 );
                        put( "order-cancel/", 50 );
                    }} );
                }} );
            }} );
            put( "fees", new java.util.HashMap<String, Object>() {{
                put( "trading", new java.util.HashMap<String, Object>() {{
                    put( "maker", Btcalpha.this.parseNumber("0.002") );
                    put( "taker", Btcalpha.this.parseNumber("0.002") );
                }} );
                put( "funding", new java.util.HashMap<String, Object>() {{
                    put( "withdraw", new java.util.HashMap<String, Object>() {{}} );
                }} );
            }} );
            put( "commonCurrencies", new java.util.HashMap<String, Object>() {{
                put( "CBC", "Cashbery" );
            }} );
            put( "features", new java.util.HashMap<String, Object>() {{
                put( "spot", new java.util.HashMap<String, Object>() {{
                    put( "sandbox", false );
                    put( "createOrder", new java.util.HashMap<String, Object>() {{
                        put( "marginMode", false );
                        put( "triggerPrice", false );
                        put( "triggerPriceType", null );
                        put( "triggerDirection", false );
                        put( "stopLossPrice", false );
                        put( "takeProfitPrice", false );
                        put( "attachedStopLossTakeProfit", null );
                        put( "timeInForce", new java.util.HashMap<String, Object>() {{
                            put( "IOC", false );
                            put( "FOK", false );
                            put( "PO", false );
                            put( "GTD", false );
                        }} );
                        put( "hedged", false );
                        put( "leverage", false );
                        put( "marketBuyRequiresPrice", false );
                        put( "marketBuyByCost", false );
                        put( "selfTradePrevention", false );
                        put( "trailing", false );
                        put( "iceberg", false );
                    }} );
                    put( "createOrders", null );
                    put( "fetchMyTrades", new java.util.HashMap<String, Object>() {{
                        put( "marginMode", false );
                        put( "limit", 100 );
                        put( "daysBack", null );
                        put( "untilDays", null );
                        put( "symbolRequired", false );
                    }} );
                    put( "fetchOrder", new java.util.HashMap<String, Object>() {{
                        put( "marginMode", false );
                        put( "trigger", false );
                        put( "trailing", false );
                        put( "symbolRequired", false );
                    }} );
                    put( "fetchOpenOrders", new java.util.HashMap<String, Object>() {{
                        put( "marginMode", false );
                        put( "limit", 2000 );
                        put( "trigger", false );
                        put( "trailing", false );
                        put( "symbolRequired", false );
                    }} );
                    put( "fetchOrders", new java.util.HashMap<String, Object>() {{
                        put( "marginMode", false );
                        put( "limit", 2000 );
                        put( "daysBack", null );
                        put( "untilDays", null );
                        put( "trigger", false );
                        put( "trailing", false );
                        put( "symbolRequired", false );
                    }} );
                    put( "fetchClosedOrders", new java.util.HashMap<String, Object>() {{
                        put( "marginMode", false );
                        put( "limit", 2000 );
                        put( "daysBack", null );
                        put( "daysBackCanceled", null );
                        put( "untilDays", null );
                        put( "trigger", false );
                        put( "trailing", false );
                        put( "symbolRequired", false );
                    }} );
                    put( "fetchOHLCV", new java.util.HashMap<String, Object>() {{
                        put( "limit", 720 );
                    }} );
                }} );
                put( "swap", new java.util.HashMap<String, Object>() {{
                    put( "linear", null );
                    put( "inverse", null );
                }} );
                put( "future", new java.util.HashMap<String, Object>() {{
                    put( "linear", null );
                    put( "inverse", null );
                }} );
            }} );
            put( "precisionMode", TICK_SIZE );
            put( "exceptions", new java.util.HashMap<String, Object>() {{
                put( "exact", new java.util.HashMap<String, Object>() {{}} );
                put( "broad", new java.util.HashMap<String, Object>() {{
                    put( "Out of balance", InsufficientFunds.class );
                }} );
            }} );
        }});
    }

    /**
     * @method
     * @name btcalpha#fetchMarkets
     * @description retrieves data on all markets for btcalpha
     * @see https://btc-alpha.github.io/api-docs/#list-all-currencies
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object[]} an array of objects representing market data
     */
    public java.util.concurrent.CompletableFuture<Object> fetchMarkets(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object parameters = Helpers.getArg(optionalArgs, 0, new java.util.HashMap<String, Object>() {{}});
            Object response = (this.publicGetPairs(parameters)).join();
            //
            //    [
            //        {
            //            "name": "1INCH_USDT",
            //            "currency1": "1INCH",
            //            "currency2": "USDT",
            //            "price_precision": 4,
            //            "amount_precision": 2,
            //            "minimum_order_size": "0.01000000",
            //            "maximum_order_size": "900000.00000000",
            //            "minimum_order_value": "10.00000000",
            //            "liquidity_type": 10
            //        },
            //    ]
            //
            return this.parseMarkets(response);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public Object parseMarket(Object market)
    {
        Object id = this.safeString(market, "name");
        Object baseId = this.safeString(market, "currency1");
        Object quoteId = this.safeString(market, "currency2");
        Object base = this.safeCurrencyCode(baseId);
        Object quote = this.safeCurrencyCode(quoteId);
        Object pricePrecision = this.safeString(market, "price_precision");
        Object priceLimit = this.parsePrecision(pricePrecision);
        Object amountLimit = this.safeString(market, "minimum_order_size");
        return new java.util.HashMap<String, Object>() {{
            put( "id", id );
            put( "symbol", Helpers.add(Helpers.add(base, "/"), quote) );
            put( "base", base );
            put( "quote", quote );
            put( "settle", null );
            put( "baseId", baseId );
            put( "quoteId", quoteId );
            put( "settleId", null );
            put( "type", "spot" );
            put( "spot", true );
            put( "margin", false );
            put( "swap", false );
            put( "future", false );
            put( "option", false );
            put( "active", true );
            put( "contract", false );
            put( "linear", null );
            put( "inverse", null );
            put( "contractSize", null );
            put( "expiry", null );
            put( "expiryDatetime", null );
            put( "strike", null );
            put( "optionType", null );
            put( "precision", new java.util.HashMap<String, Object>() {{
                put( "amount", Btcalpha.this.parseNumber(Btcalpha.this.parsePrecision(Btcalpha.this.safeString(market, "amount_precision"))) );
                put( "price", Btcalpha.this.parseNumber(Btcalpha.this.parsePrecision((pricePrecision))) );
            }} );
            put( "limits", new java.util.HashMap<String, Object>() {{
                put( "leverage", new java.util.HashMap<String, Object>() {{
                    put( "min", null );
                    put( "max", null );
                }} );
                put( "amount", new java.util.HashMap<String, Object>() {{
                    put( "min", Btcalpha.this.parseNumber(amountLimit) );
                    put( "max", Btcalpha.this.safeNumber(market, "maximum_order_size") );
                }} );
                put( "price", new java.util.HashMap<String, Object>() {{
                    put( "min", Btcalpha.this.parseNumber(priceLimit) );
                    put( "max", null );
                }} );
                put( "cost", new java.util.HashMap<String, Object>() {{
                    put( "min", Btcalpha.this.parseNumber(Precise.stringMul(priceLimit, amountLimit)) );
                    put( "max", null );
                }} );
            }} );
            put( "created", null );
            put( "info", market );
        }};
    }

    /**
     * @method
     * @name btcalpha#fetchTickers
     * @see https://btc-alpha.github.io/api-docs/#tickers
     * @description fetches price tickers for multiple markets, statistical information calculated over the past 24 hours for each market
     * @param {string[]|undefined} symbols unified symbols of the markets to fetch the ticker for, all market tickers are returned if not assigned
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a dictionary of [ticker structures]{@link https://docs.ccxt.com/?id=ticker-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> fetchTickers(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object symbols = Helpers.getArg(optionalArgs, 0, null);
            Object parameters = Helpers.getArg(optionalArgs, 1, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object response = (this.publicGetTicker(parameters)).join();
            //
            //    [
            //        {
            //            "timestamp": "1674658.445272",
            //            "pair": "BTC_USDT",
            //            "last": "22476.85",
            //            "diff": "458.96",
            //            "vol": "6660.847784",
            //            "high": "23106.08",
            //            "low": "22348.29",
            //            "buy": "22508.46",
            //            "sell": "22521.11"
            //        },
            //        ...
            //    ]
            //
            return this.parseTickers(response, symbols);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name btcalpha#fetchTicker
     * @see https://btc-alpha.github.io/api-docs/#tickers
     * @description fetches a price ticker, a statistical calculation with the information calculated over the past 24 hours for a specific market
     * @param {string} symbol unified symbol of the market to fetch the ticker for
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a [ticker structure]{@link https://docs.ccxt.com/?id=ticker-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> fetchTicker(Object symbol, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object parameters = Helpers.getArg(optionalArgs, 0, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object market = this.market(symbol);
            Object request = new java.util.HashMap<String, Object>() {{
                put( "pair", Helpers.GetValue(market, "id") );
            }};
            Object response = (this.publicGetTicker(this.extend(request, parameters))).join();
            //
            //    {
            //        "timestamp": "1674658.445272",
            //        "pair": "BTC_USDT",
            //        "last": "22476.85",
            //        "diff": "458.96",
            //        "vol": "6660.847784",
            //        "high": "23106.08",
            //        "low": "22348.29",
            //        "buy": "22508.46",
            //        "sell": "22521.11"
            //    }
            //
            return this.parseTicker(response, market);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public Object parseTicker(Object ticker, Object... optionalArgs)
    {
        //
        //    {
        //        "timestamp": "1674658.445272",
        //        "pair": "BTC_USDT",
        //        "last": "22476.85",
        //        "diff": "458.96",
        //        "vol": "6660.847784",
        //        "high": "23106.08",
        //        "low": "22348.29",
        //        "buy": "22508.46",
        //        "sell": "22521.11"
        //    }
        //
        Object market = Helpers.getArg(optionalArgs, 0, null);
        Object timestampStr = this.safeString(ticker, "timestamp");
        Object timestamp = Helpers.parseInt(Precise.stringMul(timestampStr, "1000000"));
        Object marketId = this.safeString(ticker, "pair");
        market = this.safeMarket(marketId, market, "_");
        Object last = this.safeString(ticker, "last");
        final Object finalMarket = market;
        return this.safeTicker(new java.util.HashMap<String, Object>() {{
            put( "info", ticker );
            put( "symbol", Helpers.GetValue(finalMarket, "symbol") );
            put( "timestamp", timestamp );
            put( "datetime", Btcalpha.this.iso8601(timestamp) );
            put( "high", Btcalpha.this.safeString(ticker, "high") );
            put( "low", Btcalpha.this.safeString(ticker, "low") );
            put( "bid", Btcalpha.this.safeString(ticker, "buy") );
            put( "bidVolume", null );
            put( "ask", Btcalpha.this.safeString(ticker, "sell") );
            put( "askVolume", null );
            put( "vwap", null );
            put( "open", null );
            put( "close", last );
            put( "last", last );
            put( "previousClose", null );
            put( "change", Btcalpha.this.safeString(ticker, "diff") );
            put( "percentage", null );
            put( "average", null );
            put( "baseVolume", null );
            put( "quoteVolume", Btcalpha.this.safeString(ticker, "vol") );
        }}, market);
    }

    /**
     * @method
     * @name btcalpha#fetchOrderBook
     * @see https://btc-alpha.github.io/api-docs/#get-orderbook
     * @description fetches information on open orders with bid (buy) and ask (sell) prices, volumes and other data
     * @param {string} symbol unified symbol of the market to fetch the order book for
     * @param {int} [limit] the maximum amount of order book entries to return
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} A dictionary of [order book structures]{@link https://docs.ccxt.com/?id=order-book-structure} indexed by market symbols
     */
    public java.util.concurrent.CompletableFuture<Object> fetchOrderBook(Object symbol, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object limit = Helpers.getArg(optionalArgs, 0, null);
            Object parameters = Helpers.getArg(optionalArgs, 1, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object market = this.market(symbol);
            Object request = new java.util.HashMap<String, Object>() {{
                put( "pair_name", Helpers.GetValue(market, "id") );
            }};
            if (Helpers.isTrue(limit))
            {
                Helpers.addElementToObject(request, "limit_sell", limit);
                Helpers.addElementToObject(request, "limit_buy", limit);
            }
            Object response = (this.publicGetOrderbookPairName(this.extend(request, parameters))).join();
            return this.parseOrderBook(response, Helpers.GetValue(market, "symbol"), null, "buy", "sell", "price", "amount");
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public Object parseBidsAsks(Object bidasks, Object... optionalArgs)
    {
        Object priceKey = Helpers.getArg(optionalArgs, 0, 0);
        Object amountKey = Helpers.getArg(optionalArgs, 1, 1);
        Object countOrIdKey = Helpers.getArg(optionalArgs, 2, 2);
        Object result = new java.util.ArrayList<Object>(java.util.Arrays.asList());
        for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(bidasks)); i++)
        {
            Object bidask = Helpers.GetValue(bidasks, i);
            if (Helpers.isTrue(bidask))
            {
                ((java.util.List<Object>)result).add(this.parseBidAsk(bidask, priceKey, amountKey));
            }
        }
        return result;
    }

    public Object parseTrade(Object trade, Object... optionalArgs)
    {
        //
        // fetchTrades (public)
        //
        //      {
        //          "id": "202203440",
        //          "timestamp": "1637856276.264215",
        //          "pair": "AAVE_USDT",
        //          "price": "320.79900000",
        //          "amount": "0.05000000",
        //          "type": "buy"
        //      }
        //
        // fetchMyTrades (private)
        //
        //      {
        //          "id": "202203440",
        //          "timestamp": "1637856276.264215",
        //          "pair": "AAVE_USDT",
        //          "price": "320.79900000",
        //          "amount": "0.05000000",
        //          "type": "buy",
        //          "my_side": "buy"
        //      }
        //
        Object market = Helpers.getArg(optionalArgs, 0, null);
        Object marketId = this.safeString(trade, "pair");
        market = this.safeMarket(marketId, market, "_");
        Object timestampRaw = this.safeString(trade, "timestamp");
        Object timestamp = this.parseToInt(Precise.stringMul(timestampRaw, "1000000"));
        Object priceString = this.safeString(trade, "price");
        Object amountString = this.safeString(trade, "amount");
        Object id = this.safeString(trade, "id");
        Object side = this.safeString2(trade, "my_side", "type");
        final Object finalMarket = market;
        return this.safeTrade(new java.util.HashMap<String, Object>() {{
            put( "id", id );
            put( "info", trade );
            put( "timestamp", timestamp );
            put( "datetime", Btcalpha.this.iso8601(timestamp) );
            put( "symbol", Helpers.GetValue(finalMarket, "symbol") );
            put( "order", id );
            put( "type", "limit" );
            put( "side", side );
            put( "takerOrMaker", null );
            put( "price", priceString );
            put( "amount", amountString );
            put( "cost", null );
            put( "fee", null );
        }}, market);
    }

    /**
     * @method
     * @name btcalpha#fetchTrades
     * @description get the list of most recent trades for a particular symbol
     * @see https://btc-alpha.github.io/api-docs/#list-all-exchanges
     * @param {string} symbol unified symbol of the market to fetch trades for
     * @param {int} [since] timestamp in ms of the earliest trade to fetch
     * @param {int} [limit] the maximum amount of trades to fetch
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {Trade[]} a list of [trade structures]{@link https://docs.ccxt.com/?id=public-trades}
     */
    public java.util.concurrent.CompletableFuture<Object> fetchTrades(Object symbol2, Object... optionalArgs)
    {
        final Object symbol3 = symbol2;
        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {
            Object symbol = symbol3;
            Object since = Helpers.getArg(optionalArgs, 0, null);
            Object limit = Helpers.getArg(optionalArgs, 1, null);
            Object parameters = Helpers.getArg(optionalArgs, 2, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object market = null;
            Object request = new java.util.HashMap<String, Object>() {{}};
            if (Helpers.isTrue(!Helpers.isEqual(symbol, null)))
            {
                market = this.market(symbol);
                Helpers.addElementToObject(request, "pair", Helpers.GetValue(market, "id"));
            }
            if (Helpers.isTrue(!Helpers.isEqual(limit, null)))
            {
                Helpers.addElementToObject(request, "limit", limit);
            }
            Object trades = (this.publicGetExchanges(this.extend(request, parameters))).join();
            return this.parseTrades(trades, market, since, limit);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name btcalpha#fetchDeposits
     * @description fetch all deposits made to an account
     * @see https://btc-alpha.github.io/api-docs/#list-own-deposits
     * @param {string} code unified currency code
     * @param {int} [since] the earliest time in ms to fetch deposits for
     * @param {int} [limit] the maximum number of deposits structures to retrieve
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object[]} a list of [transaction structures]{@link https://docs.ccxt.com/?id=transaction-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> fetchDeposits(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object code = Helpers.getArg(optionalArgs, 0, null);
            Object since = Helpers.getArg(optionalArgs, 1, null);
            Object limit = Helpers.getArg(optionalArgs, 2, null);
            Object parameters = Helpers.getArg(optionalArgs, 3, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object currency = null;
            if (Helpers.isTrue(!Helpers.isEqual(code, null)))
            {
                currency = this.currency(code);
            }
            Object response = (this.privateGetDeposits(parameters)).join();
            //
            //     [
            //         {
            //             "timestamp": 1485363039.18359,
            //             "id": 317,
            //             "currency": "BTC",
            //             "amount": 530.00000000
            //         }
            //     ]
            //
            return this.parseTransactions(response, currency, since, limit, new java.util.HashMap<String, Object>() {{
                put( "type", "deposit" );
            }});
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name btcalpha#fetchWithdrawals
     * @description fetch all withdrawals made from an account
     * @see https://btc-alpha.github.io/api-docs/#list-own-made-withdraws
     * @param {string} code unified currency code
     * @param {int} [since] the earliest time in ms to fetch withdrawals for
     * @param {int} [limit] the maximum number of withdrawals structures to retrieve
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object[]} a list of [transaction structures]{@link https://docs.ccxt.com/?id=transaction-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> fetchWithdrawals(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object code = Helpers.getArg(optionalArgs, 0, null);
            Object since = Helpers.getArg(optionalArgs, 1, null);
            Object limit = Helpers.getArg(optionalArgs, 2, null);
            Object parameters = Helpers.getArg(optionalArgs, 3, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object currency = null;
            Object request = new java.util.HashMap<String, Object>() {{}};
            if (Helpers.isTrue(!Helpers.isEqual(code, null)))
            {
                currency = this.currency(code);
                Helpers.addElementToObject(request, "currency_id", Helpers.GetValue(currency, "id"));
            }
            Object response = (this.privateGetWithdraws(this.extend(request, parameters))).join();
            //
            //     [
            //         {
            //             "id": 403,
            //             "timestamp": 1485363466.868539,
            //             "currency": "BTC",
            //             "amount": 0.53000000,
            //             "status": 20
            //         }
            //     ]
            //
            return this.parseTransactions(response, currency, since, limit, new java.util.HashMap<String, Object>() {{
                put( "type", "withdrawal" );
            }});
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public Object parseTransaction(Object transaction, Object... optionalArgs)
    {
        //
        //  deposit
        //      {
        //          "timestamp": 1485363039.18359,
        //          "id": 317,
        //          "currency": "BTC",
        //          "amount": 530.00000000
        //      }
        //
        //  withdrawal
        //      {
        //          "id": 403,
        //          "timestamp": 1485363466.868539,
        //          "currency": "BTC",
        //          "amount": 0.53000000,
        //          "status": 20
        //      }
        //
        Object currency = Helpers.getArg(optionalArgs, 0, null);
        Object timestamp = this.safeTimestamp(transaction, "timestamp");
        Object currencyId = this.safeString(transaction, "currency");
        Object statusId = this.safeString(transaction, "status");
        return new java.util.HashMap<String, Object>() {{
            put( "id", Btcalpha.this.safeString(transaction, "id") );
            put( "info", transaction );
            put( "timestamp", timestamp );
            put( "datetime", Btcalpha.this.iso8601(timestamp) );
            put( "network", null );
            put( "address", null );
            put( "addressTo", null );
            put( "addressFrom", null );
            put( "tag", null );
            put( "tagTo", null );
            put( "tagFrom", null );
            put( "currency", Btcalpha.this.safeCurrencyCode(currencyId, currency) );
            put( "amount", Btcalpha.this.safeNumber(transaction, "amount") );
            put( "txid", null );
            put( "type", null );
            put( "status", Btcalpha.this.parseTransactionStatus(statusId) );
            put( "comment", null );
            put( "internal", null );
            put( "fee", null );
            put( "updated", null );
        }};
    }

    public Object parseTransactionStatus(Object status)
    {
        Object statuses = new java.util.HashMap<String, Object>() {{
            put( "10", "pending" );
            put( "20", "pending" );
            put( "30", "ok" );
            put( "40", "failed" );
            put( "50", "canceled" );
        }};
        return this.safeString(statuses, status, status);
    }

    public Object parseOHLCV(Object ohlcv, Object... optionalArgs)
    {
        //
        //     {
        //         "time":1591296000,
        //         "open":0.024746,
        //         "close":0.024728,
        //         "low":0.024728,
        //         "high":0.024753,
        //         "volume":16.624
        //     }
        //
        Object market = Helpers.getArg(optionalArgs, 0, null);
        return new java.util.ArrayList<Object>(java.util.Arrays.asList(this.safeTimestamp(ohlcv, "time"), this.safeNumber(ohlcv, "open"), this.safeNumber(ohlcv, "high"), this.safeNumber(ohlcv, "low"), this.safeNumber(ohlcv, "close"), this.safeNumber(ohlcv, "volume")));
    }

    /**
     * @method
     * @name btcalpha#fetchOHLCV
     * @description fetches historical candlestick data containing the open, high, low, and close price, and the volume of a market
     * @see https://btc-alpha.github.io/api-docs/#charts
     * @param {string} symbol unified symbol of the market to fetch OHLCV data for
     * @param {string} timeframe the length of time each candle represents
     * @param {int} [since] timestamp in ms of the earliest candle to fetch
     * @param {int} [limit] the maximum amount of candles to fetch
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {int[][]} A list of candles ordered as timestamp, open, high, low, close, volume
     */
    public java.util.concurrent.CompletableFuture<Object> fetchOHLCV(Object symbol, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object timeframe = Helpers.getArg(optionalArgs, 0, "5m");
            Object since = Helpers.getArg(optionalArgs, 1, null);
            Object limit = Helpers.getArg(optionalArgs, 2, null);
            Object parameters = Helpers.getArg(optionalArgs, 3, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object market = this.market(symbol);
            Object request = new java.util.HashMap<String, Object>() {{
                put( "pair", Helpers.GetValue(market, "id") );
                put( "type", Btcalpha.this.safeString(Btcalpha.this.timeframes, timeframe, timeframe) );
            }};
            if (Helpers.isTrue(!Helpers.isEqual(limit, null)))
            {
                Helpers.addElementToObject(request, "limit", limit);
            }
            if (Helpers.isTrue(!Helpers.isEqual(since, null)))
            {
                Helpers.addElementToObject(request, "since", this.parseToInt(Helpers.divide(since, 1000)));
            }
            Object response = (this.publicGetChartsPairTypeChart(this.extend(request, parameters))).join();
            //
            //     [
            //         {"time":1591296000,"open":0.024746,"close":0.024728,"low":0.024728,"high":0.024753,"volume":16.624},
            //         {"time":1591295700,"open":0.024718,"close":0.02475,"low":0.024711,"high":0.02475,"volume":31.645},
            //         {"time":1591295400,"open":0.024721,"close":0.024717,"low":0.024711,"high":0.02473,"volume":65.071}
            //     ]
            //
            return this.parseOHLCVs(response, market, timeframe, since, limit);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public Object parseBalance(Object response)
    {
        Object result = new java.util.HashMap<String, Object>() {{
            put( "info", response );
        }};
        for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(response)); i++)
        {
            Object balance = Helpers.GetValue(response, i);
            Object currencyId = this.safeString(balance, "currency");
            Object code = this.safeCurrencyCode(currencyId);
            Object account = this.account();
            Helpers.addElementToObject(account, "used", this.safeString(balance, "reserve"));
            Helpers.addElementToObject(account, "total", this.safeString(balance, "balance"));
            Helpers.addElementToObject(result, code, account);
        }
        return this.safeBalance(result);
    }

    /**
     * @method
     * @name btcalpha#fetchBalance
     * @description query for balance and get the amount of funds available for trading or funds locked in orders
     * @see https://btc-alpha.github.io/api-docs/#list-own-wallets
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a [balance structure]{@link https://docs.ccxt.com/?id=balance-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> fetchBalance(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object parameters = Helpers.getArg(optionalArgs, 0, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object response = (this.privateGetWallets(parameters)).join();
            return this.parseBalance(response);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public Object parseOrderStatus(Object status)
    {
        Object statuses = new java.util.HashMap<String, Object>() {{
            put( "1", "open" );
            put( "2", "canceled" );
            put( "3", "closed" );
        }};
        return this.safeString(statuses, status, status);
    }

    public Object parseOrder(Object order, Object... optionalArgs)
    {
        //
        // fetchClosedOrders / fetchOrder
        //     {
        //       "id": "923763073",
        //       "date": "1635451090368",
        //       "type": "sell",
        //       "pair": "XRP_USDT",
        //       "price": "1.00000000",
        //       "amount": "0.00000000",
        //       "status": "3",
        //       "amount_filled": "10.00000000",
        //       "amount_original": "10.0"
        //       "trades": [],
        //     }
        //
        // createOrder
        //     {
        //       "success": true,
        //       "date": "1635451754.497541",
        //       "type": "sell",
        //       "oid": "923776755",
        //       "price": "1.0",
        //       "amount": "10.0",
        //       "amount_filled": "0.0",
        //       "amount_original": "10.0",
        //       "trades": []
        //     }
        //
        Object market = Helpers.getArg(optionalArgs, 0, null);
        Object marketId = this.safeString(order, "pair");
        market = this.safeMarket(marketId, market, "_");
        Object symbol = Helpers.GetValue(market, "symbol");
        Object success = this.safeBool(order, "success", false);
        Object timestamp = null;
        if (Helpers.isTrue(success))
        {
            timestamp = this.safeTimestamp(order, "date");
        } else
        {
            timestamp = this.safeInteger(order, "date");
        }
        Object price = this.safeString(order, "price");
        Object remaining = this.safeString(order, "amount");
        Object filled = this.safeString(order, "amount_filled");
        Object amount = this.safeString(order, "amount_original");
        Object status = this.parseOrderStatus(this.safeString(order, "status"));
        Object id = this.safeStringN(order, new java.util.ArrayList<Object>(java.util.Arrays.asList("oid", "id", "order")));
        Object trades = this.safeValue(order, "trades");
        Object side = this.safeString2(order, "my_side", "type");
        final Object finalTimestamp = timestamp;
        return this.safeOrder(new java.util.HashMap<String, Object>() {{
            put( "id", id );
            put( "clientOrderId", null );
            put( "datetime", Btcalpha.this.iso8601(finalTimestamp) );
            put( "timestamp", finalTimestamp );
            put( "status", status );
            put( "symbol", symbol );
            put( "type", "limit" );
            put( "timeInForce", null );
            put( "postOnly", null );
            put( "side", side );
            put( "price", price );
            put( "triggerPrice", null );
            put( "cost", null );
            put( "amount", amount );
            put( "filled", filled );
            put( "remaining", remaining );
            put( "trades", trades );
            put( "fee", null );
            put( "info", order );
            put( "lastTradeTimestamp", null );
            put( "average", null );
        }}, market);
    }

    /**
     * @method
     * @name btcalpha#createOrder
     * @see https://btc-alpha.github.io/api-docs/#create-order
     * @description create a trade order
     * @param {string} symbol unified symbol of the market to create an order in
     * @param {string} type 'limit'
     * @param {string} side 'buy' or 'sell'
     * @param {float} amount how much of currency you want to trade in units of base currency
     * @param {float} [price] the price at which the order is to be fulfilled, in units of the quote currency, ignored in market orders
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} an [order structure]{@link https://docs.ccxt.com/?id=order-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> createOrder(Object symbol, Object type2, Object side, Object amount2, Object... optionalArgs)
    {
        final Object type3 = type2;
        final Object amount3 = amount2;
        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {
            Object type = type3;
            Object amount = amount3;
            Object price = Helpers.getArg(optionalArgs, 0, null);
            Object parameters = Helpers.getArg(optionalArgs, 1, new java.util.HashMap<String, Object>() {{}});
            if (Helpers.isTrue(Helpers.isEqual(type, "market")))
            {
                throw new InvalidOrder((String)Helpers.add(this.id, " only limits orders are supported")) ;
            }
            (this.loadMarkets()).join();
            Object market = this.market(symbol);
            Object finalAmount = this.amountToPrecision(symbol, amount);
            Object request = new java.util.HashMap<String, Object>() {{
                put( "pair", Helpers.GetValue(market, "id") );
                put( "type", side );
                put( "amount", finalAmount );
                put( "price", Btcalpha.this.priceToPrecision(symbol, price) );
            }};
            Object response = (this.privatePostOrder(this.extend(request, parameters))).join();
            if (!Helpers.isTrue(Helpers.GetValue(response, "success")))
            {
                throw new InvalidOrder((String)Helpers.add(Helpers.add(this.id, " "), this.json(response))) ;
            }
            Object order = this.parseOrder(response, market);
            Object orderAmount = String.valueOf(Helpers.GetValue(order, "amount"));
            amount = ((Helpers.isTrue(Precise.stringGt(orderAmount, "0")))) ? Helpers.GetValue(order, "amount") : amount;
            Helpers.addElementToObject(order, "amount", this.parseNumber(amount));
            return order;
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name btcalpha#cancelOrder
     * @see https://btc-alpha.github.io/api-docs/#cancel-order
     * @description cancels an open order
     * @param {string} id order id
     * @param {string} symbol unified symbol of the market the order was made in
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} An [order structure]{@link https://docs.ccxt.com/?id=order-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> cancelOrder(Object id, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object symbol = Helpers.getArg(optionalArgs, 0, null);
            Object parameters = Helpers.getArg(optionalArgs, 1, new java.util.HashMap<String, Object>() {{}});
            Object request = new java.util.HashMap<String, Object>() {{
                put( "order", id );
            }};
            Object response = (this.privatePostOrderCancel(this.extend(request, parameters))).join();
            //
            //    {
            //        "order": 63568
            //    }
            //
            return this.parseOrder(response);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name btcalpha#fetchOrder
     * @see https://btc-alpha.github.io/api-docs/#retrieve-single-order
     * @description fetches information on an order made by the user
     * @param {string} id the order id
     * @param {string} symbol not used by btcalpha fetchOrder
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} An [order structure]{@link https://docs.ccxt.com/?id=order-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> fetchOrder(Object id, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object symbol = Helpers.getArg(optionalArgs, 0, null);
            Object parameters = Helpers.getArg(optionalArgs, 1, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object request = new java.util.HashMap<String, Object>() {{
                put( "id", id );
            }};
            Object order = (this.privateGetOrderId(this.extend(request, parameters))).join();
            return this.parseOrder(order);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name btcalpha#fetchOrders
     * @see https://btc-alpha.github.io/api-docs/#list-own-orders
     * @description fetches information on multiple orders made by the user
     * @param {string} symbol unified market symbol of the market orders were made in
     * @param {int} [since] the earliest time in ms to fetch orders for
     * @param {int} [limit] the maximum number of order structures to retrieve
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {Order[]} a list of [order structures]{@link https://docs.ccxt.com/?id=order-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> fetchOrders(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object symbol = Helpers.getArg(optionalArgs, 0, null);
            Object since = Helpers.getArg(optionalArgs, 1, null);
            Object limit = Helpers.getArg(optionalArgs, 2, null);
            Object parameters = Helpers.getArg(optionalArgs, 3, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object request = new java.util.HashMap<String, Object>() {{}};
            Object market = null;
            if (Helpers.isTrue(!Helpers.isEqual(symbol, null)))
            {
                market = this.market(symbol);
                Helpers.addElementToObject(request, "pair", Helpers.GetValue(market, "id"));
            }
            if (Helpers.isTrue(!Helpers.isEqual(limit, null)))
            {
                Helpers.addElementToObject(request, "limit", limit);
            }
            Object orders = (this.privateGetOrdersOwn(this.extend(request, parameters))).join();
            return this.parseOrders(orders, market, since, limit);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name btcalpha#fetchOpenOrders
     * @description fetch all unfilled currently open orders
     * @see https://btc-alpha.github.io/api-docs/#list-own-orders
     * @param {string} symbol unified market symbol
     * @param {int} [since] the earliest time in ms to fetch open orders for
     * @param {int} [limit] the maximum number of  open orders structures to retrieve
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {Order[]} a list of [order structures]{@link https://docs.ccxt.com/?id=order-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> fetchOpenOrders(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object symbol = Helpers.getArg(optionalArgs, 0, null);
            Object since = Helpers.getArg(optionalArgs, 1, null);
            Object limit = Helpers.getArg(optionalArgs, 2, null);
            Object parameters = Helpers.getArg(optionalArgs, 3, new java.util.HashMap<String, Object>() {{}});
            Object request = new java.util.HashMap<String, Object>() {{
                put( "status", "1" );
            }};
            return (this.fetchOrders(symbol, since, limit, this.extend(request, parameters))).join();
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name btcalpha#fetchClosedOrders
     * @description fetches information on multiple closed orders made by the user
     * @see https://btc-alpha.github.io/api-docs/#list-own-orders
     * @param {string} symbol unified market symbol of the market orders were made in
     * @param {int} [since] the earliest time in ms to fetch orders for
     * @param {int} [limit] the maximum number of order structures to retrieve
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {Order[]} a list of [order structures]{@link https://docs.ccxt.com/?id=order-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> fetchClosedOrders(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object symbol = Helpers.getArg(optionalArgs, 0, null);
            Object since = Helpers.getArg(optionalArgs, 1, null);
            Object limit = Helpers.getArg(optionalArgs, 2, null);
            Object parameters = Helpers.getArg(optionalArgs, 3, new java.util.HashMap<String, Object>() {{}});
            Object request = new java.util.HashMap<String, Object>() {{
                put( "status", "3" );
            }};
            return (this.fetchOrders(symbol, since, limit, this.extend(request, parameters))).join();
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name btcalpha#fetchMyTrades
     * @description fetch all trades made by the user
     * @see https://btc-alpha.github.io/api-docs/#list-own-exchanges
     * @param {string} symbol unified market symbol
     * @param {int} [since] the earliest time in ms to fetch trades for
     * @param {int} [limit] the maximum number of trades structures to retrieve
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {Trade[]} a list of [trade structures]{@link https://docs.ccxt.com/?id=trade-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> fetchMyTrades(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object symbol = Helpers.getArg(optionalArgs, 0, null);
            Object since = Helpers.getArg(optionalArgs, 1, null);
            Object limit = Helpers.getArg(optionalArgs, 2, null);
            Object parameters = Helpers.getArg(optionalArgs, 3, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object request = new java.util.HashMap<String, Object>() {{}};
            if (Helpers.isTrue(!Helpers.isEqual(symbol, null)))
            {
                Object market = this.market(symbol);
                Helpers.addElementToObject(request, "pair", Helpers.GetValue(market, "id"));
            }
            if (Helpers.isTrue(!Helpers.isEqual(limit, null)))
            {
                Helpers.addElementToObject(request, "limit", limit);
            }
            Object trades = (this.privateGetExchangesOwn(this.extend(request, parameters))).join();
            return this.parseTrades(trades, null, since, limit);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public Object nonce()
    {
        return this.milliseconds();
    }

    public Object sign(Object path, Object... optionalArgs)
    {
        Object api = Helpers.getArg(optionalArgs, 0, "public");
        Object method = Helpers.getArg(optionalArgs, 1, "GET");
        Object parameters = Helpers.getArg(optionalArgs, 2, new java.util.HashMap<String, Object>() {{}});
        Object headers = Helpers.getArg(optionalArgs, 3, null);
        Object body = Helpers.getArg(optionalArgs, 4, null);
        Object query = this.urlencode(this.keysort(this.omit(parameters, this.extractParams(path))));
        Object url = Helpers.add(Helpers.GetValue(Helpers.GetValue(this.urls, "api"), "rest"), "/");
        if (Helpers.isTrue(!Helpers.isEqual(path, "charts/{pair}/{type}/chart/")))
        {
            url = Helpers.add(url, "v1/");
        }
        url = Helpers.add(url, this.implodeParams(path, parameters));
        headers = new java.util.HashMap<String, Object>() {{
            put( "Accept", "application/json" );
        }};
        if (Helpers.isTrue(Helpers.isEqual(api, "public")))
        {
            if (Helpers.isTrue(Helpers.getArrayLength(query)))
            {
                url = Helpers.add(url, Helpers.add("?", query));
            }
        } else
        {
            this.checkRequiredCredentials();
            Object payload = this.apiKey;
            if (Helpers.isTrue(Helpers.isEqual(method, "POST")))
            {
                Helpers.addElementToObject(headers, "Content-Type", "application/x-www-form-urlencoded");
                body = query;
                payload = Helpers.add(payload, body);
            } else if (Helpers.isTrue(Helpers.getArrayLength(query)))
            {
                url = Helpers.add(url, Helpers.add("?", query));
            }
            Helpers.addElementToObject(headers, "X-KEY", this.apiKey);
            Helpers.addElementToObject(headers, "X-SIGN", this.hmac(this.encode(payload), this.encode(this.secret), sha256()));
            Helpers.addElementToObject(headers, "X-NONCE", String.valueOf(this.nonce()));
        }
        final Object finalUrl = url;
        final Object finalMethod = method;
        final Object finalBody = body;
        final Object finalHeaders = headers;
        return new java.util.HashMap<String, Object>() {{
            put( "url", finalUrl );
            put( "method", finalMethod );
            put( "body", finalBody );
            put( "headers", finalHeaders );
        }};
    }

    public Object handleErrors(Object code, Object reason, Object url, Object method, Object headers, Object body, Object response, Object requestHeaders, Object requestBody)
    {
        if (Helpers.isTrue(Helpers.isEqual(response, null)))
        {
            return null;  // fallback to default error handler
        }
        //
        //     {"date":1570599531.4814300537,"error":"Out of balance -9.99243661 BTC"}
        //
        Object error = this.safeString(response, "error");
        if (Helpers.isTrue(!Helpers.isEqual(error, null)))
        {
            Object feedback = Helpers.add(Helpers.add(this.id, " "), body);
            this.throwExactlyMatchedException(Helpers.GetValue(this.exceptions, "exact"), error, feedback);
            this.throwBroadlyMatchedException(Helpers.GetValue(this.exceptions, "broad"), error, feedback);
            throw new ExchangeError((String)feedback) ;
        }
        return null;
    }
}
