package io.github.ccxt.exchanges;
import io.github.ccxt.api.OceanexApi;
import io.github.ccxt.base.Precise;
import io.github.ccxt.errors.*;
import io.github.ccxt.Helpers;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

public class Oceanex extends OceanexApi
{
   public Oceanex () {
       super();
   }

   public Oceanex (Object options) {
       super(options);
   }

    public Object describe()
    {
        return this.deepExtend(super.describe(), new java.util.HashMap<String, Object>() {{
            put( "id", "oceanex" );
            put( "name", "OceanEx" );
            put( "countries", new java.util.ArrayList<Object>(java.util.Arrays.asList("BS")) );
            put( "version", "v1" );
            put( "rateLimit", 3000 );
            put( "urls", new java.util.HashMap<String, Object>() {{
                put( "logo", "https://user-images.githubusercontent.com/1294454/58385970-794e2d80-8001-11e9-889c-0567cd79b78e.jpg" );
                put( "api", new java.util.HashMap<String, Object>() {{
                    put( "rest", "https://api.oceanex.pro" );
                }} );
                put( "www", "https://www.oceanex.pro.com" );
                put( "doc", "https://api.oceanex.pro/doc/v1" );
                put( "referral", "https://oceanex.pro/signup?referral=VE24QX" );
            }} );
            put( "has", new java.util.HashMap<String, Object>() {{
                put( "CORS", null );
                put( "spot", true );
                put( "margin", false );
                put( "swap", null );
                put( "future", null );
                put( "option", null );
                put( "cancelAllOrders", true );
                put( "cancelOrder", true );
                put( "cancelOrders", true );
                put( "createMarketOrder", true );
                put( "createOrder", true );
                put( "fetchBalance", true );
                put( "fetchBorrowRateHistories", false );
                put( "fetchBorrowRateHistory", false );
                put( "fetchClosedOrders", true );
                put( "fetchCrossBorrowRate", false );
                put( "fetchCrossBorrowRates", false );
                put( "fetchCurrencies", false );
                put( "fetchDepositAddress", "emulated" );
                put( "fetchDepositAddresses", null );
                put( "fetchDepositAddressesByNetwork", true );
                put( "fetchFundingRateHistory", false );
                put( "fetchFundingRates", false );
                put( "fetchIsolatedBorrowRate", false );
                put( "fetchIsolatedBorrowRates", false );
                put( "fetchMarkets", true );
                put( "fetchOHLCV", true );
                put( "fetchOpenOrders", true );
                put( "fetchOrder", true );
                put( "fetchOrderBook", true );
                put( "fetchOrderBooks", true );
                put( "fetchOrders", true );
                put( "fetchTicker", true );
                put( "fetchTickers", true );
                put( "fetchTime", true );
                put( "fetchTrades", true );
                put( "fetchTradingFee", false );
                put( "fetchTradingFees", true );
                put( "fetchTransactionFees", null );
            }} );
            put( "timeframes", new java.util.HashMap<String, Object>() {{
                put( "1m", "1" );
                put( "5m", "5" );
                put( "15m", "15" );
                put( "30m", "30" );
                put( "1h", "60" );
                put( "2h", "120" );
                put( "4h", "240" );
                put( "6h", "360" );
                put( "12h", "720" );
                put( "1d", "1440" );
                put( "3d", "4320" );
                put( "1w", "10080" );
            }} );
            put( "api", new java.util.HashMap<String, Object>() {{
                put( "public", new java.util.HashMap<String, Object>() {{
                    put( "get", new java.util.ArrayList<Object>(java.util.Arrays.asList("markets", "tickers/{pair}", "tickers_multi", "order_book", "order_book/multi", "fees/trading", "trades", "timestamp")) );
                    put( "post", new java.util.ArrayList<Object>(java.util.Arrays.asList("k")) );
                }} );
                put( "private", new java.util.HashMap<String, Object>() {{
                    put( "get", new java.util.ArrayList<Object>(java.util.Arrays.asList("key", "members/me", "orders", "orders/filter")) );
                    put( "post", new java.util.ArrayList<Object>(java.util.Arrays.asList("orders", "orders/multi", "order/delete", "order/delete/multi", "orders/clear", "/withdraws/special/new", "/deposit_address", "/deposit_addresses", "/deposit_history", "/withdraw_history")) );
                }} );
            }} );
            put( "fees", new java.util.HashMap<String, Object>() {{
                put( "trading", new java.util.HashMap<String, Object>() {{
                    put( "tierBased", false );
                    put( "percentage", true );
                    put( "maker", Oceanex.this.parseNumber("0.001") );
                    put( "taker", Oceanex.this.parseNumber("0.001") );
                }} );
            }} );
            put( "commonCurrencies", new java.util.HashMap<String, Object>() {{
                put( "PLA", "Plair" );
            }} );
            put( "precisionMode", TICK_SIZE );
            put( "features", new java.util.HashMap<String, Object>() {{
                put( "spot", new java.util.HashMap<String, Object>() {{
                    put( "sandbox", false );
                    put( "createOrder", new java.util.HashMap<String, Object>() {{
                        put( "marginMode", false );
                        put( "triggerPrice", true );
                        put( "triggerDirection", true );
                        put( "triggerPriceType", null );
                        put( "stopLossPrice", false );
                        put( "takeProfitPrice", false );
                        put( "attachedStopLossTakeProfit", null );
                        put( "timeInForce", new java.util.HashMap<String, Object>() {{
                            put( "IOC", false );
                            put( "FOK", false );
                            put( "PO", false );
                            put( "GTD", false );
                        }} );
                        put( "hedged", false );
                        put( "trailing", false );
                        put( "leverage", false );
                        put( "marketBuyByCost", false );
                        put( "marketBuyRequiresPrice", false );
                        put( "selfTradePrevention", false );
                        put( "iceberg", false );
                    }} );
                    put( "createOrders", null );
                    put( "fetchMyTrades", null );
                    put( "fetchOrder", new java.util.HashMap<String, Object>() {{
                        put( "marginMode", false );
                        put( "trigger", false );
                        put( "trailing", false );
                        put( "symbolRequired", false );
                    }} );
                    put( "fetchOpenOrders", new java.util.HashMap<String, Object>() {{
                        put( "marginMode", false );
                        put( "limit", 100 );
                        put( "trigger", false );
                        put( "trailing", false );
                        put( "symbolRequired", false );
                    }} );
                    put( "fetchOrders", new java.util.HashMap<String, Object>() {{
                        put( "marginMode", false );
                        put( "limit", 100 );
                        put( "daysBack", 100000 );
                        put( "untilDays", 100000 );
                        put( "trigger", false );
                        put( "trailing", false );
                        put( "symbolRequired", false );
                    }} );
                    put( "fetchClosedOrders", new java.util.HashMap<String, Object>() {{
                        put( "marginMode", false );
                        put( "limit", 100 );
                        put( "daysBack", 100000 );
                        put( "daysBackCanceled", 1 );
                        put( "untilDays", 100000 );
                        put( "trigger", false );
                        put( "trailing", false );
                        put( "symbolRequired", false );
                    }} );
                    put( "fetchOHLCV", new java.util.HashMap<String, Object>() {{
                        put( "limit", 100 );
                    }} );
                }} );
                put( "swap", new java.util.HashMap<String, Object>() {{
                    put( "linear", null );
                    put( "inverse", null );
                }} );
                put( "future", new java.util.HashMap<String, Object>() {{
                    put( "linear", null );
                    put( "inverse", null );
                }} );
            }} );
            put( "exceptions", new java.util.HashMap<String, Object>() {{
                put( "codes", new java.util.HashMap<String, Object>() {{
                    put( "-1", BadRequest.class );
                    put( "-2", BadRequest.class );
                    put( "1001", BadRequest.class );
                    put( "1004", ArgumentsRequired.class );
                    put( "1006", AuthenticationError.class );
                    put( "1008", AuthenticationError.class );
                    put( "1010", AuthenticationError.class );
                    put( "1011", PermissionDenied.class );
                    put( "2001", AuthenticationError.class );
                    put( "2002", InvalidOrder.class );
                    put( "2004", OrderNotFound.class );
                    put( "9003", PermissionDenied.class );
                }} );
                put( "exact", new java.util.HashMap<String, Object>() {{
                    put( "market does not have a valid value", BadRequest.class );
                    put( "side does not have a valid value", BadRequest.class );
                    put( "Account::AccountError: Cannot lock funds", InsufficientFunds.class );
                    put( "The account does not exist", AuthenticationError.class );
                }} );
            }} );
        }});
    }

    /**
     * @method
     * @name oceanex#fetchMarkets
     * @description retrieves data on all markets for oceanex
     * @see https://api.oceanex.pro/doc/v1/#markets-post
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object[]} an array of objects representing market data
     */
    public java.util.concurrent.CompletableFuture<Object> fetchMarkets(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object parameters = Helpers.getArg(optionalArgs, 0, new java.util.HashMap<String, Object>() {{}});
            Object request = new java.util.HashMap<String, Object>() {{
                put( "show_details", true );
            }};
            Object response = (this.publicGetMarkets(this.extend(request, parameters))).join();
            //
            //    {
            //        "id": "xtzusdt",
            //        "name": "XTZ/USDT",
            //        "ask_precision": "8",
            //        "bid_precision": "8",
            //        "enabled": true,
            //        "price_precision": "4",
            //        "amount_precision": "3",
            //        "usd_precision": "4",
            //        "minimum_trading_amount": "1.0"
            //    },
            //
            Object markets = this.safeValue(response, "data", new java.util.ArrayList<Object>(java.util.Arrays.asList()));
            return this.parseMarkets(markets);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public Object parseMarket(Object market)
    {
        Object id = this.safeValue(market, "id");
        Object name = this.safeValue(market, "name");
        var baseIdquoteIdVariable = Helpers.split(name, "/");
        var baseId = ((java.util.List<Object>) baseIdquoteIdVariable).get(0);
        var quoteId = ((java.util.List<Object>) baseIdquoteIdVariable).get(1);
        Object base = this.safeCurrencyCode(baseId);
        Object quote = this.safeCurrencyCode(quoteId);
        baseId = ((String)baseId).toLowerCase();
        quoteId = ((String)quoteId).toLowerCase();
        Object symbol = Helpers.add(Helpers.add(base, "/"), quote);
        final Object finalBase = base;
        final Object finalBaseId = baseId;
        final Object finalQuoteId = quoteId;
        return new java.util.HashMap<String, Object>() {{
            put( "id", id );
            put( "symbol", symbol );
            put( "base", finalBase );
            put( "quote", quote );
            put( "settle", null );
            put( "baseId", finalBaseId );
            put( "quoteId", finalQuoteId );
            put( "settleId", null );
            put( "type", "spot" );
            put( "spot", true );
            put( "margin", false );
            put( "swap", false );
            put( "future", false );
            put( "option", false );
            put( "active", null );
            put( "contract", false );
            put( "linear", null );
            put( "inverse", null );
            put( "contractSize", null );
            put( "expiry", null );
            put( "expiryDatetime", null );
            put( "strike", null );
            put( "optionType", null );
            put( "precision", new java.util.HashMap<String, Object>() {{
                put( "amount", Oceanex.this.parseNumber(Oceanex.this.parsePrecision(Oceanex.this.safeString(market, "amount_precision"))) );
                put( "price", Oceanex.this.parseNumber(Oceanex.this.parsePrecision(Oceanex.this.safeString(market, "price_precision"))) );
            }} );
            put( "limits", new java.util.HashMap<String, Object>() {{
                put( "leverage", new java.util.HashMap<String, Object>() {{
                    put( "min", null );
                    put( "max", null );
                }} );
                put( "amount", new java.util.HashMap<String, Object>() {{
                    put( "min", null );
                    put( "max", null );
                }} );
                put( "price", new java.util.HashMap<String, Object>() {{
                    put( "min", null );
                    put( "max", null );
                }} );
                put( "cost", new java.util.HashMap<String, Object>() {{
                    put( "min", Oceanex.this.safeNumber(market, "minimum_trading_amount") );
                    put( "max", null );
                }} );
            }} );
            put( "created", null );
            put( "info", market );
        }};
    }

    /**
     * @method
     * @name oceanex#fetchTicker
     * @description fetches a price ticker, a statistical calculation with the information calculated over the past 24 hours for a specific market
     * @see https://api.oceanex.pro/doc/v1/#ticker-post
     * @param {string} symbol unified symbol of the market to fetch the ticker for
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a [ticker structure]{@link https://docs.ccxt.com/?id=ticker-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> fetchTicker(Object symbol, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object parameters = Helpers.getArg(optionalArgs, 0, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object market = this.market(symbol);
            Object request = new java.util.HashMap<String, Object>() {{
                put( "pair", Helpers.GetValue(market, "id") );
            }};
            Object response = (this.publicGetTickersPair(this.extend(request, parameters))).join();
            //
            //     {
            //         "code":0,
            //         "message":"Operation successful",
            //         "data": {
            //             "at":1559431729,
            //             "ticker": {
            //                 "buy":"0.0065",
            //                 "sell":"0.00677",
            //                 "low":"0.00677",
            //                 "high":"0.00677",
            //                 "last":"0.00677",
            //                 "vol":"2000.0"
            //             }
            //         }
            //     }
            //
            Object data = this.safeDict(response, "data", new java.util.HashMap<String, Object>() {{}});
            return this.parseTicker(data, market);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name oceanex#fetchTickers
     * @description fetches price tickers for multiple markets, statistical information calculated over the past 24 hours for each market
     * @see https://api.oceanex.pro/doc/v1/#multiple-tickers-post
     * @param {string[]|undefined} symbols unified symbols of the markets to fetch the ticker for, all market tickers are returned if not assigned
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a dictionary of [ticker structures]{@link https://docs.ccxt.com/?id=ticker-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> fetchTickers(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object symbols = Helpers.getArg(optionalArgs, 0, null);
            Object parameters = Helpers.getArg(optionalArgs, 1, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            symbols = this.marketSymbols(symbols);
            if (Helpers.isTrue(Helpers.isEqual(symbols, null)))
            {
                symbols = this.symbols;
            }
            Object marketIds = this.marketIds(symbols);
            Object request = new java.util.HashMap<String, Object>() {{
                put( "markets", marketIds );
            }};
            Object response = (this.publicGetTickersMulti(this.extend(request, parameters))).join();
            //
            //     {
            //         "code":0,
            //         "message":"Operation successful",
            //         "data": {
            //             "at":1559431729,
            //             "ticker": {
            //                 "buy":"0.0065",
            //                 "sell":"0.00677",
            //                 "low":"0.00677",
            //                 "high":"0.00677",
            //                 "last":"0.00677",
            //                 "vol":"2000.0"
            //             }
            //         }
            //     }
            //
            Object data = this.safeValue(response, "data", new java.util.ArrayList<Object>(java.util.Arrays.asList()));
            Object result = new java.util.HashMap<String, Object>() {{}};
            for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(data)); i++)
            {
                Object ticker = Helpers.GetValue(data, i);
                Object marketId = this.safeString(ticker, "market");
                Object market = this.safeMarket(marketId);
                Object symbol = Helpers.GetValue(market, "symbol");
                Helpers.addElementToObject(result, symbol, this.parseTicker(ticker, market));
            }
            return this.filterByArrayTickers(result, "symbol", symbols);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public Object parseTicker(Object data, Object... optionalArgs)
    {
        //
        //         {
        //             "at":1559431729,
        //             "ticker": {
        //                 "buy":"0.0065",
        //                 "sell":"0.00677",
        //                 "low":"0.00677",
        //                 "high":"0.00677",
        //                 "last":"0.00677",
        //                 "vol":"2000.0"
        //             }
        //         }
        //
        Object market = Helpers.getArg(optionalArgs, 0, null);
        Object ticker = this.safeValue(data, "ticker", new java.util.HashMap<String, Object>() {{}});
        Object timestamp = this.safeTimestamp(data, "at");
        Object symbol = this.safeSymbol(null, market);
        return this.safeTicker(new java.util.HashMap<String, Object>() {{
            put( "symbol", symbol );
            put( "timestamp", timestamp );
            put( "datetime", Oceanex.this.iso8601(timestamp) );
            put( "high", Oceanex.this.safeString(ticker, "high") );
            put( "low", Oceanex.this.safeString(ticker, "low") );
            put( "bid", Oceanex.this.safeString(ticker, "buy") );
            put( "bidVolume", null );
            put( "ask", Oceanex.this.safeString(ticker, "sell") );
            put( "askVolume", null );
            put( "vwap", null );
            put( "open", null );
            put( "close", Oceanex.this.safeString(ticker, "last") );
            put( "last", Oceanex.this.safeString(ticker, "last") );
            put( "previousClose", null );
            put( "change", null );
            put( "percentage", null );
            put( "average", null );
            put( "baseVolume", Oceanex.this.safeString(ticker, "volume") );
            put( "quoteVolume", null );
            put( "info", ticker );
        }}, market);
    }

    /**
     * @method
     * @name oceanex#fetchOrderBook
     * @description fetches information on open orders with bid (buy) and ask (sell) prices, volumes and other data
     * @see https://api.oceanex.pro/doc/v1/#order-book-post
     * @param {string} symbol unified symbol of the market to fetch the order book for
     * @param {int} [limit] the maximum amount of order book entries to return
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} A dictionary of [order book structures]{@link https://docs.ccxt.com/?id=order-book-structure} indexed by market symbols
     */
    public java.util.concurrent.CompletableFuture<Object> fetchOrderBook(Object symbol, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object limit = Helpers.getArg(optionalArgs, 0, null);
            Object parameters = Helpers.getArg(optionalArgs, 1, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object market = this.market(symbol);
            Object request = new java.util.HashMap<String, Object>() {{
                put( "market", Helpers.GetValue(market, "id") );
            }};
            if (Helpers.isTrue(!Helpers.isEqual(limit, null)))
            {
                Helpers.addElementToObject(request, "limit", limit);
            }
            Object response = (this.publicGetOrderBook(this.extend(request, parameters))).join();
            //
            //     {
            //         "code":0,
            //         "message":"Operation successful",
            //         "data": {
            //             "timestamp":1559433057,
            //             "asks": [
            //                 ["100.0","20.0"],
            //                 ["4.74","2000.0"],
            //                 ["1.74","4000.0"],
            //             ],
            //             "bids":[
            //                 ["0.0065","5482873.4"],
            //                 ["0.00649","4781956.2"],
            //                 ["0.00648","2876006.8"],
            //             ],
            //         }
            //     }
            //
            Object orderbook = this.safeValue(response, "data", new java.util.HashMap<String, Object>() {{}});
            Object timestamp = this.safeTimestamp(orderbook, "timestamp");
            return this.parseOrderBook(orderbook, symbol, timestamp);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name oceanex#fetchOrderBooks
     * @description fetches information on open orders with bid (buy) and ask (sell) prices, volumes and other data for multiple markets
     * @see https://api.oceanex.pro/doc/v1/#multiple-order-books-post
     * @param {string[]|undefined} symbols list of unified market symbols, all symbols fetched if undefined, default is undefined
     * @param {int} [limit] max number of entries per orderbook to return, default is undefined
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a dictionary of [order book structures]{@link https://docs.ccxt.com/?id=order-book-structure} indexed by market symbol
     */
    public java.util.concurrent.CompletableFuture<Object> fetchOrderBooks(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object symbols = Helpers.getArg(optionalArgs, 0, null);
            Object limit = Helpers.getArg(optionalArgs, 1, null);
            Object parameters = Helpers.getArg(optionalArgs, 2, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            if (Helpers.isTrue(Helpers.isEqual(symbols, null)))
            {
                symbols = this.symbols;
            }
            Object marketIds = this.marketIds(symbols);
            Object request = new java.util.HashMap<String, Object>() {{
                put( "markets", marketIds );
            }};
            if (Helpers.isTrue(!Helpers.isEqual(limit, null)))
            {
                Helpers.addElementToObject(request, "limit", limit);
            }
            Object response = (this.publicGetOrderBookMulti(this.extend(request, parameters))).join();
            //
            //     {
            //         "code":0,
            //         "message":"Operation successful",
            //         "data": [
            //             {
            //                 "timestamp":1559433057,
            //                 "market": "bagvet",
            //                 "asks": [
            //                     ["100.0","20.0"],
            //                     ["4.74","2000.0"],
            //                     ["1.74","4000.0"],
            //                 ],
            //                 "bids":[
            //                     ["0.0065","5482873.4"],
            //                     ["0.00649","4781956.2"],
            //                     ["0.00648","2876006.8"],
            //                 ],
            //             },
            //             ...,
            //         ],
            //     }
            //
            Object data = this.safeValue(response, "data", new java.util.ArrayList<Object>(java.util.Arrays.asList()));
            Object result = new java.util.HashMap<String, Object>() {{}};
            for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(data)); i++)
            {
                Object orderbook = Helpers.GetValue(data, i);
                Object marketId = this.safeString(orderbook, "market");
                Object symbol = this.safeSymbol(marketId);
                Object timestamp = this.safeTimestamp(orderbook, "timestamp");
                Helpers.addElementToObject(result, symbol, this.parseOrderBook(orderbook, symbol, timestamp));
            }
            return result;
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name oceanex#fetchTrades
     * @description get the list of most recent trades for a particular symbol
     * @see https://api.oceanex.pro/doc/v1/#trades-post
     * @param {string} symbol unified symbol of the market to fetch trades for
     * @param {int} [since] timestamp in ms of the earliest trade to fetch
     * @param {int} [limit] the maximum amount of trades to fetch
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {Trade[]} a list of [trade structures]{@link https://docs.ccxt.com/?id=public-trades}
     */
    public java.util.concurrent.CompletableFuture<Object> fetchTrades(Object symbol, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object since = Helpers.getArg(optionalArgs, 0, null);
            Object limit = Helpers.getArg(optionalArgs, 1, null);
            Object parameters = Helpers.getArg(optionalArgs, 2, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object market = this.market(symbol);
            Object request = new java.util.HashMap<String, Object>() {{
                put( "market", Helpers.GetValue(market, "id") );
            }};
            if (Helpers.isTrue(!Helpers.isEqual(limit, null)))
            {
                Helpers.addElementToObject(request, "limit", Helpers.mathMin(limit, 1000));
            }
            Object response = (this.publicGetTrades(this.extend(request, parameters))).join();
            //
            //      {
            //          "code":0,
            //          "message":"Operation successful",
            //          "data": [
            //              {
            //                  "id":220247666,
            //                  "price":"3098.62",
            //                  "volume":"0.00196",
            //                  "funds":"6.0732952",
            //                  "market":"ethusdt",
            //                  "created_at":"2022-04-19T19:03:15Z",
            //                  "created_on":1650394994,
            //                  "side":"bid"
            //              },
            //          ]
            //      }
            //
            Object data = this.safeList(response, "data");
            return this.parseTrades(data, market, since, limit);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public Object parseTrade(Object trade, Object... optionalArgs)
    {
        //
        // fetchTrades (public)
        //
        //      {
        //          "id":220247666,
        //          "price":"3098.62",
        //          "volume":"0.00196",
        //          "funds":"6.0732952",
        //          "market":"ethusdt",
        //          "created_at":"2022-04-19T19:03:15Z",
        //          "created_on":1650394995,
        //          "side":"bid"
        //      }
        //
        Object market = Helpers.getArg(optionalArgs, 0, null);
        Object side = this.safeValue(trade, "side");
        if (Helpers.isTrue(Helpers.isEqual(side, "bid")))
        {
            side = "buy";
        } else if (Helpers.isTrue(Helpers.isEqual(side, "ask")))
        {
            side = "sell";
        }
        Object marketId = this.safeValue(trade, "market");
        Object symbol = this.safeSymbol(marketId, market);
        Object timestamp = this.safeTimestamp(trade, "created_on");
        if (Helpers.isTrue(Helpers.isEqual(timestamp, null)))
        {
            timestamp = this.parse8601(this.safeString(trade, "created_at"));
        }
        Object priceString = this.safeString(trade, "price");
        Object amountString = this.safeString(trade, "volume");
        final Object finalTimestamp = timestamp;
        final Object finalSide = side;
        return this.safeTrade(new java.util.HashMap<String, Object>() {{
            put( "info", trade );
            put( "timestamp", finalTimestamp );
            put( "datetime", Oceanex.this.iso8601(finalTimestamp) );
            put( "symbol", symbol );
            put( "id", Oceanex.this.safeString(trade, "id") );
            put( "order", null );
            put( "type", "limit" );
            put( "takerOrMaker", null );
            put( "side", finalSide );
            put( "price", priceString );
            put( "amount", amountString );
            put( "cost", null );
            put( "fee", null );
        }}, market);
    }

    /**
     * @method
     * @name oceanex#fetchTime
     * @description fetches the current integer timestamp in milliseconds from the exchange server
     * @see https://api.oceanex.pro/doc/v1/#api-server-time-post
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {int} the current integer timestamp in milliseconds from the exchange server
     */
    public java.util.concurrent.CompletableFuture<Object> fetchTime(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object parameters = Helpers.getArg(optionalArgs, 0, new java.util.HashMap<String, Object>() {{}});
            Object response = (this.publicGetTimestamp(parameters)).join();
            //
            //     {"code":0,"message":"Operation successful","data":1559433420}
            //
            return this.safeTimestamp(response, "data");
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name oceanex#fetchTradingFees
     * @description fetch the trading fees for multiple markets
     * @see https://api.oceanex.pro/doc/v1/#trading-fees-post
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a dictionary of [fee structures]{@link https://docs.ccxt.com/?id=fee-structure} indexed by market symbols
     */
    public java.util.concurrent.CompletableFuture<Object> fetchTradingFees(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object parameters = Helpers.getArg(optionalArgs, 0, new java.util.HashMap<String, Object>() {{}});
            Object response = (this.publicGetFeesTrading(parameters)).join();
            Object data = this.safeValue(response, "data", new java.util.ArrayList<Object>(java.util.Arrays.asList()));
            Object result = new java.util.HashMap<String, Object>() {{}};
            for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(data)); i++)
            {
                Object group = Helpers.GetValue(data, i);
                Object maker = this.safeValue(group, "ask_fee", new java.util.HashMap<String, Object>() {{}});
                Object taker = this.safeValue(group, "bid_fee", new java.util.HashMap<String, Object>() {{}});
                Object marketId = this.safeString(group, "market");
                Object symbol = this.safeSymbol(marketId);
                Helpers.addElementToObject(result, symbol, new java.util.HashMap<String, Object>() {{
        put( "info", group );
        put( "symbol", symbol );
        put( "maker", Oceanex.this.safeNumber(maker, "value") );
        put( "taker", Oceanex.this.safeNumber(taker, "value") );
        put( "percentage", true );
    }});
            }
            return result;
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public java.util.concurrent.CompletableFuture<Object> fetchKey(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object parameters = Helpers.getArg(optionalArgs, 0, new java.util.HashMap<String, Object>() {{}});
            Object response = (this.privateGetKey(parameters)).join();
            return this.safeValue(response, "data");
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public Object parseBalance(Object response)
    {
        Object data = this.safeValue(response, "data");
        Object balances = this.safeValue(data, "accounts", new java.util.ArrayList<Object>(java.util.Arrays.asList()));
        Object result = new java.util.HashMap<String, Object>() {{
            put( "info", response );
        }};
        for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(balances)); i++)
        {
            Object balance = Helpers.GetValue(balances, i);
            Object currencyId = this.safeValue(balance, "currency");
            Object code = this.safeCurrencyCode(currencyId);
            Object account = this.account();
            Helpers.addElementToObject(account, "free", this.safeString(balance, "balance"));
            Helpers.addElementToObject(account, "used", this.safeString(balance, "locked"));
            Helpers.addElementToObject(result, code, account);
        }
        return this.safeBalance(result);
    }

    /**
     * @method
     * @name oceanex#fetchBalance
     * @description query for balance and get the amount of funds available for trading or funds locked in orders
     * @see https://api.oceanex.pro/doc/v1/#account-info-post
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a [balance structure]{@link https://docs.ccxt.com/?id=balance-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> fetchBalance(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object parameters = Helpers.getArg(optionalArgs, 0, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object response = (this.privateGetMembersMe(parameters)).join();
            return this.parseBalance(response);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name oceanex#createOrder
     * @description create a trade order
     * @see https://api.oceanex.pro/doc/v1/#new-order-post
     * @param {string} symbol unified symbol of the market to create an order in
     * @param {string} type 'market' or 'limit'
     * @param {string} side 'buy' or 'sell'
     * @param {float} amount how much of currency you want to trade in units of base currency
     * @param {float} [price] the price at which the order is to be fulfilled, in units of the quote currency, ignored in market orders
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} an [order structure]{@link https://docs.ccxt.com/?id=order-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> createOrder(Object symbol, Object type2, Object side, Object amount, Object... optionalArgs)
    {
        final Object type3 = type2;
        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {
            Object type = type3;
            Object price = Helpers.getArg(optionalArgs, 0, null);
            Object parameters = Helpers.getArg(optionalArgs, 1, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object market = this.market(symbol);
            Object request = new java.util.HashMap<String, Object>() {{
                put( "market", Helpers.GetValue(market, "id") );
                put( "side", side );
                put( "ord_type", type );
                put( "volume", Oceanex.this.amountToPrecision(symbol, amount) );
            }};
            if (Helpers.isTrue(Helpers.isEqual(type, "limit")))
            {
                Helpers.addElementToObject(request, "price", this.priceToPrecision(symbol, price));
            }
            Object response = (this.privatePostOrders(this.extend(request, parameters))).join();
            Object data = this.safeDict(response, "data");
            return this.parseOrder(data, market);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name oceanex#fetchOrder
     * @description fetches information on an order made by the user
     * @see https://api.oceanex.pro/doc/v1/#order-status-get
     * @param {string} id order id
     * @param {string} symbol unified symbol of the market the order was made in
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} An [order structure]{@link https://docs.ccxt.com/?id=order-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> fetchOrder(Object id, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object symbol = Helpers.getArg(optionalArgs, 0, null);
            Object parameters = Helpers.getArg(optionalArgs, 1, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object market = null;
            if (Helpers.isTrue(!Helpers.isEqual(symbol, null)))
            {
                market = this.market(symbol);
            }
            Object ids = new java.util.ArrayList<Object>(java.util.Arrays.asList(id));
            Object request = new java.util.HashMap<String, Object>() {{
                put( "ids", ids );
            }};
            Object response = (this.privateGetOrders(this.extend(request, parameters))).join();
            Object data = this.safeValue(response, "data");
            Object dataLength = Helpers.getArrayLength(data);
            if (Helpers.isTrue(Helpers.isEqual(data, null)))
            {
                throw new OrderNotFound((String)Helpers.add(this.id, " could not found matching order")) ;
            }
            if (Helpers.isTrue(((id instanceof java.util.List) || (id.getClass().isArray()))))
            {
                Object orders = this.parseOrders(data, market);
                return Helpers.GetValue(orders, 0);
            }
            if (Helpers.isTrue(Helpers.isEqual(dataLength, 0)))
            {
                throw new OrderNotFound((String)Helpers.add(this.id, " could not found matching order")) ;
            }
            return this.parseOrder(Helpers.GetValue(data, 0), market);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name oceanex#fetchOpenOrders
     * @description fetch all unfilled currently open orders
     * @see https://api.oceanex.pro/doc/v1/#order-status-get
     * @param {string} symbol unified market symbol
     * @param {int} [since] the earliest time in ms to fetch open orders for
     * @param {int} [limit] the maximum number of  open orders structures to retrieve
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {Order[]} a list of [order structures]{@link https://docs.ccxt.com/?id=order-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> fetchOpenOrders(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object symbol = Helpers.getArg(optionalArgs, 0, null);
            Object since = Helpers.getArg(optionalArgs, 1, null);
            Object limit = Helpers.getArg(optionalArgs, 2, null);
            Object parameters = Helpers.getArg(optionalArgs, 3, new java.util.HashMap<String, Object>() {{}});
            Object request = new java.util.HashMap<String, Object>() {{
                put( "states", new java.util.ArrayList<Object>(java.util.Arrays.asList("wait")) );
            }};
            return (this.fetchOrders(symbol, since, limit, this.extend(request, parameters))).join();
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name oceanex#fetchClosedOrders
     * @description fetches information on multiple closed orders made by the user
     * @see https://api.oceanex.pro/doc/v1/#order-status-get
     * @param {string} symbol unified market symbol of the market orders were made in
     * @param {int} [since] the earliest time in ms to fetch orders for
     * @param {int} [limit] the maximum number of order structures to retrieve
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {Order[]} a list of [order structures]{@link https://docs.ccxt.com/?id=order-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> fetchClosedOrders(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object symbol = Helpers.getArg(optionalArgs, 0, null);
            Object since = Helpers.getArg(optionalArgs, 1, null);
            Object limit = Helpers.getArg(optionalArgs, 2, null);
            Object parameters = Helpers.getArg(optionalArgs, 3, new java.util.HashMap<String, Object>() {{}});
            Object request = new java.util.HashMap<String, Object>() {{
                put( "states", new java.util.ArrayList<Object>(java.util.Arrays.asList("done", "cancel")) );
            }};
            return (this.fetchOrders(symbol, since, limit, this.extend(request, parameters))).join();
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name oceanex#fetchOrders
     * @description fetches information on multiple orders made by the user
     * @see https://api.oceanex.pro/doc/v1/#order-status-with-filters-post
     * @param {string} symbol unified market symbol of the market orders were made in
     * @param {int} [since] the earliest time in ms to fetch orders for
     * @param {int} [limit] the maximum number of order structures to retrieve
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {Order[]} a list of [order structures]{@link https://docs.ccxt.com/?id=order-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> fetchOrders(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object symbol = Helpers.getArg(optionalArgs, 0, null);
            Object since = Helpers.getArg(optionalArgs, 1, null);
            Object limit = Helpers.getArg(optionalArgs, 2, null);
            Object parameters = Helpers.getArg(optionalArgs, 3, new java.util.HashMap<String, Object>() {{}});
            if (Helpers.isTrue(Helpers.isEqual(symbol, null)))
            {
                throw new ArgumentsRequired((String)Helpers.add(this.id, " fetchOrders() requires a symbol argument")) ;
            }
            (this.loadMarkets()).join();
            Object market = this.market(symbol);
            Object states = this.safeValue(parameters, "states", new java.util.ArrayList<Object>(java.util.Arrays.asList("wait", "done", "cancel")));
            Object query = this.omit(parameters, "states");
            Object request = new java.util.HashMap<String, Object>() {{
                put( "market", Helpers.GetValue(market, "id") );
                put( "states", states );
                put( "need_price", "True" );
            }};
            if (Helpers.isTrue(!Helpers.isEqual(limit, null)))
            {
                Helpers.addElementToObject(request, "limit", limit);
            }
            Object response = (this.privateGetOrdersFilter(this.extend(request, query))).join();
            Object data = this.safeValue(response, "data", new java.util.ArrayList<Object>(java.util.Arrays.asList()));
            Object result = new java.util.ArrayList<Object>(java.util.Arrays.asList());
            for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(data)); i++)
            {
                Object orders = this.safeValue(Helpers.GetValue(data, i), "orders", new java.util.ArrayList<Object>(java.util.Arrays.asList()));
                Object status = this.parseOrderStatus(this.safeValue(Helpers.GetValue(data, i), "state"));
                Object parsedOrders = this.parseOrders(orders, market, since, limit, new java.util.HashMap<String, Object>() {{
                    put( "status", status );
                }});
                result = this.arrayConcat(result, parsedOrders);
            }
            return result;
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public Object parseOHLCV(Object ohlcv, Object... optionalArgs)
    {
        // [
        //    1559232000,
        //    8889.22,
        //    9028.52,
        //    8889.22,
        //    9028.52
        //    0.3121
        // ]
        Object market = Helpers.getArg(optionalArgs, 0, null);
        return new java.util.ArrayList<Object>(java.util.Arrays.asList(this.safeTimestamp(ohlcv, 0), this.safeNumber(ohlcv, 1), this.safeNumber(ohlcv, 2), this.safeNumber(ohlcv, 3), this.safeNumber(ohlcv, 4), this.safeNumber(ohlcv, 5)));
    }

    /**
     * @method
     * @name oceanex#fetchOHLCV
     * @description fetches historical candlestick data containing the open, high, low, and close price, and the volume of a market
     * @see https://api.oceanex.pro/doc/v1/#k-line-post
     * @param {string} symbol unified symbol of the market to fetch OHLCV data for
     * @param {string} timeframe the length of time each candle represents
     * @param {int} [since] timestamp in ms of the earliest candle to fetch
     * @param {int} [limit] the maximum amount of candles to fetch
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {int[][]} A list of candles ordered as timestamp, open, high, low, close, volume
     */
    public java.util.concurrent.CompletableFuture<Object> fetchOHLCV(Object symbol, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object timeframe = Helpers.getArg(optionalArgs, 0, "1m");
            Object since = Helpers.getArg(optionalArgs, 1, null);
            Object limit = Helpers.getArg(optionalArgs, 2, null);
            Object parameters = Helpers.getArg(optionalArgs, 3, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object market = this.market(symbol);
            Object request = new java.util.HashMap<String, Object>() {{
                put( "market", Helpers.GetValue(market, "id") );
                put( "period", Oceanex.this.safeString(Oceanex.this.timeframes, timeframe, timeframe) );
            }};
            if (Helpers.isTrue(!Helpers.isEqual(since, null)))
            {
                Helpers.addElementToObject(request, "timestamp", since);
            }
            if (Helpers.isTrue(!Helpers.isEqual(limit, null)))
            {
                Helpers.addElementToObject(request, "limit", Helpers.mathMin(limit, 10000));
            }
            Object response = (this.publicPostK(this.extend(request, parameters))).join();
            Object ohlcvs = this.safeList(response, "data", new java.util.ArrayList<Object>(java.util.Arrays.asList()));
            return this.parseOHLCVs(ohlcvs, market, timeframe, since, limit);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public Object parseOrder(Object order, Object... optionalArgs)
    {
        //
        //     {
        //         "created_at": "2019-01-18T00:38:18Z",
        //         "trades_count": 0,
        //         "remaining_volume": "0.2",
        //         "price": "1001.0",
        //         "created_on": "1547771898",
        //         "side": "buy",
        //         "volume": "0.2",
        //         "state": "wait",
        //         "ord_type": "limit",
        //         "avg_price": "0.0",
        //         "executed_volume": "0.0",
        //         "id": 473797,
        //         "market": "veteth"
        //     }
        //
        Object market = Helpers.getArg(optionalArgs, 0, null);
        Object status = this.parseOrderStatus(this.safeValue(order, "state"));
        Object marketId = this.safeString2(order, "market", "market_id");
        Object symbol = this.safeSymbol(marketId, market);
        Object timestamp = this.safeTimestamp(order, "created_on");
        if (Helpers.isTrue(Helpers.isEqual(timestamp, null)))
        {
            timestamp = this.parse8601(this.safeString(order, "created_at"));
        }
        Object price = this.safeString(order, "price");
        Object average = this.safeString(order, "avg_price");
        Object amount = this.safeString(order, "volume");
        Object remaining = this.safeString(order, "remaining_volume");
        Object filled = this.safeString(order, "executed_volume");
        final Object finalTimestamp = timestamp;
        return this.safeOrder(new java.util.HashMap<String, Object>() {{
            put( "info", order );
            put( "id", Oceanex.this.safeString(order, "id") );
            put( "clientOrderId", null );
            put( "timestamp", finalTimestamp );
            put( "datetime", Oceanex.this.iso8601(finalTimestamp) );
            put( "lastTradeTimestamp", null );
            put( "symbol", symbol );
            put( "type", Oceanex.this.safeValue(order, "ord_type") );
            put( "timeInForce", null );
            put( "postOnly", null );
            put( "side", Oceanex.this.safeValue(order, "side") );
            put( "price", price );
            put( "triggerPrice", null );
            put( "average", average );
            put( "amount", amount );
            put( "remaining", remaining );
            put( "filled", filled );
            put( "status", status );
            put( "cost", null );
            put( "trades", null );
            put( "fee", null );
        }}, market);
    }

    public Object parseOrderStatus(Object status)
    {
        Object statuses = new java.util.HashMap<String, Object>() {{
            put( "wait", "open" );
            put( "done", "closed" );
            put( "cancel", "canceled" );
        }};
        return this.safeString(statuses, status, status);
    }

    /**
     * @method
     * @name oceanex#cancelOrder
     * @description cancels an open order
     * @see https://api.oceanex.pro/doc/v1/#cancel-order-post
     * @param {string} id order id
     * @param {string} symbol not used by oceanex cancelOrder ()
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} An [order structure]{@link https://docs.ccxt.com/?id=order-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> cancelOrder(Object id, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object symbol = Helpers.getArg(optionalArgs, 0, null);
            Object parameters = Helpers.getArg(optionalArgs, 1, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object response = (this.privatePostOrderDelete(this.extend(new java.util.HashMap<String, Object>() {{
                put( "id", id );
            }}, parameters))).join();
            Object data = this.safeDict(response, "data");
            return this.parseOrder(data);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name oceanex#cancelOrders
     * @description cancel multiple orders
     * @see https://api.oceanex.pro/doc/v1/#cancel-multiple-orders-post
     * @param {string[]} ids order ids
     * @param {string} symbol not used by oceanex cancelOrders ()
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} an list of [order structures]{@link https://docs.ccxt.com/?id=order-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> cancelOrders(Object ids, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object symbol = Helpers.getArg(optionalArgs, 0, null);
            Object parameters = Helpers.getArg(optionalArgs, 1, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object response = (this.privatePostOrderDeleteMulti(this.extend(new java.util.HashMap<String, Object>() {{
                put( "ids", ids );
            }}, parameters))).join();
            Object data = this.safeList(response, "data");
            return this.parseOrders(data);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name oceanex#cancelAllOrders
     * @description cancel all open orders
     * @see https://api.oceanex.pro/doc/v1/#cancel-all-orders-post
     * @param {string} symbol unified market symbol, only orders in the market of this symbol are cancelled when symbol is not undefined
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object[]} a list of [order structures]{@link https://docs.ccxt.com/?id=order-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> cancelAllOrders(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object symbol = Helpers.getArg(optionalArgs, 0, null);
            Object parameters = Helpers.getArg(optionalArgs, 1, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object response = (this.privatePostOrdersClear(parameters)).join();
            Object data = this.safeList(response, "data");
            return this.parseOrders(data);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name oceanex#fetchDepositAddressesByNetwork
     * @description fetch the deposit addresses for a currency associated with this account
     * @see https://api.oceanex.pro/doc/v1/#deposit-addresses-post
     * @param {string} code unified currency code
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a dictionary [address structures]{@link https://docs.ccxt.com/?id=address-structure}, indexed by the network
     */
    public java.util.concurrent.CompletableFuture<Object> fetchDepositAddressesByNetwork(Object code, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object parameters = Helpers.getArg(optionalArgs, 0, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object currency = this.currency(code);
            Object request = new java.util.HashMap<String, Object>() {{
                put( "currency", Helpers.GetValue(currency, "id") );
            }};
            Object response = (this.privatePostDepositAddresses(this.extend(request, parameters))).join();
            //
            //    {
            //        code: '0',
            //        message: 'Operation successful',
            //        data: {
            //          data: {
            //            currency_id: 'usdt',
            //            display_name: 'USDT',
            //            num_of_resources: '3',
            //            resources: [
            //              {
            //                chain_name: 'TRC20',
            //                currency_id: 'usdt',
            //                address: 'TPcS7VgKMFmpRrWY82GbJzDeMnemWxEbpg',
            //                memo: '',
            //                deposit_status: 'enabled'
            //              },
            //              ...
            //            ]
            //          }
            //        }
            //    }
            //
            Object data = this.safeDict(response, "data", new java.util.HashMap<String, Object>() {{}});
            Object data2 = this.safeDict(data, "data", new java.util.HashMap<String, Object>() {{}});
            Object resources = this.safeList(data2, "resources", new java.util.ArrayList<Object>(java.util.Arrays.asList()));
            Object result = new java.util.HashMap<String, Object>() {{}};
            for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(resources)); i++)
            {
                Object resource = Helpers.GetValue(resources, i);
                Object enabled = this.safeString(resource, "deposit_status");
                if (Helpers.isTrue(Helpers.isEqual(enabled, "enabled")))
                {
                    Object parsedAddress = this.parseDepositAddress(resource, currency);
                    Helpers.addElementToObject(result, Helpers.GetValue(parsedAddress, "currency"), parsedAddress);
                }
            }
            return result;
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public Object parseDepositAddress(Object depositAddress, Object... optionalArgs)
    {
        //
        //    {
        //        chain_name: 'TRC20',
        //        currency_id: 'usdt',
        //        address: 'TPcS7VgKMFmpRrWY82GbJzDeMnemWxEbpg',
        //        memo: '',
        //        deposit_status: 'enabled'
        //    }
        //
        Object currency = Helpers.getArg(optionalArgs, 0, null);
        Object address = this.safeString(depositAddress, "address");
        this.checkAddress(address);
        Object currencyId = this.safeString(depositAddress, "currency_id");
        Object networkId = this.safeString(depositAddress, "chain_name");
        return new java.util.HashMap<String, Object>() {{
            put( "info", depositAddress );
            put( "currency", Oceanex.this.safeCurrencyCode(currencyId, currency) );
            put( "network", Oceanex.this.networkIdToCode(networkId) );
            put( "address", address );
            put( "tag", Oceanex.this.safeString(depositAddress, "memo") );
        }};
    }

    public Object sign(Object path, Object... optionalArgs)
    {
        Object api = Helpers.getArg(optionalArgs, 0, "public");
        Object method = Helpers.getArg(optionalArgs, 1, "GET");
        Object parameters = Helpers.getArg(optionalArgs, 2, new java.util.HashMap<String, Object>() {{}});
        Object headers = Helpers.getArg(optionalArgs, 3, null);
        Object body = Helpers.getArg(optionalArgs, 4, null);
        Object url = Helpers.add(Helpers.add(Helpers.add(Helpers.add(Helpers.GetValue(Helpers.GetValue(this.urls, "api"), "rest"), "/"), this.version), "/"), this.implodeParams(path, parameters));
        Object query = this.omit(parameters, this.extractParams(path));
        if (Helpers.isTrue(Helpers.isEqual(api, "public")))
        {
            if (Helpers.isTrue(Helpers.isTrue(Helpers.isEqual(path, "tickers_multi")) || Helpers.isTrue(Helpers.isEqual(path, "order_book/multi"))))
            {
                Object request = "?";
                Object markets = this.safeValue(parameters, "markets");
                for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(markets)); i++)
                {
                    request = Helpers.add(request, Helpers.add(Helpers.add("markets[]=", Helpers.GetValue(markets, i)), "&"));
                }
                Object limit = this.safeValue(parameters, "limit");
                if (Helpers.isTrue(!Helpers.isEqual(limit, null)))
                {
                    request = Helpers.add(request, Helpers.add("limit=", limit));
                }
                url = Helpers.add(url, request);
            } else if (Helpers.isTrue(Helpers.getArrayLength(new java.util.ArrayList<Object>(((java.util.Map<String, Object>)query).keySet()))))
            {
                url = Helpers.add(url, Helpers.add("?", this.urlencode(query)));
            }
        } else if (Helpers.isTrue(Helpers.isEqual(api, "private")))
        {
            this.checkRequiredCredentials();
            Object request = new java.util.HashMap<String, Object>() {{
                put( "uid", Oceanex.this.apiKey );
                put( "data", query );
            }};
            // to set the private key:
            // const fs = require ('fs')
            // exchange.secret = fs.readFileSync ('oceanex.pem', 'utf8')
            Object jwt_token = jwt(request, this.encode(this.secret), sha256(), true);
            url = Helpers.add(url, Helpers.add("?user_jwt=", jwt_token));
        }
        headers = new java.util.HashMap<String, Object>() {{
            put( "Content-Type", "application/json" );
        }};
        final Object finalUrl = url;
        final Object finalHeaders = headers;
        return new java.util.HashMap<String, Object>() {{
            put( "url", finalUrl );
            put( "method", method );
            put( "body", body );
            put( "headers", finalHeaders );
        }};
    }

    public Object handleErrors(Object code, Object reason, Object url, Object method, Object headers, Object body, Object response, Object requestHeaders, Object requestBody)
    {
        //
        //     {"code":1011,"message":"This IP 'x.x.x.x' is not allowed","data":{}}
        //
        if (Helpers.isTrue(Helpers.isEqual(response, null)))
        {
            return null;
        }
        Object errorCode = this.safeString(response, "code");
        Object message = this.safeString(response, "message");
        if (Helpers.isTrue(Helpers.isTrue((!Helpers.isEqual(errorCode, null))) && Helpers.isTrue((!Helpers.isEqual(errorCode, "0")))))
        {
            Object feedback = Helpers.add(Helpers.add(this.id, " "), body);
            this.throwExactlyMatchedException(Helpers.GetValue(this.exceptions, "codes"), errorCode, feedback);
            this.throwExactlyMatchedException(Helpers.GetValue(this.exceptions, "exact"), message, feedback);
            throw new ExchangeError((String)feedback) ;
        }
        return null;
    }
}
