// Renders MIGRATION-REPORT.md — the list of what the codemod changed and,
// more importantly, what it could not change.

import { Patch } from './util.js';
import { VENUES, METHODS, ERRORS, SHAPES, snakeCase } from './rules.js';

export type FileResult = {
    path: string;
    language: 'typescript' | 'python';
    patch: Patch;
    /** original file contents */
    source: string;
    /** rewritten file contents */
    code: string;
    written: boolean;
};

export function renderReport (results: FileResult[], ccxtVersion: string): string {
    const touched = results.filter ((r) => r.patch.changed);
    const totalChanges = touched.reduce ((n, r) => n + r.patch.changes.length, 0);
    const totalTodos = touched.reduce ((n, r) => n + r.patch.todos.length, 0);

    const out: string[] = [];
    out.push ('# pmxt -> CCXT migration report');
    out.push ('');
    out.push ('Generated by `ccxt-migrate` against ccxt ' + ccxtVersion + '.');
    out.push ('');
    out.push ('| | |');
    out.push ('|---|---|');
    out.push ('| Files scanned | ' + results.length + ' |');
    out.push ('| Files rewritten | ' + touched.length + ' |');
    out.push ('| Mechanical changes applied | ' + totalChanges + ' |');
    out.push ('| `TODO(ccxt-migrate)` markers left for you | ' + totalTodos + ' |');
    out.push ('');

    // --- the part people skip and shouldn't -------------------------------
    const blockers = new Map<string, { note: string; sites: string[] }> ();
    for (const r of touched) {
        for (const u of r.patch.unsupported) {
            const entry = blockers.get (u.symbol) ?? { 'note': u.note, 'sites': [] };
            entry.sites.push (r.path + ':' + u.line);
            blockers.set (u.symbol, entry);
        }
    }
    out.push ('## Not migrated');
    out.push ('');
    if (blockers.size === 0) {
        out.push ('Nothing in this codebase falls outside what CCXT covers.');
    } else {
        out.push ('These are real coverage gaps, not codemod limitations. Each one needs a decision from you:');
        out.push ('keep pmxt for that call, drop the feature, or build it on top of CCXT yourself.');
        out.push ('');
        out.push ('| pmxt symbol | Why | Call sites |');
        out.push ('|---|---|---|');
        for (const [ symbol, entry ] of [ ...blockers.entries () ].sort ()) {
            const sites = entry.sites.slice (0, 6).join ('<br>') + ((entry.sites.length > 6) ? '<br>…and ' + (entry.sites.length - 6) + ' more' : '');
            out.push ('| `' + symbol + '` | ' + entry.note + ' | ' + sites + ' |');
        }
    }
    out.push ('');

    // --- per-file -----------------------------------------------------------
    out.push ('## Changes by file');
    out.push ('');
    if (touched.length === 0) {
        out.push ('No pmxt usage found.');
    }
    for (const r of touched) {
        out.push ('### `' + r.path + '`' + (r.written ? '' : '  _(dry run — not written)_'));
        out.push ('');
        if (r.patch.changes.length) {
            out.push ('| Line | Rule | Change |');
            out.push ('|---|---|---|');
            for (const c of r.patch.changes) {
                out.push ('| ' + c.line + ' | ' + c.rule + ' | ' + c.detail + ' |');
            }
            out.push ('');
        }
        if (r.patch.todos.length) {
            out.push ('Left for review:');
            out.push ('');
            for (const t of r.patch.todos) {
                out.push ('- L' + (t.line + 1) + ' — ' + t.message);
            }
            out.push ('');
        }
    }

    out.push ('## Return shapes the codemod cannot rewrite');
    out.push ('');
    out.push ('pmxt returns typed objects with attribute access; CCXT returns plain dicts/arrays.');
    out.push ('Rewriting field access blindly would silently corrupt working code, so it is left to you:');
    out.push ('');
    out.push ('| | pmxt | CCXT |');
    out.push ('|---|---|---|');
    for (const s of SHAPES) {
        out.push ('| ' + s.subject + ' | `' + s.pmxt + '` | `' + s.ccxt + '` |');
    }
    out.push ('');
    out.push ('## Next steps');
    out.push ('');
    out.push ('1. `grep -rn "TODO(ccxt-migrate)"` and work through them.');
    out.push ('2. Replace every pmxt `outcomeId` / `market_id` with a unified CCXT symbol — `console.log (Object.keys (await exchange.loadMarkets ()))` lists them.');
    out.push ('3. Re-run your tests, then smoke-test against a live public endpoint before touching credentials.');
    out.push ('');
    out.push ('Or hand the whole thing to an AI agent: `ccxt-migrate prompt` prints a ready-to-paste prompt.');
    out.push ('');
    return out.join ('\n');
}

/** `ccxt-migrate rules --markdown` — the same tables, for the docs. */
export function renderRules (): string {
    const out: string[] = [];
    out.push ('### Venues');
    out.push ('');
    out.push ('| pmxt class | CCXT exchange | Notes |');
    out.push ('|---|---|---|');
    for (const [ name, rule ] of Object.entries (VENUES)) {
        out.push ('| `' + name + '` | ' + (rule.ccxtId ? ('`' + rule.ccxtId + '`') : '— none —') + ' | ' + rule.note + ' |');
    }
    out.push ('');
    out.push ('### Methods');
    out.push ('');
    out.push ('| pmxt | CCXT | Notes |');
    out.push ('|---|---|---|');
    for (const [ name, rule ] of Object.entries (METHODS)) {
        const py = snakeCase (name);
        const left = '`' + name + '()`' + ((py !== name) ? ' / `' + py + '()`' : '');
        const right = rule.ccxt ? ('`' + rule.ccxt + '()`' + ((rule.kind === 'pro') ? ' _(ccxt.pro)_' : '')) : '— none —';
        out.push ('| ' + left + ' | ' + right + ' | ' + (rule.signature ? ('**' + rule.signature + '** — ') : '') + rule.note + ' |');
    }
    out.push ('');
    out.push ('### Errors');
    out.push ('');
    out.push ('| pmxt | CCXT |');
    out.push ('|---|---|');
    for (const [ name, target ] of Object.entries (ERRORS)) {
        out.push ('| `' + name + '` | `' + target + '` |');
    }
    out.push ('');
    out.push ('### Return shapes');
    out.push ('');
    out.push ('| | pmxt | CCXT |');
    out.push ('|---|---|---|');
    for (const s of SHAPES) {
        out.push ('| ' + s.subject + ' | `' + s.pmxt + '` | `' + s.ccxt + '` |');
    }
    out.push ('');
    return out.join ('\n');
}
