// ----------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
// EDIT THE CORRESPONDENT .ts FILE INSTEAD

import testWsOrderBook from "./test.orderBook.js";
import testWsCache from "./test.cache.js";
import testStream from "./test.Stream.js";
function testBaseWs() {
    testWsOrderBook();
    testWsCache();
    testStream();
    // todo : testWsClose ();
}
export default testBaseWs;
