package io.github.ccxt.exchanges.pro;
import io.github.ccxt.base.Precise;
import io.github.ccxt.errors.*;
import io.github.ccxt.Helpers;
import io.github.ccxt.ws.*;
import io.github.ccxt.Client;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

public class Coincatch extends io.github.ccxt.exchanges.Coincatch
{
   public Coincatch () {
       super();
   }

   public Coincatch (Object options) {
       super(options);
   }

    public Object describe()
    {
        return this.deepExtend(super.describe(), new java.util.HashMap<String, Object>() {{
            put( "has", new java.util.HashMap<String, Object>() {{
                put( "ws", true );
                put( "watchTrades", true );
                put( "watchTradesForSymbols", true );
                put( "watchOrderBook", true );
                put( "watchOrderBookForSymbols", true );
                put( "watchOHLCV", true );
                put( "watchOHLCVForSymbols", false );
                put( "watchOrders", true );
                put( "watchMyTrades", false );
                put( "watchTicker", true );
                put( "watchTickers", true );
                put( "watchBalance", true );
                put( "watchPositions", true );
            }} );
            put( "urls", new java.util.HashMap<String, Object>() {{
                put( "api", new java.util.HashMap<String, Object>() {{
                    put( "ws", new java.util.HashMap<String, Object>() {{
                        put( "public", "wss://ws.coincatch.com/public/v1/stream" );
                        put( "private", "wss://ws.coincatch.com/private/v1/stream" );
                    }} );
                }} );
            }} );
            put( "options", new java.util.HashMap<String, Object>() {{
                put( "tradesLimit", 1000 );
                put( "OHLCVLimit", 200 );
                put( "timeframesForWs", new java.util.HashMap<String, Object>() {{
                    put( "1m", "1m" );
                    put( "5m", "5m" );
                    put( "15m", "15m" );
                    put( "30m", "30m" );
                    put( "1h", "1H" );
                    put( "4h", "4H" );
                    put( "12h", "12H" );
                    put( "1d", "1D" );
                    put( "1w", "1W" );
                }} );
                put( "watchOrderBook", new java.util.HashMap<String, Object>() {{
                    put( "checksum", true );
                }} );
            }} );
            put( "streaming", new java.util.HashMap<String, Object>() {{
                put( "ping", "ping");
            }} );
            put( "exceptions", new java.util.HashMap<String, Object>() {{
                put( "ws", new java.util.HashMap<String, Object>() {{
                    put( "exact", new java.util.HashMap<String, Object>() {{
                        put( "30001", BadRequest.class );
                        put( "30002", AuthenticationError.class );
                        put( "30003", BadRequest.class );
                        put( "30004", AuthenticationError.class );
                        put( "30005", AuthenticationError.class );
                        put( "30006", RateLimitExceeded.class );
                        put( "30007", RateLimitExceeded.class );
                        put( "30011", AuthenticationError.class );
                        put( "30012", AuthenticationError.class );
                        put( "30013", AuthenticationError.class );
                        put( "30014", BadRequest.class );
                        put( "30015", AuthenticationError.class );
                    }} );
                    put( "broad", new java.util.HashMap<String, Object>() {{}} );
                }} );
            }} );
        }});
    }

    public Object getMarketFromArg(Object entry)
    {
        Object instId = this.safeString(entry, "instId");
        Object instType = this.safeString(entry, "instType");
        Object baseAndQuote = this.parseSpotMarketId(instId);
        Object baseId = Helpers.GetValue(baseAndQuote, "baseId");
        Object quoteId = Helpers.GetValue(baseAndQuote, "quoteId");
        Object suffix = "_SPBL"; // spot suffix
        if (Helpers.isTrue(Helpers.isEqual(instType, "mc")))
        {
            if (Helpers.isTrue(Helpers.isEqual(quoteId, "USD")))
            {
                suffix = "_DMCBL";
            } else
            {
                suffix = "_UMCBL";
            }
        }
        Object marketId = Helpers.add(Helpers.add(this.safeCurrencyCode(baseId), this.safeCurrencyCode(quoteId)), suffix);
        return this.safeMarketCustom(marketId);
    }

    public java.util.concurrent.CompletableFuture<Object> authenticate(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object parameters = Helpers.getArg(optionalArgs, 0, new java.util.HashMap<String, Object>() {{}});
            this.checkRequiredCredentials();
            Object url = Helpers.GetValue(Helpers.GetValue(Helpers.GetValue(this.urls, "api"), "ws"), "private");
            Client client = this.client(url);
            Object messageHash = "authenticated";
            io.github.ccxt.ws.Future future = client.reusableFuture((String)messageHash);
            Object authenticated = this.safeValue(client.subscriptions, messageHash);
            if (Helpers.isTrue(Helpers.isEqual(authenticated, null)))
            {
                Object timestamp = String.valueOf(this.seconds());
                Object auth = Helpers.add(Helpers.add(timestamp, "GET"), "/user/verify");
                Object signature = this.hmac(this.encode(auth), this.encode(this.secret), sha256(), "base64");
                Object operation = "login";
                Object request = new java.util.HashMap<String, Object>() {{
                    put( "op", operation );
                    put( "args", new java.util.ArrayList<Object>(java.util.Arrays.asList(new java.util.HashMap<String, Object>() {{
        put( "apiKey", "apiKey");
        put( "passphrase", "password");
        put( "timestamp", timestamp );
        put( "sign", signature );
    }})) );
                }};
                Object message = this.extend(request, parameters);
                this.watch(url, messageHash, message, messageHash, null);
            }
            return ((io.github.ccxt.ws.Future)future).getFuture().join();
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public java.util.concurrent.CompletableFuture<Object> watchPublic(Object messageHash, Object subscribeHash, Object args, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object parameters = Helpers.getArg(optionalArgs, 0, new java.util.HashMap<String, Object>() {{}});
            Object url = Helpers.GetValue(Helpers.GetValue(Helpers.GetValue(this.urls, "api"), "ws"), "public");
            Object request = new java.util.HashMap<String, Object>() {{
                put( "op", "subscribe" );
                put( "args", new java.util.ArrayList<Object>(java.util.Arrays.asList(args)) );
            }};
            Object message = this.extend(request, parameters);
            return (this.watch(url, messageHash, message, subscribeHash, null)).join();
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public java.util.concurrent.CompletableFuture<Object> unWatchPublic(Object messageHash, Object args, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object parameters = Helpers.getArg(optionalArgs, 0, new java.util.HashMap<String, Object>() {{}});
            Object url = Helpers.GetValue(Helpers.GetValue(Helpers.GetValue(this.urls, "api"), "ws"), "public");
            Object request = new java.util.HashMap<String, Object>() {{
                put( "op", "unsubscribe" );
                put( "args", new java.util.ArrayList<Object>(java.util.Arrays.asList(args)) );
            }};
            Object message = this.extend(request, parameters);
            return (this.watch(url, messageHash, message, messageHash, null)).join();
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public java.util.concurrent.CompletableFuture<Object> watchPrivate(Object messageHash, Object subscribeHash, Object args, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object parameters = Helpers.getArg(optionalArgs, 0, new java.util.HashMap<String, Object>() {{}});
            (this.authenticate()).join();
            Object url = Helpers.GetValue(Helpers.GetValue(Helpers.GetValue(this.urls, "api"), "ws"), "private");
            Object request = new java.util.HashMap<String, Object>() {{
                put( "op", "subscribe" );
                put( "args", new java.util.ArrayList<Object>(java.util.Arrays.asList(args)) );
            }};
            Object message = this.extend(request, parameters);
            return (this.watch(url, messageHash, message, subscribeHash, null)).join();
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public java.util.concurrent.CompletableFuture<Object> watchPrivateMultiple(Object messageHashes, Object subscribeHashes, Object args, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object parameters = Helpers.getArg(optionalArgs, 0, new java.util.HashMap<String, Object>() {{}});
            (this.authenticate()).join();
            Object url = Helpers.GetValue(Helpers.GetValue(Helpers.GetValue(this.urls, "api"), "ws"), "private");
            Object request = new java.util.HashMap<String, Object>() {{
                put( "op", "subscribe" );
                put( "args", args );
            }};
            Object message = this.extend(request, parameters);
            return (this.watchMultiple(url, messageHashes, message, subscribeHashes, null)).join();
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public void handleAuthenticate(Client client, Object message)
    {
        //
        //  { event: "login", code: 0 }
        //
        Object messageHash = "authenticated";
        Object future = this.safeValue(client.futures, messageHash);
        ((io.github.ccxt.ws.Future)future).resolve(true);
    }

    public java.util.concurrent.CompletableFuture<Object> watchPublicMultiple(Object messageHashes, Object subscribeHashes, Object argsArray, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object parameters = Helpers.getArg(optionalArgs, 0, new java.util.HashMap<String, Object>() {{}});
            Object url = Helpers.GetValue(Helpers.GetValue(Helpers.GetValue(this.urls, "api"), "ws"), "public");
            Object request = new java.util.HashMap<String, Object>() {{
                put( "op", "subscribe" );
                put( "args", argsArray );
            }};
            Object message = this.extend(request, parameters);
            return (this.watchMultiple(url, messageHashes, message, subscribeHashes, null)).join();
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public java.util.concurrent.CompletableFuture<Object> unWatchChannel(Object symbol, Object channel, Object messageHashTopic, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object parameters = Helpers.getArg(optionalArgs, 0, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object market = this.market(symbol);
            var instTypeinstIdVariable = this.getPublicInstTypeAndId(market);
            var instType = ((java.util.List<Object>) instTypeinstIdVariable).get(0);
            var instId = ((java.util.List<Object>) instTypeinstIdVariable).get(1);
            Object messageHash = Helpers.add(Helpers.add(Helpers.add("unsubscribe:", messageHashTopic), ":"), symbol);
            Object args = new java.util.HashMap<String, Object>() {{
                put( "instType", instType );
                put( "channel", channel );
                put( "instId", instId );
            }};
            return (this.unWatchPublic(messageHash, args, parameters)).join();
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public Object getPublicInstTypeAndId(Object market)
    {
        Object instId = Helpers.add(Helpers.GetValue(market, "baseId"), Helpers.GetValue(market, "quoteId"));
        Object instType = null;
        if (Helpers.isTrue(Helpers.GetValue(market, "spot")))
        {
            instType = "SP";
        } else if (Helpers.isTrue(Helpers.GetValue(market, "swap")))
        {
            instType = "MC";
        } else
        {
            throw new NotSupported((String)Helpers.add(this.id, " supports only spot and swap markets")) ;
        }
        return new java.util.ArrayList<Object>(java.util.Arrays.asList(instType, instId));
    }

    public Object handleDMCBLMarketByMessageHashes(Object market, Object hash, Client client, Object... optionalArgs)
    {
        Object timeframe = Helpers.getArg(optionalArgs, 0, null);
        Object marketId = Helpers.GetValue(market, "id");
        Object messageHashes = this.findMessageHashes(client, hash);
        // the exchange counts DMCBL markets as the same market with different quote currencies
        // for example symbols ETHUSD:ETH and ETH/USD:BTC both have the same marketId ETHUSD_DMCBL
        // we need to check all markets with the same marketId to find the correct market that is in messageHashes
        Object marketsWithCurrentId = this.safeList(this.markets_by_id, marketId, new java.util.ArrayList<Object>(java.util.Arrays.asList()));
        Object suffix = "";
        if (Helpers.isTrue(!Helpers.isEqual(timeframe, null)))
        {
            suffix = Helpers.add(":", timeframe);
        }
        for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(marketsWithCurrentId)); i++)
        {
            market = Helpers.GetValue(marketsWithCurrentId, i);
            Object symbol = Helpers.GetValue(market, "symbol");
            Object messageHash = Helpers.add(Helpers.add(hash, symbol), suffix);
            if (Helpers.isTrue(this.inArray(messageHash, messageHashes)))
            {
                return market;
            }
        }
        return market;
    }

    /**
     * @method
     * @name coincatch#watchTicker
     * @description watches a price ticker, a statistical calculation with the information calculated over the past 24 hours for a specific market
     * @see https://coincatch.github.io/github.io/en/spot/#tickers-channel
     * @param {string} symbol unified symbol of the market to fetch the ticker for
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @param {string} [params.instType] the type of the instrument to fetch the ticker for, 'SP' for spot markets, 'MC' for futures markets (default is 'SP')
     * @returns {object} a [ticker structure]{@link https://docs.ccxt.com/?id=ticker-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> watchTicker(Object symbol, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object parameters = Helpers.getArg(optionalArgs, 0, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object market = this.market(symbol);
            var instTypeinstIdVariable = this.getPublicInstTypeAndId(market);
            var instType = ((java.util.List<Object>) instTypeinstIdVariable).get(0);
            var instId = ((java.util.List<Object>) instTypeinstIdVariable).get(1);
            Object channel = "ticker";
            Object messageHash = Helpers.add(Helpers.add(channel, ":"), symbol);
            final Object finalChannel = channel;
            Object args = new java.util.HashMap<String, Object>() {{
                put( "instType", instType );
                put( "channel", finalChannel );
                put( "instId", instId );
            }};
            return (this.watchPublic(messageHash, messageHash, args, parameters)).join();
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name coincatch#unWatchTicker
     * @description unsubscribe from the ticker channel
     * @see https://coincatch.github.io/github.io/en/mix/#tickers-channel
     * @param {string} symbol unified symbol of the market to unwatch the ticker for
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {any} status of the unwatch request
     */
    public java.util.concurrent.CompletableFuture<Object> unWatchTicker(Object symbol, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object parameters = Helpers.getArg(optionalArgs, 0, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            return (this.unWatchChannel(symbol, "ticker", "ticker", parameters)).join();
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name coincatch#watchTickers
     * @description watches a price ticker, a statistical calculation with the information calculated over the past 24 hours for all markets of a specific list
     * @see https://coincatch.github.io/github.io/en/mix/#tickers-channel
     * @param {string[]} symbols unified symbol of the market to watch the tickers for
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a [ticker structure]{@link https://docs.ccxt.com/?id=ticker-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> watchTickers(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object symbols = Helpers.getArg(optionalArgs, 0, null);
            Object parameters = Helpers.getArg(optionalArgs, 1, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            if (Helpers.isTrue(Helpers.isEqual(symbols, null)))
            {
                symbols = this.symbols;
            }
            Object topics = new java.util.ArrayList<Object>(java.util.Arrays.asList());
            Object messageHashes = new java.util.ArrayList<Object>(java.util.Arrays.asList());
            for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(symbols)); i++)
            {
                Object symbol = Helpers.GetValue(symbols, i);
                Object market = this.market(symbol);
                var instTypeinstIdVariable = this.getPublicInstTypeAndId(market);
                var instType = ((java.util.List<Object>) instTypeinstIdVariable).get(0);
                var instId = ((java.util.List<Object>) instTypeinstIdVariable).get(1);
                Object args = new java.util.HashMap<String, Object>() {{
                    put( "instType", instType );
                    put( "channel", "ticker" );
                    put( "instId", instId );
                }};
                ((java.util.List<Object>)topics).add(args);
                ((java.util.List<Object>)messageHashes).add(Helpers.add("ticker:", symbol));
            }
            Object tickers = (this.watchPublicMultiple(messageHashes, messageHashes, topics, parameters)).join();
            if (Helpers.isTrue(this.newUpdates))
            {
                Object result = new java.util.HashMap<String, Object>() {{}};
                Helpers.addElementToObject(result, Helpers.GetValue(tickers, "symbol"), tickers);
                return result;
            }
            return this.filterByArray(this.tickers, "symbol", symbols);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public void handleTicker(Client client, Object message)
    {
        //
        //     action: 'snapshot',
        //     arg: { instType: 'sp', channel: 'ticker', instId: 'ETHUSDT' },
        //     data: [
        //         {
        //             instId: 'ETHUSDT',
        //             last: '2421.06',
        //             open24h: '2416.93',
        //             high24h: '2441.47',
        //             low24h: '2352.99',
        //             bestBid: '2421.03',
        //             bestAsk: '2421.06',
        //             baseVolume: '9445.2043',
        //             quoteVolume: '22807159.1148',
        //             ts: 1728131730687,
        //             labeId: 0,
        //             openUtc: '2414.50',
        //             chgUTC: '0.00272',
        //             bidSz: '3.866',
        //             askSz: '0.124'
        //         }
        //     ],
        //     ts: 1728131730688
        //
        Object arg = this.safeDict(message, "arg", new java.util.HashMap<String, Object>() {{}});
        Object market = this.getMarketFromArg(arg);
        Object marketId = Helpers.GetValue(market, "id");
        Object hash = "ticker:";
        if (Helpers.isTrue(Helpers.isGreaterThanOrEqual(Helpers.getIndexOf(marketId, "_DMCBL"), 0)))
        {
            market = this.handleDMCBLMarketByMessageHashes(market, hash, client);
        }
        Object data = this.safeList(message, "data", new java.util.ArrayList<Object>(java.util.Arrays.asList()));
        Object ticker = this.parseWsTicker(this.safeDict(data, 0, new java.util.HashMap<String, Object>() {{}}), market);
        Object symbol = Helpers.GetValue(market, "symbol");
        Helpers.addElementToObject(this.tickers, symbol, ticker);
        Object messageHash = Helpers.add(hash, symbol);
        client.resolve(Helpers.GetValue(this.tickers, symbol), messageHash);
    }

    public Object parseWsTicker(Object ticker, Object... optionalArgs)
    {
        //
        // spot
        //     {
        //         instId: 'ETHUSDT',
        //         last: '2421.06',
        //         open24h: '2416.93',
        //         high24h: '2441.47',
        //         low24h: '2352.99',
        //         bestBid: '2421.03',
        //         bestAsk: '2421.06',
        //         baseVolume: '9445.2043',
        //         quoteVolume: '22807159.1148',
        //         ts: 1728131730687,
        //         labeId: 0,
        //         openUtc: '2414.50',
        //         chgUTC: '0.00272',
        //         bidSz: '3.866',
        //         askSz: '0.124'
        //     }
        //
        // swap
        //     {
        //         instId: 'ETHUSDT',
        //         last: '2434.47',
        //         bestAsk: '2434.48',
        //         bestBid: '2434.47',
        //         high24h: '2471.68',
        //         low24h: '2400.01',
        //         priceChangePercent: '0.00674',
        //         capitalRate: '0.000082',
        //         nextSettleTime: 1728489600000,
        //         systemTime: 1728471993602,
        //         markPrice: '2434.46',
        //         indexPrice: '2435.44',
        //         holding: '171450.25',
        //         baseVolume: '1699298.91',
        //         quoteVolume: '4144522832.32',
        //         openUtc: '2439.67',
        //         chgUTC: '-0.00213',
        //         symbolType: 1,
        //         symbolId: 'ETHUSDT_UMCBL',
        //         deliveryPrice: '0',
        //         bidSz: '26.12',
        //         askSz: '49.6'
        //     }
        //
        Object market = Helpers.getArg(optionalArgs, 0, null);
        Object last = this.safeString(ticker, "last");
        Object timestamp = this.safeInteger2(ticker, "ts", "systemTime");
        return this.safeTicker(new java.util.HashMap<String, Object>() {{
            put( "symbol", Helpers.GetValue(market, "symbol") );
            put( "timestamp", timestamp );
            put( "datetime", Coincatch.this.iso8601(timestamp) );
            put( "high", Coincatch.this.safeString(ticker, "high24h") );
            put( "low", Coincatch.this.safeString(ticker, "low24h") );
            put( "bid", Coincatch.this.safeString(ticker, "bestBid") );
            put( "bidVolume", Coincatch.this.safeString(ticker, "bidSz") );
            put( "ask", Coincatch.this.safeString(ticker, "bestAsk") );
            put( "askVolume", Coincatch.this.safeString(ticker, "askSz") );
            put( "vwap", null );
            put( "open", Coincatch.this.safeString2(ticker, "open24h", "openUtc") );
            put( "close", last );
            put( "last", last );
            put( "previousClose", null );
            put( "change", null );
            put( "percentage", Precise.stringMul(Coincatch.this.safeString(ticker, "chgUTC"), "100") );
            put( "average", null );
            put( "baseVolume", Coincatch.this.safeNumber(ticker, "baseVolume") );
            put( "quoteVolume", Coincatch.this.safeNumber(ticker, "quoteVolume") );
            put( "indexPrice", Coincatch.this.safeString(ticker, "indexPrice") );
            put( "markPrice", Coincatch.this.safeString(ticker, "markPrice") );
            put( "info", ticker );
        }}, market);
    }

    /**
     * @method
     * @name coincatch#watchOHLCV
     * @description watches historical candlestick data containing the open, high, low, and close price, and the volume of a market
     * @see https://coincatch.github.io/github.io/en/spot/#candlesticks-channel
     * @param {string} symbol unified symbol of the market to fetch OHLCV data for
     * @param {string} timeframe the length of time each candle represents
     * @param {int} [since] timestamp in ms of the earliest candle to fetch (not including)
     * @param {int} [limit] the maximum amount of candles to fetch (not including)
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @param {bool} [params.instType] the type of the instrument to fetch the OHLCV data for, 'SP' for spot markets, 'MC' for futures markets (default is 'SP')
     * @returns {int[][]} A list of candles ordered as timestamp, open, high, low, close, volume
     */
    public java.util.concurrent.CompletableFuture<Object> watchOHLCV(Object symbol, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object timeframe = Helpers.getArg(optionalArgs, 0, "1m");
            Object since = Helpers.getArg(optionalArgs, 1, null);
            Object limit = Helpers.getArg(optionalArgs, 2, null);
            Object parameters = Helpers.getArg(optionalArgs, 3, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object market = this.market(symbol);
            Object timeframes = Helpers.GetValue(this.options, "timeframesForWs");
            Object channel = Helpers.add("candle", this.safeString(timeframes, timeframe));
            var instTypeinstIdVariable = this.getPublicInstTypeAndId(market);
            var instType = ((java.util.List<Object>) instTypeinstIdVariable).get(0);
            var instId = ((java.util.List<Object>) instTypeinstIdVariable).get(1);
            Object args = new java.util.HashMap<String, Object>() {{
                put( "instType", instType );
                put( "channel", channel );
                put( "instId", instId );
            }};
            Object messageHash = Helpers.add(Helpers.add(Helpers.add("ohlcv:", symbol), ":"), timeframe);
            Object ohlcv = (this.watchPublic(messageHash, messageHash, args, parameters)).join();
            if (Helpers.isTrue(this.newUpdates))
            {
                limit = Helpers.callDynamically(ohlcv, "getLimit", new Object[]{symbol, limit});
            }
            return this.filterBySinceLimit(ohlcv, since, limit, 0, true);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name coincatch#unWatchOHLCV
     * @description unsubscribe from the ohlcv channel
     * @see https://www.bitget.com/api-doc/spot/websocket/public/Candlesticks-Channel
     * @param {string} symbol unified symbol of the market to unwatch the ohlcv for
     * @param timeframe
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} A dictionary of [order book structures]{@link https://docs.ccxt.com/?id=order-book-structure} indexed by market symbols
     */
    public java.util.concurrent.CompletableFuture<Object> unWatchOHLCV(Object symbol, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object timeframe = Helpers.getArg(optionalArgs, 0, "1m");
            Object parameters = Helpers.getArg(optionalArgs, 1, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object timeframes = Helpers.GetValue(this.options, "timeframesForWs");
            Object interval = this.safeString(timeframes, timeframe);
            Object channel = Helpers.add("candle", interval);
            return (this.unWatchChannel(symbol, channel, Helpers.add("ohlcv:", interval), parameters)).join();
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public void handleOHLCV(Client client, Object message)
    {
        //
        //     {
        //         action: 'update',
        //         arg: { instType: 'sp', channel: 'candle1D', instId: 'ETHUSDT' },
        //         data: [
        //             [
        //                 '1728316800000',
        //                 '2474.5',
        //                 '2478.21',
        //                 '2459.8',
        //                 '2463.51',
        //                 '86.0551'
        //             ]
        //         ],
        //         ts: 1728317607657
        //     }
        //
        Object arg = this.safeDict(message, "arg", new java.util.HashMap<String, Object>() {{}});
        Object market = this.getMarketFromArg(arg);
        Object marketId = Helpers.GetValue(market, "id");
        Object hash = "ohlcv:";
        Object data = this.safeList(message, "data", new java.util.ArrayList<Object>(java.util.Arrays.asList()));
        Object channel = this.safeString(arg, "channel");
        Object klineType = Helpers.slice(channel, 6, null);
        Object timeframe = this.findTimeframe(klineType);
        if (Helpers.isTrue(Helpers.isGreaterThanOrEqual(Helpers.getIndexOf(marketId, "_DMCBL"), 0)))
        {
            market = this.handleDMCBLMarketByMessageHashes(market, hash, client, timeframe);
        }
        Object symbol = Helpers.GetValue(market, "symbol");
        if (!Helpers.isTrue((Helpers.inOp(this.ohlcvs, symbol))))
        {
            Helpers.addElementToObject(this.ohlcvs, symbol, new java.util.HashMap<String, Object>() {{}});
        }
        if (!Helpers.isTrue((Helpers.inOp(Helpers.GetValue(this.ohlcvs, symbol), timeframe))))
        {
            Object limit = this.safeInteger(this.options, "OHLCVLimit", 1000);
            Helpers.addElementToObject(Helpers.GetValue(this.ohlcvs, symbol), timeframe, new ArrayCache.ArrayCacheByTimestamp(((Number)limit).intValue()));
        }
        Object stored = Helpers.GetValue(Helpers.GetValue(this.ohlcvs, symbol), timeframe);
        for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(data)); i++)
        {
            Object candle = this.safeList(data, i, new java.util.ArrayList<Object>(java.util.Arrays.asList()));
            Object parsed = this.parseWsOHLCV(candle, market);
            Helpers.callDynamically(stored, "append", new Object[]{parsed});
        }
        Object messageHash = Helpers.add(Helpers.add(Helpers.add(hash, symbol), ":"), timeframe);
        client.resolve(stored, messageHash);
    }

    public Object parseWsOHLCV(Object ohlcv, Object... optionalArgs)
    {
        //
        //     [
        //         '1728316800000',
        //         '2474.5',
        //         '2478.21',
        //         '2459.8',
        //         '2463.51',
        //         '86.0551'
        //     ]
        //
        Object market = Helpers.getArg(optionalArgs, 0, null);
        return new java.util.ArrayList<Object>(java.util.Arrays.asList(this.safeInteger(ohlcv, 0), this.safeNumber(ohlcv, 1), this.safeNumber(ohlcv, 2), this.safeNumber(ohlcv, 3), this.safeNumber(ohlcv, 4), this.safeNumber(ohlcv, 5)));
    }

    /**
     * @method
     * @name coincatch#watchOrderBook
     * @description watches information on open orders with bid (buy) and ask (sell) prices, volumes and other data
     * @see https://coincatch.github.io/github.io/en/spot/#depth-channel
     * @param {string} symbol unified symbol of the market to fetch the order book for
     * @param {int} [limit] the maximum amount of order book entries to return
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} A dictionary of [order book structures]{@link https://docs.ccxt.com/?id=order-book-structure} indexed by market symbols
     */
    public java.util.concurrent.CompletableFuture<Object> watchOrderBook(Object symbol, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object limit = Helpers.getArg(optionalArgs, 0, null);
            Object parameters = Helpers.getArg(optionalArgs, 1, new java.util.HashMap<String, Object>() {{}});
            return (this.watchOrderBookForSymbols(new java.util.ArrayList<Object>(java.util.Arrays.asList(symbol)), limit, parameters)).join();
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name coincatch#unWatchOrderBook
     * @description unsubscribe from the orderbook channel
     * @see https://coincatch.github.io/github.io/en/spot/#depth-channel
     * @param {string} symbol unified symbol of the market to fetch the order book for
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @param {int} [params.limit] orderbook limit, default is undefined
     * @returns {object} A dictionary of [order book structures]{@link https://docs.ccxt.com/?id=order-book-structure} indexed by market symbols
     */
    public java.util.concurrent.CompletableFuture<Object> unWatchOrderBook(Object symbol, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object parameters = Helpers.getArg(optionalArgs, 0, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object channel = "books";
            Object limit = this.safeInteger(parameters, "limit");
            if (Helpers.isTrue(Helpers.isTrue((Helpers.isEqual(limit, 5))) || Helpers.isTrue((Helpers.isEqual(limit, 15)))))
            {
                parameters = this.omit(parameters, "limit");
                channel = Helpers.add(channel, String.valueOf(limit));
            }
            return (this.unWatchChannel(symbol, channel, channel, parameters)).join();
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name coincatch#watchOrderBookForSymbols
     * @description watches information on open orders with bid (buy) and ask (sell) prices, volumes and other data
     * @see https://coincatch.github.io/github.io/en/spot/#depth-channel
     * @param symbols
     * @param {int} [limit] the maximum amount of order book entries to return
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} A dictionary of [order book structures]{@link https://docs.ccxt.com/?id=order-book-structure} indexed by market symbols
     */
    public java.util.concurrent.CompletableFuture<Object> watchOrderBookForSymbols(Object symbols2, Object... optionalArgs)
    {
        final Object symbols3 = symbols2;
        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {
            Object symbols = symbols3;
            Object limit = Helpers.getArg(optionalArgs, 0, null);
            Object parameters = Helpers.getArg(optionalArgs, 1, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            symbols = this.marketSymbols(symbols);
            Object channel = "books";
            Object topics = new java.util.ArrayList<Object>(java.util.Arrays.asList());
            Object messageHashes = new java.util.ArrayList<Object>(java.util.Arrays.asList());
            for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(symbols)); i++)
            {
                Object symbol = Helpers.GetValue(symbols, i);
                Object market = this.market(symbol);
                var instTypeinstIdVariable = this.getPublicInstTypeAndId(market);
                var instType = ((java.util.List<Object>) instTypeinstIdVariable).get(0);
                var instId = ((java.util.List<Object>) instTypeinstIdVariable).get(1);
                Object args = new java.util.HashMap<String, Object>() {{
                    put( "instType", instType );
                    put( "channel", channel );
                    put( "instId", instId );
                }};
                ((java.util.List<Object>)topics).add(args);
                ((java.util.List<Object>)messageHashes).add(Helpers.add(Helpers.add(channel, ":"), symbol));
            }
            Object orderbook = (this.watchPublicMultiple(messageHashes, messageHashes, topics, parameters)).join();
            return Helpers.callDynamically(orderbook, "limit", new Object[]{});
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public void handleOrderBook(Client client, Object message)
    {
        //
        //     {
        //         action: 'update',
        //         arg: { instType: 'sp', channel: 'books', instId: 'ETHUSDT' },
        //         data: [
        //             {
        //                 asks: [ [ 2507.07, 0.4248 ] ],
        //                 bids: [ [ 2507.05, 0.1198 ] ],
        //                 checksum: -1400923312,
        //                 ts: '1728339446908'
        //             }
        //         ],
        //         ts: 1728339446908
        //     }
        //
        Object arg = this.safeDict(message, "arg", new java.util.HashMap<String, Object>() {{}});
        Object market = this.getMarketFromArg(arg);
        Object marketId = Helpers.GetValue(market, "id");
        Object hash = "books:";
        if (Helpers.isTrue(Helpers.isGreaterThanOrEqual(Helpers.getIndexOf(marketId, "_DMCBL"), 0)))
        {
            market = this.handleDMCBLMarketByMessageHashes(market, hash, client);
        }
        Object symbol = Helpers.GetValue(market, "symbol");
        Object channel = this.safeString(arg, "channel");
        Object messageHash = Helpers.add(hash, symbol);
        Object data = this.safeList(message, "data", new java.util.ArrayList<Object>(java.util.Arrays.asList()));
        Object rawOrderBook = this.safeDict(data, 0);
        Object timestamp = this.safeInteger(rawOrderBook, "ts");
        Object incrementalBook = channel;
        if (Helpers.isTrue(incrementalBook))
        {
            if (!Helpers.isTrue((Helpers.inOp(this.orderbooks, symbol))))
            {
                Object ob = this.countedOrderBook(new java.util.HashMap<String, Object>() {{}});
                Helpers.addElementToObject(ob, "symbol", symbol);
                Helpers.addElementToObject(this.orderbooks, symbol, ob);
            }
            Object storedOrderBook = Helpers.GetValue(this.orderbooks, symbol);
            Object asks = this.safeList(rawOrderBook, "asks", new java.util.ArrayList<Object>(java.util.Arrays.asList()));
            Object bids = this.safeList(rawOrderBook, "bids", new java.util.ArrayList<Object>(java.util.Arrays.asList()));
            this.handleDeltas(Helpers.GetValue(storedOrderBook, "asks"), asks);
            this.handleDeltas(Helpers.GetValue(storedOrderBook, "bids"), bids);
            Helpers.addElementToObject(storedOrderBook, "timestamp", timestamp);
            Helpers.addElementToObject(storedOrderBook, "datetime", this.iso8601(timestamp));
            Object checksum = this.safeBool(this.options, "checksum", true);
            Object isSnapshot = Helpers.isEqual(this.safeString(message, "action"), "snapshot");
            if (Helpers.isTrue(!Helpers.isTrue(isSnapshot) && Helpers.isTrue(checksum)))
            {
                Object storedAsks = Helpers.GetValue(storedOrderBook, "asks");
                Object storedBids = Helpers.GetValue(storedOrderBook, "bids");
                Object asksLength = Helpers.getArrayLength(storedAsks);
                Object bidsLength = Helpers.getArrayLength(storedBids);
                Object payloadArray = new java.util.ArrayList<Object>(java.util.Arrays.asList());
                for (var i = 0; Helpers.isLessThan(i, 25); i++)
                {
                    if (Helpers.isTrue(Helpers.isLessThan(i, bidsLength)))
                    {
                        ((java.util.List<Object>)payloadArray).add(Helpers.GetValue(Helpers.GetValue(Helpers.GetValue(storedBids, i), 2), 0));
                        ((java.util.List<Object>)payloadArray).add(Helpers.GetValue(Helpers.GetValue(Helpers.GetValue(storedBids, i), 2), 1));
                    }
                    if (Helpers.isTrue(Helpers.isLessThan(i, asksLength)))
                    {
                        ((java.util.List<Object>)payloadArray).add(Helpers.GetValue(Helpers.GetValue(Helpers.GetValue(storedAsks, i), 2), 0));
                        ((java.util.List<Object>)payloadArray).add(Helpers.GetValue(Helpers.GetValue(Helpers.GetValue(storedAsks, i), 2), 1));
                    }
                }
                Object payload = String.join((String)":", (java.util.List<String>)payloadArray);
                Object calculatedChecksum = this.crc32(payload, true);
                Object responseChecksum = this.safeInteger(rawOrderBook, "checksum");
                if (Helpers.isTrue(!Helpers.isEqual(calculatedChecksum, responseChecksum)))
                {
                    this.spawn(() -> { try { this.handleCheckSumError(client, symbol, messageHash); } catch(Exception _e) { throw new RuntimeException(_e); } });
                    return;
                }
            }
        } else
        {
            Object orderbook = this.orderBook(new java.util.HashMap<String, Object>() {{}});
            Object parsedOrderbook = this.parseOrderBook(rawOrderBook, symbol, timestamp);
            Helpers.callDynamically(orderbook, "reset", new Object[]{parsedOrderbook});
            Helpers.addElementToObject(this.orderbooks, symbol, orderbook);
        }
        client.resolve(Helpers.GetValue(this.orderbooks, symbol), messageHash);
    }

    public java.util.concurrent.CompletableFuture<Object> handleCheckSumError(Client client, Object symbol, Object messageHash)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            (this.unWatchOrderBook(symbol)).join();
            var error = new ChecksumError(Helpers.add(Helpers.add(this.id, " "), this.orderbookChecksumMessage(symbol)));
            client.reject(error, messageHash);
            return null;
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public void handleDelta(Object bookside, Object delta)
    {
        Object bidAsk = this.parseBidAsk(delta, 0, 1);
        ((java.util.List<Object>)bidAsk).add(delta);
        Helpers.callDynamically(bookside, "storeArray", new Object[]{bidAsk});
    }

    public void handleDeltas(Object bookside, Object deltas)
    {
        for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(deltas)); i++)
        {
            this.handleDelta(bookside, Helpers.GetValue(deltas, i));
        }
    }

    /**
     * @method
     * @name coincatch#watchTrades
     * @description get the list of most recent trades for a particular symbol
     * @see https://coincatch.github.io/github.io/en/spot/#trades-channel
     * @param {string} symbol unified symbol of the market to fetch trades for
     * @param {int} [since] timestamp in ms of the earliest trade to fetch
     * @param {int} [limit] the maximum amount of trades to fetch
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object[]} a list of [trade structures]{@link https://docs.ccxt.com/?id=public-trades}
     */
    public java.util.concurrent.CompletableFuture<Object> watchTrades(Object symbol, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object since = Helpers.getArg(optionalArgs, 0, null);
            Object limit = Helpers.getArg(optionalArgs, 1, null);
            Object parameters = Helpers.getArg(optionalArgs, 2, new java.util.HashMap<String, Object>() {{}});
            return (this.watchTradesForSymbols(new java.util.ArrayList<Object>(java.util.Arrays.asList(symbol)), since, limit, parameters)).join();
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name coincatch#watchTradesForSymbols
     * @description watches information on multiple trades made in a market
     * @see https://coincatch.github.io/github.io/en/spot/#trades-channel
     * @param symbols
     * @param {int} [since] the earliest time in ms to fetch orders for
     * @param {int} [limit] the maximum number of trade structures to retrieve
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object[]} a list of [trade structures]{@link https://docs.ccxt.com/?id=trade-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> watchTradesForSymbols(Object symbols2, Object... optionalArgs)
    {
        final Object symbols3 = symbols2;
        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {
            Object symbols = symbols3;
            Object since = Helpers.getArg(optionalArgs, 0, null);
            Object limit = Helpers.getArg(optionalArgs, 1, null);
            Object parameters = Helpers.getArg(optionalArgs, 2, new java.util.HashMap<String, Object>() {{}});
            Object symbolsLength = Helpers.getArrayLength(symbols);
            if (Helpers.isTrue(Helpers.isEqual(symbolsLength, 0)))
            {
                throw new ArgumentsRequired((String)Helpers.add(this.id, " watchTradesForSymbols() requires a non-empty array of symbols")) ;
            }
            (this.loadMarkets()).join();
            symbols = this.marketSymbols(symbols);
            Object topics = new java.util.ArrayList<Object>(java.util.Arrays.asList());
            Object messageHashes = new java.util.ArrayList<Object>(java.util.Arrays.asList());
            for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(symbols)); i++)
            {
                Object symbol = Helpers.GetValue(symbols, i);
                Object market = this.market(symbol);
                var instTypeinstIdVariable = this.getPublicInstTypeAndId(market);
                var instType = ((java.util.List<Object>) instTypeinstIdVariable).get(0);
                var instId = ((java.util.List<Object>) instTypeinstIdVariable).get(1);
                Object args = new java.util.HashMap<String, Object>() {{
                    put( "instType", instType );
                    put( "channel", "trade" );
                    put( "instId", instId );
                }};
                ((java.util.List<Object>)topics).add(args);
                ((java.util.List<Object>)messageHashes).add(Helpers.add("trade:", symbol));
            }
            Object trades = (this.watchPublicMultiple(messageHashes, messageHashes, topics, parameters)).join();
            if (Helpers.isTrue(this.newUpdates))
            {
                Object first = this.safeDict(trades, 0);
                Object tradeSymbol = this.safeString(first, "symbol");
                limit = Helpers.callDynamically(trades, "getLimit", new Object[]{tradeSymbol, limit});
            }
            return this.filterBySinceLimit(trades, since, limit, "timestamp", true);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name coincatch#unWatchTrades
     * @description unsubscribe from the trades channel
     * @see https://coincatch.github.io/github.io/en/spot/#trades-channel
     * @param {string} symbol unified symbol of the market to unwatch the trades for
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {any} status of the unwatch request
     */
    public java.util.concurrent.CompletableFuture<Object> unWatchTrades(Object symbol, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object parameters = Helpers.getArg(optionalArgs, 0, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            return (this.unWatchChannel(symbol, "trade", "trade", parameters)).join();
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public void handleTrades(Client client, Object message)
    {
        //
        //     {
        //         action: 'update',
        //         arg: { instType: 'sp', channel: 'trade', instId: 'ETHUSDT' },
        //         data: [ [ '1728341807469', '2421.41', '0.478', 'sell' ] ],
        //         ts: 1728341807482
        //     }
        //
        Object arg = this.safeDict(message, "arg", new java.util.HashMap<String, Object>() {{}});
        Object market = this.getMarketFromArg(arg);
        Object marketId = Helpers.GetValue(market, "id");
        Object hash = "trade:";
        if (Helpers.isTrue(Helpers.isGreaterThanOrEqual(Helpers.getIndexOf(marketId, "_DMCBL"), 0)))
        {
            market = this.handleDMCBLMarketByMessageHashes(market, hash, client);
        }
        Object symbol = Helpers.GetValue(market, "symbol");
        if (!Helpers.isTrue((Helpers.inOp(this.trades, symbol))))
        {
            Object limit = this.safeInteger(this.options, "tradesLimit", 1000);
            Helpers.addElementToObject(this.trades, symbol, new ArrayCache(((Number)limit).intValue()));
        }
        Object stored = Helpers.GetValue(this.trades, symbol);
        Object data = this.safeList(message, "data", new java.util.ArrayList<Object>(java.util.Arrays.asList()));
        if (Helpers.isTrue(!Helpers.isEqual(data, null)))
        {
            data = this.sortBy(data, 0);
            for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(data)); i++)
            {
                Object trade = this.safeList(data, i);
                Object parsed = this.parseWsTrade(trade, market);
                Helpers.callDynamically(stored, "append", new Object[]{parsed});
            }
        }
        Object messageHash = Helpers.add(hash, symbol);
        client.resolve(stored, messageHash);
    }

    public Object parseWsTrade(Object trade, Object... optionalArgs)
    {
        //
        //     [
        //         '1728341807469',
        //         '2421.41',
        //         '0.478',
        //         'sell'
        //     ]
        //
        Object market = Helpers.getArg(optionalArgs, 0, null);
        Object timestamp = this.safeInteger(trade, 0);
        return this.safeTrade(new java.util.HashMap<String, Object>() {{
            put( "id", null );
            put( "timestamp", timestamp );
            put( "datetime", Coincatch.this.iso8601(timestamp) );
            put( "symbol", Helpers.GetValue(market, "symbol") );
            put( "side", Coincatch.this.safeStringLower(trade, 3) );
            put( "price", Coincatch.this.safeString(trade, 1) );
            put( "amount", Coincatch.this.safeString(trade, 2) );
            put( "cost", null );
            put( "takerOrMaker", null );
            put( "type", null );
            put( "order", null );
            put( "fee", null );
            put( "info", trade );
        }}, market);
    }

    /**
     * @method
     * @name coincatch#watchBalance
     * @description watch balance and get the amount of funds available for trading or funds locked in orders
     * @see https://coincatch.github.io/github.io/en/spot/#account-channel
     * @see https://coincatch.github.io/github.io/en/mix/#account-channel
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @param {str} [params.type] 'spot' or 'swap' (default is 'spot')
     * @param {string} [params.instType] *swap only* 'umcbl' or 'dmcbl' (default is 'umcbl')
     * @returns {object} a [balance structure]{@link https://docs.ccxt.com/?id=balance-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> watchBalance(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object parameters = Helpers.getArg(optionalArgs, 0, new java.util.HashMap<String, Object>() {{}});
            Object type = null;
            var typeparametersVariable = this.handleMarketTypeAndParams("watchBalance", null, parameters);
            type = ((java.util.List<Object>) typeparametersVariable).get(0);
            parameters = ((java.util.List<Object>) typeparametersVariable).get(1);
            Object instType = "spbl"; // must be lower case for spot
            if (Helpers.isTrue(Helpers.isEqual(type, "swap")))
            {
                instType = "umcbl";
            }
            Object channel = "account";
            var instTypeparametersVariable = this.handleOptionAndParams(parameters, "watchBalance", "instType", instType);
            instType = ((java.util.List<Object>) instTypeparametersVariable).get(0);
            parameters = ((java.util.List<Object>) instTypeparametersVariable).get(1);
            final Object finalInstType = instType;
            Object args = new java.util.HashMap<String, Object>() {{
                put( "instType", finalInstType );
                put( "channel", channel );
                put( "instId", "default" );
            }};
            Object messageHash = Helpers.add("balance:", ((String)instType).toLowerCase());
            return (this.watchPrivate(messageHash, messageHash, args, parameters)).join();
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public void handleBalance(Client client, Object message)
    {
        //
        //  spot
        //     {
        //         action: 'snapshot',
        //         arg: { instType: 'spbl', channel: 'account', instId: 'default' },
        //         data: [
        //             {
        //                 coinId: '3',
        //                 coinName: 'ETH',
        //                 available: '0.0000832',
        //                 frozen: '0',
        //                 lock: '0'
        //             }
        //         ],
        //         ts: 1728464548725
        //     }
        //
        // //  swap
        //     {
        //         action: 'snapshot',
        //         arg: { instType: 'dmcbl', channel: 'account', instId: 'default' },
        //         data: [
        //             {
        //                 marginCoin: 'ETH',
        //                 locked: '0.00000000',
        //                 available: '0.00001203',
        //                 maxOpenPosAvailable: '0.00001203',
        //                 maxTransferOut: '0.00001203',
        //                 equity: '0.00001203',
        //                 usdtEquity: '0.029092328738',
        //                 coinDisplayName: 'ETH'
        //             }
        //         ],
        //         ts: 1728650777643
        //     }
        //
        Object data = this.safeList(message, "data", new java.util.ArrayList<Object>(java.util.Arrays.asList()));
        for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(data)); i++)
        {
            Object rawBalance = Helpers.GetValue(data, i);
            Object currencyId = this.safeString2(rawBalance, "coinName", "marginCoin");
            Object code = this.safeCurrencyCode(currencyId);
            Object account = ((Helpers.isTrue((Helpers.inOp(this.balance, code))))) ? Helpers.GetValue(this.balance, code) : this.account();
            Object freeQuery = ((Helpers.isTrue((Helpers.inOp(rawBalance, "maxTransferOut"))))) ? "maxTransferOut" : "available";
            Helpers.addElementToObject(account, "free", this.safeString(rawBalance, freeQuery));
            Helpers.addElementToObject(account, "total", this.safeString(rawBalance, "equity"));
            Helpers.addElementToObject(account, "used", this.safeString(rawBalance, "frozen"));
            Helpers.addElementToObject(this.balance, code, account);
        }
        this.balance = this.safeBalance(this.balance);
        Object arg = this.safeDict(message, "arg");
        Object instType = this.safeStringLower(arg, "instType");
        Object messageHash = Helpers.add("balance:", instType);
        client.resolve(this.balance, messageHash);
    }

    /**
     * @method
     * @name coincatch#watchOrders
     * @description watches information on multiple orders made by the user
     * @see https://coincatch.github.io/github.io/en/spot/#order-channel
     * @see https://coincatch.github.io/github.io/en/mix/#order-channel
     * @see https://coincatch.github.io/github.io/en/mix/#plan-order-channel
     * @param {string} symbol unified market symbol of the market orders were made in
     * @param {int} [since] the earliest time in ms to fetch orders for
     * @param {int} [limit] the maximum number of order structures to retrieve
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @param {string} [params.type] 'spot' or 'swap'
     * @param {string} [params.instType] *swap only* 'umcbl' or 'dmcbl' (default is 'umcbl')
     * @param {bool} [params.trigger] *swap only* whether to watch trigger orders (default is false)
     * @returns {object[]} a list of [order structures]{@link https://docs.ccxt.com/?id=order-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> watchOrders(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object symbol = Helpers.getArg(optionalArgs, 0, null);
            Object since = Helpers.getArg(optionalArgs, 1, null);
            Object limit = Helpers.getArg(optionalArgs, 2, null);
            Object parameters = Helpers.getArg(optionalArgs, 3, new java.util.HashMap<String, Object>() {{}});
            Object methodName = "watchOrders";
            (this.loadMarkets()).join();
            Object market = null;
            Object marketId = null;
            if (Helpers.isTrue(!Helpers.isEqual(symbol, null)))
            {
                market = this.market(symbol);
                symbol = Helpers.GetValue(market, "symbol");
                marketId = Helpers.GetValue(market, "id");
            }
            Object marketType = null;
            var marketTypeparametersVariable = this.handleMarketTypeAndParams(methodName, market, parameters);
            marketType = ((java.util.List<Object>) marketTypeparametersVariable).get(0);
            parameters = ((java.util.List<Object>) marketTypeparametersVariable).get(1);
            Object instType = "spbl";
            Object instId = marketId;
            if (Helpers.isTrue(Helpers.isEqual(marketType, "spot")))
            {
                if (Helpers.isTrue(Helpers.isEqual(symbol, null)))
                {
                    throw new ArgumentsRequired((String)Helpers.add(Helpers.add(Helpers.add(Helpers.add(Helpers.add(this.id, " "), methodName), "() requires a symbol argument for "), marketType), " markets.")) ;
                }
            } else
            {
                instId = "default";
                instType = "umcbl";
                if (Helpers.isTrue(Helpers.isEqual(symbol, null)))
                {
                    var instTypeparametersVariable = this.handleOptionAndParams(parameters, methodName, "instType", instType);
                    instType = ((java.util.List<Object>) instTypeparametersVariable).get(0);
                    parameters = ((java.util.List<Object>) instTypeparametersVariable).get(1);
                } else
                {
                    if (Helpers.isTrue(Helpers.isGreaterThanOrEqual(Helpers.getIndexOf(marketId, "_DMCBL"), 0)))
                    {
                        instType = "dmcbl";
                    }
                }
            }
            Object channel = "orders";
            Object isTrigger = this.safeBool(parameters, "trigger");
            if (Helpers.isTrue(isTrigger))
            {
                channel = "ordersAlgo"; // channel does not return any data
                parameters = this.omit(parameters, "trigger");
            }
            final Object finalInstType = instType;
            final Object finalChannel = channel;
            final Object finalInstId = instId;
            Object args = new java.util.HashMap<String, Object>() {{
                put( "instType", finalInstType );
                put( "channel", finalChannel );
                put( "instId", finalInstId );
            }};
            Object messageHash = "orders";
            if (Helpers.isTrue(!Helpers.isEqual(symbol, null)))
            {
                messageHash = Helpers.add(messageHash, Helpers.add(":", symbol));
            }
            Object orders = (this.watchPrivate(messageHash, messageHash, args, parameters)).join();
            if (Helpers.isTrue(this.newUpdates))
            {
                limit = Helpers.callDynamically(orders, "getLimit", new Object[]{symbol, limit});
            }
            return this.filterBySymbolSinceLimit(orders, symbol, since, limit, true);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public void handleOrder(Client client, Object message)
    {
        //
        // spot
        //
        //     {
        //         action: 'snapshot',
        //         arg: { instType: 'spbl', channel: 'orders', instId: 'ETHUSDT_SPBL' },
        //         data: [
        //             {
        //                 instId: 'ETHUSDT_SPBL',
        //                 ordId: '1228627925964996608',
        //                 clOrdId: 'f0cccf74-c535-4523-a53d-dbe3b9958559',
        //                 px: '2000',
        //                 sz: '0.001',
        //                 notional: '2',
        //                 ordType: 'limit',
        //                 force: 'normal',
        //                 side: 'buy',
        //                 accFillSz: '0',
        //                 avgPx: '0',
        //                 status: 'new',
        //                 cTime: 1728653645030,
        //                 uTime: 1728653645030,
        //                 orderFee: [],
        //                 eps: 'API'
        //             }
        //         ],
        //         ts: 1728653645046
        //     }
        //
        // swap
        //
        //     {
        //         action: 'snapshot',
        //         arg: { instType: 'umcbl', channel: 'orders', instId: 'default' },
        //         data: [
        //             {
        //                 accFillSz: '0',
        //                 cTime: 1728653796976,
        //                 clOrdId: '1228628563272753152',
        //                 eps: 'API',
        //                 force: 'normal',
        //                 hM: 'single_hold',
        //                 instId: 'ETHUSDT_UMCBL',
        //                 lever: '5',
        //                 low: false,
        //                 notionalUsd: '20',
        //                 ordId: '1228628563188867072',
        //                 ordType: 'limit',
        //                 orderFee: [],
        //                 posSide: 'net',
        //                 px: '2000',
        //                 side: 'buy',
        //                 status: 'new',
        //                 sz: '0.01',
        //                 tS: 'buy_single',
        //                 tdMode: 'cross',
        //                 tgtCcy: 'USDT',
        //                 uTime: 1728653796976
        //             }
        //         ],
        //         ts: 1728653797002
        //     }
        //
        //
        Object arg = this.safeDict(message, "arg", new java.util.HashMap<String, Object>() {{}});
        Object instType = this.safeString(arg, "instType");
        Object argInstId = this.safeString(arg, "instId");
        Object marketType = null;
        if (Helpers.isTrue(Helpers.isEqual(instType, "spbl")))
        {
            marketType = "spot";
        } else
        {
            marketType = "swap";
        }
        Object data = this.safeList(message, "data", new java.util.ArrayList<Object>(java.util.Arrays.asList()));
        if (Helpers.isTrue(Helpers.isEqual(this.orders, null)))
        {
            Object limit = this.safeInteger(this.options, "ordersLimit", 1000);
            this.orders = new ArrayCache.ArrayCacheBySymbolById(((Number)limit).intValue());
        }
        Object hash = "orders";
        Object stored = this.orders;
        Object symbol = null;
        for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(data)); i++)
        {
            Object order = Helpers.GetValue(data, i);
            Object marketId = this.safeString(order, "instId", argInstId);
            Object market = this.safeMarket(marketId, null, null, marketType);
            Object parsed = this.parseWsOrder(order, market);
            Helpers.callDynamically(stored, "append", new Object[]{parsed});
            symbol = Helpers.GetValue(parsed, "symbol");
            Object messageHash = Helpers.add("orders:", symbol);
            client.resolve(stored, messageHash);
        }
        client.resolve(stored, hash);
    }

    public Object parseWsOrder(Object order, Object... optionalArgs)
    {
        //
        // spot
        //     {
        //         instId: 'ETHUSDT_SPBL',
        //         ordId: '1228627925964996608',
        //         clOrdId: 'f0cccf74-c535-4523-a53d-dbe3b9958559',
        //         px: '2000',
        //         sz: '0.001',
        //         notional: '2',
        //         ordType: 'limit',
        //         force: 'normal',
        //         side: 'buy',
        //         accFillSz: '0',
        //         avgPx: '0',
        //         status: 'new',
        //         cTime: 1728653645030,
        //         uTime: 1728653645030,
        //         orderFee: orderFee: [ { fee: '0', feeCcy: 'USDT' } ],
        //         eps: 'API'
        //     }
        //
        // swap
        //     {
        //         accFillSz: '0',
        //         cTime: 1728653796976,
        //         clOrdId: '1228628563272753152',
        //         eps: 'API',
        //         force: 'normal',
        //         hM: 'single_hold',
        //         instId: 'ETHUSDT_UMCBL',
        //         lever: '5',
        //         low: false,
        //         notionalUsd: '20',
        //         ordId: '1228628563188867072',
        //         ordType: 'limit',
        //         orderFee: [ { fee: '0', feeCcy: 'USDT' } ],
        //         posSide: 'net',
        //         px: '2000',
        //         side: 'buy',
        //         status: 'new',
        //         sz: '0.01',
        //         tS: 'buy_single',
        //         tdMode: 'cross',
        //         tgtCcy: 'USDT',
        //         uTime: 1728653796976
        //     }
        //
        Object market = Helpers.getArg(optionalArgs, 0, null);
        Object marketId = this.safeString(order, "instId");
        Object settleId = this.safeString(order, "tgtCcy");
        market = this.safeMarketCustom(marketId, market, settleId);
        Object timestamp = this.safeInteger(order, "cTime");
        Object symbol = Helpers.GetValue(market, "symbol");
        Object rawStatus = this.safeString(order, "status");
        Object orderFee = this.safeList(order, "orderFee", new java.util.ArrayList<Object>(java.util.Arrays.asList()));
        Object fee = this.safeDict(orderFee, 0);
        Object feeCost = Precise.stringMul(this.safeString(fee, "fee"), "-1");
        Object feeCurrency = this.safeString(fee, "feeCcy");
        Object price = this.omitZero(this.safeString(order, "px"));
        Object priceAvg = this.omitZero(this.safeString(order, "avgPx"));
        if (Helpers.isTrue(Helpers.isEqual(price, null)))
        {
            price = priceAvg;
        }
        Object type = this.safeStringLower(order, "ordType");
        final Object finalPrice = price;
        return this.safeOrder(new java.util.HashMap<String, Object>() {{
            put( "id", Coincatch.this.safeString(order, "ordId") );
            put( "clientOrderId", Coincatch.this.safeString(order, "clOrdId") );
            put( "timestamp", timestamp );
            put( "datetime", Coincatch.this.iso8601(timestamp) );
            put( "lastTradeTimestamp", null );
            put( "lastUpdateTimestamp", Coincatch.this.safeInteger(order, "uTime") );
            put( "status", Coincatch.this.parseOrderStatus(rawStatus) );
            put( "symbol", symbol );
            put( "type", type );
            put( "timeInForce", Coincatch.this.parseOrderTimeInForce(Coincatch.this.safeStringLower(order, "force")) );
            put( "side", Coincatch.this.safeStringLower(order, "side") );
            put( "price", finalPrice );
            put( "average", Coincatch.this.safeString(order, "avgPx") );
            put( "amount", Coincatch.this.safeString(order, "sz") );
            put( "filled", Coincatch.this.safeString(order, "accFillSz") );
            put( "remaining", null );
            put( "triggerPrice", null );
            put( "takeProfitPrice", null );
            put( "stopLossPrice", null );
            put( "cost", Coincatch.this.safeString(order, "notional") );
            put( "trades", null );
            put( "fee", new java.util.HashMap<String, Object>() {{
                put( "currency", feeCurrency );
                put( "cost", feeCost );
            }} );
            put( "reduceOnly", Coincatch.this.safeBool(order, "low") );
            put( "postOnly", null );
            put( "info", order );
        }}, market);
    }

    /**
     * @method
     * @name coincatch#watchPositions
     * @description watch all open positions
     * @see https://coincatch.github.io/github.io/en/mix/#positions-channel
     * @param {string[]|undefined} symbols list of unified market symbols
     * @param since
     * @param limit
     * @param {object} params extra parameters specific to the exchange API endpoint
     * @returns {object[]} a list of [position structure]{@link https://docs.ccxt.com/en/latest/manual.html#position-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> watchPositions(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object symbols = Helpers.getArg(optionalArgs, 0, null);
            Object since = Helpers.getArg(optionalArgs, 1, null);
            Object limit = Helpers.getArg(optionalArgs, 2, null);
            Object parameters = Helpers.getArg(optionalArgs, 3, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            symbols = this.marketSymbols(symbols, "swap");
            Object messageHashes = new java.util.ArrayList<Object>(java.util.Arrays.asList());
            Object hash = "positions";
            Object instTypes = new java.util.ArrayList<Object>(java.util.Arrays.asList());
            if (Helpers.isTrue(!Helpers.isEqual(symbols, null)))
            {
                for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(symbols)); i++)
                {
                    Object symbol = Helpers.GetValue(symbols, i);
                    Object market = this.market(symbol);
                    Object instType = this.getPrivateInstType(market);
                    if (!Helpers.isTrue(this.inArray(instType, instTypes)))
                    {
                        ((java.util.List<Object>)instTypes).add(instType);
                    }
                    ((java.util.List<Object>)messageHashes).add(Helpers.add(Helpers.add(hash, "::"), symbol));
                }
            } else
            {
                instTypes = new java.util.ArrayList<Object>(java.util.Arrays.asList("umcbl", "dmcbl"));
                ((java.util.List<Object>)messageHashes).add(hash);
            }
            Object args = new java.util.ArrayList<Object>(java.util.Arrays.asList());
            Object subscribeHashes = new java.util.ArrayList<Object>(java.util.Arrays.asList());
            for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(instTypes)); i++)
            {
                Object instType = Helpers.GetValue(instTypes, i);
                final Object finalHash = hash;
                Object arg = new java.util.HashMap<String, Object>() {{
                    put( "instType", instType );
                    put( "channel", finalHash );
                    put( "instId", "default" );
                }};
                ((java.util.List<Object>)subscribeHashes).add(Helpers.add(Helpers.add(hash, "::"), instType));
                ((java.util.List<Object>)args).add(arg);
            }
            Object newPositions = (this.watchPrivateMultiple(messageHashes, subscribeHashes, args, parameters)).join();
            if (Helpers.isTrue(this.newUpdates))
            {
                return newPositions;
            }
            return this.filterBySymbolsSinceLimit(newPositions, symbols, since, limit, true);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public Object getPrivateInstType(Object market)
    {
        Object marketId = Helpers.GetValue(market, "id");
        if (Helpers.isTrue(Helpers.isGreaterThanOrEqual(Helpers.getIndexOf(marketId, "_DMCBL"), 0)))
        {
            return "dmcbl";
        }
        return "umcbl";
    }

    public void handlePositions(Client client, Object message)
    {
        //
        //     {
        //         action: 'snapshot',
        //         arg: { instType: 'umcbl', channel: 'positions', instId: 'default' },
        //         data: [
        //             {
        //                 posId: '1221355728745619456',
        //                 instId: 'ETHUSDT_UMCBL',
        //                 instName: 'ETHUSDT',
        //                 marginCoin: 'USDT',
        //                 margin: '5.27182',
        //                 marginMode: 'crossed',
        //                 holdSide: 'long',
        //                 holdMode: 'single_hold',
        //                 total: '0.01',
        //                 available: '0.01',
        //                 locked: '0',
        //                 averageOpenPrice: '2635.91',
        //                 leverage: 5,
        //                 achievedProfits: '0',
        //                 upl: '-0.0267',
        //                 uplRate: '-0.005064664576',
        //                 liqPx: '-3110.66866033',
        //                 keepMarginRate: '0.0033',
        //                 marginRate: '0.002460827254',
        //                 cTime: '1726919818102',
        //                 uTime: '1728919604312',
        //                 markPrice: '2633.24',
        //                 autoMargin: 'off'
        //             }
        //         ],
        //         ts: 1728919604329
        //     }
        //
        if (Helpers.isTrue(Helpers.isEqual(this.positions, null)))
        {
            this.positions = new ArrayCache.ArrayCacheBySymbolBySide();
        }
        Object cache = this.positions;
        Object rawPositions = this.safeValue(message, "data", new java.util.ArrayList<Object>(java.util.Arrays.asList()));
        Object dataLength = Helpers.getArrayLength(rawPositions);
        if (Helpers.isTrue(Helpers.isEqual(dataLength, 0)))
        {
            return;
        }
        Object newPositions = new java.util.ArrayList<Object>(java.util.Arrays.asList());
        Object symbols = new java.util.ArrayList<Object>(java.util.Arrays.asList());
        for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(rawPositions)); i++)
        {
            Object rawPosition = Helpers.GetValue(rawPositions, i);
            Object position = this.parseWsPosition(rawPosition);
            ((java.util.List<Object>)symbols).add(Helpers.GetValue(position, "symbol"));
            ((java.util.List<Object>)newPositions).add(position);
            Helpers.callDynamically(cache, "append", new Object[]{position});
        }
        Object hash = "positions";
        Object messageHashes = this.findMessageHashes(client, hash);
        for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(messageHashes)); i++)
        {
            Object messageHash = Helpers.GetValue(messageHashes, i);
            Object parts = Helpers.split(messageHash, "::");
            Object symbol = Helpers.GetValue(parts, 1);
            if (Helpers.isTrue(this.inArray(symbol, symbols)))
            {
                Object positionsForSymbol = new java.util.ArrayList<Object>(java.util.Arrays.asList());
                for (var j = 0; Helpers.isLessThan(j, Helpers.getArrayLength(newPositions)); j++)
                {
                    Object position = Helpers.GetValue(newPositions, j);
                    if (Helpers.isTrue(Helpers.isEqual(Helpers.GetValue(position, "symbol"), symbol)))
                    {
                        ((java.util.List<Object>)positionsForSymbol).add(position);
                    }
                }
                client.resolve(positionsForSymbol, messageHash);
            }
        }
        client.resolve(newPositions, hash);
    }

    public Object parseWsPosition(Object position, Object... optionalArgs)
    {
        //
        //     {
        //         posId: '1221355728745619456',
        //         instId: 'ETHUSDT_UMCBL',
        //         instName: 'ETHUSDT',
        //         marginCoin: 'USDT',
        //         margin: '5.27182',
        //         marginMode: 'crossed',
        //         holdSide: 'long',
        //         holdMode: 'single_hold',
        //         total: '0.01',
        //         available: '0.01',
        //         locked: '0',
        //         averageOpenPrice: '2635.91',
        //         leverage: 5,
        //         achievedProfits: '0',
        //         upl: '-0.0267',
        //         uplRate: '-0.005064664576',
        //         liqPx: '-3110.66866033',
        //         keepMarginRate: '0.0033',
        //         marginRate: '0.002460827254',
        //         cTime: '1726919818102',
        //         uTime: '1728919604312',
        //         markPrice: '2633.24',
        //         autoMargin: 'off'
        //     }
        //
        Object market = Helpers.getArg(optionalArgs, 0, null);
        Object marketId = this.safeString(position, "symbol");
        Object settleId = this.safeString(position, "marginCoin");
        market = this.safeMarketCustom(marketId, market, settleId);
        Object timestamp = this.safeInteger(position, "cTime");
        Object marginModeId = this.safeString(position, "marginMode");
        Object marginMode = this.getSupportedMapping(marginModeId, new java.util.HashMap<String, Object>() {{
            put( "crossed", "cross" );
            put( "isolated", "isolated" );
        }});
        Object isHedged = null;
        Object holdMode = this.safeString(position, "holdMode");
        if (Helpers.isTrue(Helpers.isEqual(holdMode, "double_hold")))
        {
            isHedged = true;
        } else if (Helpers.isTrue(Helpers.isEqual(holdMode, "single_hold")))
        {
            isHedged = false;
        }
        Object percentageDecimal = this.safeString(position, "uplRate");
        Object percentage = Precise.stringMul(percentageDecimal, "100");
        Object margin = this.safeNumber(position, "margin");
        final Object finalMarket = market;
        final Object finalIsHedged = isHedged;
        return this.safePosition(new java.util.HashMap<String, Object>() {{
            put( "symbol", Helpers.GetValue(finalMarket, "symbol") );
            put( "id", null );
            put( "timestamp", timestamp );
            put( "datetime", Coincatch.this.iso8601(timestamp) );
            put( "contracts", Coincatch.this.safeNumber(position, "total") );
            put( "contractSize", null );
            put( "side", Coincatch.this.safeStringLower(position, "holdSide") );
            put( "notional", margin );
            put( "leverage", Coincatch.this.safeInteger(position, "leverage") );
            put( "unrealizedPnl", Coincatch.this.safeNumber(position, "upl") );
            put( "realizedPnl", Coincatch.this.safeNumber(position, "achievedProfits") );
            put( "collateral", null );
            put( "entryPrice", Coincatch.this.safeNumber(position, "averageOpenPrice") );
            put( "markPrice", Coincatch.this.safeNumber(position, "markPrice") );
            put( "liquidationPrice", Coincatch.this.safeNumber(position, "liqPx") );
            put( "marginMode", marginMode );
            put( "hedged", finalIsHedged );
            put( "maintenanceMargin", null );
            put( "maintenanceMarginPercentage", Coincatch.this.safeNumber(position, "keepMarginRate") );
            put( "initialMargin", margin );
            put( "initialMarginPercentage", null );
            put( "marginRatio", Coincatch.this.safeNumber(position, "marginRate") );
            put( "lastUpdateTimestamp", Coincatch.this.safeInteger(position, "uTime") );
            put( "lastPrice", null );
            put( "stopLossPrice", null );
            put( "takeProfitPrice", null );
            put( "percentage", percentage );
            put( "info", position );
        }});
    }

    public Object handleErrorMessage(Client client, Object message)
    {
        //
        //    { event: "error", code: 30001, msg: "Channel does not exist" }
        //
        Object eventVar = this.safeString(message, "event");
        try
        {
            if (Helpers.isTrue(Helpers.isEqual(eventVar, "error")))
            {
                Object code = this.safeString(message, "code");
                Object feedback = Helpers.add(Helpers.add(this.id, " "), this.json(message));
                this.throwExactlyMatchedException(Helpers.GetValue(Helpers.GetValue(this.exceptions, "ws"), "exact"), code, feedback);
                Object msg = this.safeString(message, "msg", "");
                this.throwBroadlyMatchedException(Helpers.GetValue(Helpers.GetValue(this.exceptions, "ws"), "broad"), msg, feedback);
                throw new ExchangeError((String)feedback) ;
            }
            return false;
        } catch(Exception e)
        {
            if (Helpers.isTrue(Helpers.isInstance(e, AuthenticationError.class)))
            {
                Object messageHash = "authenticated";
                client.reject(e, messageHash);
                if (Helpers.isTrue(Helpers.inOp(client.subscriptions, messageHash)))
                {
                    ((java.util.Map<String,Object>)client.subscriptions).remove((String)messageHash);
                }
            } else
            {
                client.reject(e);
            }
            return true;
        }
    }

    public void handleMessage(Client client, Object message)
    {
        // todo handle with subscribe and unsubscribe
        if (Helpers.isTrue(this.handleErrorMessage(client, message)))
        {
            return;
        }
        Object content = this.safeString(message, "message");
        if (Helpers.isTrue(Helpers.isEqual(content, "pong")))
        {
            this.handlePong(client, message);
            return;
        }
        if (Helpers.isTrue(Helpers.isEqual(message, "pong")))
        {
            this.handlePong(client, message);
            return;
        }
        Object eventVar = this.safeString(message, "event");
        if (Helpers.isTrue(Helpers.isEqual(eventVar, "login")))
        {
            this.handleAuthenticate(client, message);
            return;
        }
        if (Helpers.isTrue(Helpers.isEqual(eventVar, "subscribe")))
        {
            this.handleSubscriptionStatus(client, message);
            return;
        }
        if (Helpers.isTrue(Helpers.isEqual(eventVar, "unsubscribe")))
        {
            this.handleUnSubscriptionStatus(client, message);
            return;
        }
        Object data = this.safeDict(message, "arg", new java.util.HashMap<String, Object>() {{}});
        Object channel = this.safeString(data, "channel");
        if (Helpers.isTrue(Helpers.isEqual(channel, "ticker")))
        {
            this.handleTicker(client, message);
        }
        if (Helpers.isTrue(Helpers.isGreaterThanOrEqual(Helpers.getIndexOf(channel, "candle"), 0)))
        {
            this.handleOHLCV(client, message);
        }
        if (Helpers.isTrue(Helpers.isGreaterThanOrEqual(Helpers.getIndexOf(channel, "books"), 0)))
        {
            this.handleOrderBook(client, message);
        }
        if (Helpers.isTrue(Helpers.isEqual(channel, "trade")))
        {
            this.handleTrades(client, message);
        }
        if (Helpers.isTrue(Helpers.isEqual(channel, "account")))
        {
            this.handleBalance(client, message);
        }
        if (Helpers.isTrue(Helpers.isTrue((Helpers.isEqual(channel, "orders"))) || Helpers.isTrue((Helpers.isEqual(channel, "ordersAlgo")))))
        {
            this.handleOrder(client, message);
        }
        if (Helpers.isTrue(Helpers.isEqual(channel, "positions")))
        {
            this.handlePositions(client, message);
        }
    }

    public Object ping(Client client)
    {
        return "ping";
    }

    public Object handlePong(Client client, Object message)
    {
        client.lastPong = ((Number)this.milliseconds()).longValue();
        return message;
    }

    public Object handleSubscriptionStatus(Client client, Object message)
    {
        return message;
    }

    public Object handleUnSubscriptionStatus(Client client, Object message)
    {
        Object argsList = this.safeList(message, "args");
        if (Helpers.isTrue(Helpers.isEqual(argsList, null)))
        {
            argsList = new java.util.ArrayList<Object>(java.util.Arrays.asList(this.safeDict(message, "arg", new java.util.HashMap<String, Object>() {{}})));
        }
        for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(argsList)); i++)
        {
            Object arg = Helpers.GetValue(argsList, i);
            Object channel = this.safeString(arg, "channel");
            if (Helpers.isTrue(Helpers.isEqual(channel, "books")))
            {
                this.handleOrderBookUnSubscription(client, message);
            } else if (Helpers.isTrue(Helpers.isEqual(channel, "trade")))
            {
                this.handleTradesUnSubscription(client, message);
            } else if (Helpers.isTrue(Helpers.isEqual(channel, "ticker")))
            {
                this.handleTickerUnSubscription(client, message);
            } else if (Helpers.isTrue(((String)channel).startsWith(((String)"candle"))))
            {
                this.handleOHLCVUnSubscription(client, message);
            }
        }
        return message;
    }

    public void handleOrderBookUnSubscription(Client client, Object message)
    {
        Object arg = this.safeDict(message, "arg", new java.util.HashMap<String, Object>() {{}});
        Object instType = this.safeStringLower(arg, "instType");
        Object type = ((Helpers.isTrue((Helpers.isEqual(instType, "sp"))))) ? "spot" : "swap";
        Object instId = this.safeString(arg, "instId");
        Object market = this.safeMarket(instId, null, null, type);
        Object symbol = Helpers.GetValue(market, "symbol");
        Object messageHash = Helpers.add("unsubscribe:orderbook:", Helpers.GetValue(market, "symbol"));
        Object subMessageHash = Helpers.add("orderbook:", symbol);
        if (Helpers.isTrue(Helpers.inOp(this.orderbooks, symbol)))
        {
            ((java.util.Map<String,Object>)this.orderbooks).remove((String)symbol);
        }
        if (Helpers.isTrue(Helpers.inOp(client.subscriptions, subMessageHash)))
        {
            ((java.util.Map<String,Object>)client.subscriptions).remove((String)subMessageHash);
        }
        if (Helpers.isTrue(Helpers.inOp(client.subscriptions, messageHash)))
        {
            ((java.util.Map<String,Object>)client.subscriptions).remove((String)messageHash);
        }
        var error = new UnsubscribeError(Helpers.add(Helpers.add(this.id, " orderbook "), symbol));
        client.reject(error, subMessageHash);
        client.resolve(true, messageHash);
    }

    public void handleTradesUnSubscription(Client client, Object message)
    {
        Object arg = this.safeDict(message, "arg", new java.util.HashMap<String, Object>() {{}});
        Object instType = this.safeStringLower(arg, "instType");
        Object type = ((Helpers.isTrue((Helpers.isEqual(instType, "sp"))))) ? "spot" : "swap";
        Object instId = this.safeString(arg, "instId");
        Object market = this.safeMarket(instId, null, null, type);
        Object symbol = Helpers.GetValue(market, "symbol");
        Object messageHash = Helpers.add("unsubscribe:trade:", Helpers.GetValue(market, "symbol"));
        Object subMessageHash = Helpers.add("trade:", symbol);
        if (Helpers.isTrue(Helpers.inOp(this.trades, symbol)))
        {
            ((java.util.Map<String,Object>)this.trades).remove((String)symbol);
        }
        if (Helpers.isTrue(Helpers.inOp(client.subscriptions, subMessageHash)))
        {
            ((java.util.Map<String,Object>)client.subscriptions).remove((String)subMessageHash);
        }
        if (Helpers.isTrue(Helpers.inOp(client.subscriptions, messageHash)))
        {
            ((java.util.Map<String,Object>)client.subscriptions).remove((String)messageHash);
        }
        var error = new UnsubscribeError(Helpers.add(Helpers.add(this.id, " trades "), symbol));
        client.reject(error, subMessageHash);
        client.resolve(true, messageHash);
    }

    public void handleTickerUnSubscription(Client client, Object message)
    {
        Object arg = this.safeDict(message, "arg", new java.util.HashMap<String, Object>() {{}});
        Object instType = this.safeStringLower(arg, "instType");
        Object type = ((Helpers.isTrue((Helpers.isEqual(instType, "sp"))))) ? "spot" : "swap";
        Object instId = this.safeString(arg, "instId");
        Object market = this.safeMarket(instId, null, null, type);
        Object symbol = Helpers.GetValue(market, "symbol");
        Object messageHash = Helpers.add("unsubscribe:ticker:", Helpers.GetValue(market, "symbol"));
        Object subMessageHash = Helpers.add("ticker:", symbol);
        if (Helpers.isTrue(Helpers.inOp(this.tickers, symbol)))
        {
            ((java.util.Map<String,Object>)this.tickers).remove((String)symbol);
        }
        if (Helpers.isTrue(Helpers.inOp(client.subscriptions, subMessageHash)))
        {
            ((java.util.Map<String,Object>)client.subscriptions).remove((String)subMessageHash);
        }
        if (Helpers.isTrue(Helpers.inOp(client.subscriptions, messageHash)))
        {
            ((java.util.Map<String,Object>)client.subscriptions).remove((String)messageHash);
        }
        var error = new UnsubscribeError(Helpers.add(Helpers.add(this.id, " ticker "), symbol));
        client.reject(error, subMessageHash);
        client.resolve(true, messageHash);
    }

    public void handleOHLCVUnSubscription(Client client, Object message)
    {
        Object arg = this.safeDict(message, "arg", new java.util.HashMap<String, Object>() {{}});
        Object instType = this.safeStringLower(arg, "instType");
        Object type = ((Helpers.isTrue((Helpers.isEqual(instType, "sp"))))) ? "spot" : "swap";
        Object instId = this.safeString(arg, "instId");
        Object channel = this.safeString(arg, "channel");
        Object interval = Helpers.replace((String)channel, (String)"candle", (String)"");
        Object timeframes = this.safeDict(this.options, "timeframesForWs");
        Object timeframe = this.findTimeframe(interval, timeframes);
        Object market = this.safeMarket(instId, null, null, type);
        Object symbol = Helpers.GetValue(market, "symbol");
        Object messageHash = Helpers.add(Helpers.add(Helpers.add("unsubscribe:ohlcv:", timeframe), ":"), Helpers.GetValue(market, "symbol"));
        Object subMessageHash = Helpers.add(Helpers.add(Helpers.add("ohlcv:", symbol), ":"), timeframe);
        if (Helpers.isTrue(Helpers.inOp(this.ohlcvs, symbol)))
        {
            if (Helpers.isTrue(Helpers.inOp(Helpers.GetValue(this.ohlcvs, symbol), timeframe)))
            {
                ((java.util.Map<String,Object>)Helpers.GetValue(this.ohlcvs, symbol)).remove((String)timeframe);
            }
        }
        this.cleanUnsubscription(client, subMessageHash, messageHash);
    }
}
