package io.github.ccxt.exchanges.pro;
import io.github.ccxt.base.Precise;
import io.github.ccxt.errors.*;
import io.github.ccxt.Helpers;
import io.github.ccxt.ws.*;
import io.github.ccxt.Client;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

public class Hyperliquid extends io.github.ccxt.exchanges.Hyperliquid
{
   public Hyperliquid () {
       super();
   }

   public Hyperliquid (Object options) {
       super(options);
   }

    public Object describe()
    {
        return this.deepExtend(super.describe(), new java.util.HashMap<String, Object>() {{
            put( "has", new java.util.HashMap<String, Object>() {{
                put( "ws", true );
                put( "cancelOrderWs", true );
                put( "cancelOrdersWs", true );
                put( "createOrderWs", true );
                put( "createOrdersWs", true );
                put( "editOrderWs", true );
                put( "watchBalance", false );
                put( "watchMyTrades", true );
                put( "watchOHLCV", true );
                put( "watchOrderBook", true );
                put( "watchOrders", true );
                put( "watchTicker", true );
                put( "watchTickers", true );
                put( "watchTrades", true );
                put( "watchTradesForSymbols", false );
                put( "watchPosition", false );
                put( "unWatchOrderBook", true );
                put( "unWatchTickers", true );
                put( "unWatchTrades", true );
                put( "unWatchOHLCV", true );
                put( "unWatchMyTrades", true );
                put( "unWatchOrders", true );
            }} );
            put( "urls", new java.util.HashMap<String, Object>() {{
                put( "api", new java.util.HashMap<String, Object>() {{
                    put( "ws", new java.util.HashMap<String, Object>() {{
                        put( "public", "wss://api.hyperliquid.xyz/ws" );
                    }} );
                }} );
                put( "test", new java.util.HashMap<String, Object>() {{
                    put( "ws", new java.util.HashMap<String, Object>() {{
                        put( "public", "wss://api.hyperliquid-testnet.xyz/ws" );
                    }} );
                }} );
            }} );
            put( "options", new java.util.HashMap<String, Object>() {{}} );
            put( "streaming", new java.util.HashMap<String, Object>() {{
                put( "ping", "ping");
                put( "keepAlive", 20000 );
            }} );
            put( "exceptions", new java.util.HashMap<String, Object>() {{
                put( "ws", new java.util.HashMap<String, Object>() {{
                    put( "exact", new java.util.HashMap<String, Object>() {{}} );
                }} );
            }} );
        }});
    }

    /**
     * @method
     * @name hyperliquid#createOrdersWs
     * @description create a list of trade orders using WebSocket post request
     * @see https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/exchange-endpoint#place-an-order
     * @param {Array} orders list of orders to create, each object should contain the parameters required by createOrder, namely symbol, type, side, amount, price and params
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} an [order structure]{@link https://docs.ccxt.com/?id=order-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> createOrdersWs(Object orders, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object parameters = Helpers.getArg(optionalArgs, 0, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object url = Helpers.GetValue(Helpers.GetValue(Helpers.GetValue(this.urls, "api"), "ws"), "public");
            Object ordersRequest = this.createOrdersRequest(orders, parameters);
            Object wrapped = this.wrapAsPostAction(ordersRequest);
            Object request = this.safeDict(wrapped, "request", new java.util.HashMap<String, Object>() {{}});
            Object requestId = this.safeString(wrapped, "requestId");
            Object response = (this.watch(url, requestId, request, requestId, null)).join();
            Object responseOjb = this.safeDict(response, "response", new java.util.HashMap<String, Object>() {{}});
            Object data = this.safeDict(responseOjb, "data", new java.util.HashMap<String, Object>() {{}});
            Object statuses = this.safeList(data, "statuses", new java.util.ArrayList<Object>(java.util.Arrays.asList()));
            return this.parseOrders(statuses, null);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name hyperliquid#createOrderWs
     * @description create a trade order using WebSocket post request
     * @see https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/exchange-endpoint#place-an-order
     * @param {string} symbol unified symbol of the market to create an order in
     * @param {string} type 'market' or 'limit'
     * @param {string} side 'buy' or 'sell'
     * @param {float} amount how much of currency you want to trade in units of base currency
     * @param {float} [price] the price at which the order is to be fulfilled, in units of the quote currency, ignored in market orders
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @param {string} [params.timeInForce] 'Gtc', 'Ioc', 'Alo'
     * @param {bool} [params.postOnly] true or false whether the order is post-only
     * @param {bool} [params.reduceOnly] true or false whether the order is reduce-only
     * @param {float} [params.triggerPrice] The price at which a trigger order is triggered at
     * @param {string} [params.clientOrderId] client order id, (optional 128 bit hex string e.g. 0x1234567890abcdef1234567890abcdef)
     * @param {string} [params.slippage] the slippage for market order
     * @param {string} [params.vaultAddress] the vault address for order
     * @returns {object} an [order structure]{@link https://docs.ccxt.com/?id=order-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> createOrderWs(Object symbol, Object type, Object side, Object amount, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object price = Helpers.getArg(optionalArgs, 0, null);
            Object parameters = Helpers.getArg(optionalArgs, 1, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            var orderglobalParamsVariable = this.parseCreateEditOrderArgs(null, symbol, type, side, amount, price, parameters);
            var order = ((java.util.List<Object>) orderglobalParamsVariable).get(0);
            var globalParams = ((java.util.List<Object>) orderglobalParamsVariable).get(1);
            Object orders = (this.createOrdersWs(new java.util.ArrayList<Object>(java.util.Arrays.asList(((Object)order))), globalParams)).join();
            Object ordersLength = Helpers.getArrayLength(orders);
            if (Helpers.isTrue(Helpers.isEqual(ordersLength, 0)))
            {
                // not sure why but it is happening sometimes
                return this.safeOrder(new java.util.HashMap<String, Object>() {{}});
            }
            Object parsedOrder = Helpers.GetValue(orders, 0);
            return parsedOrder;
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name hyperliquid#editOrderWs
     * @description edit a trade order
     * @see https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/exchange-endpoint#modify-multiple-orders
     * @param {string} id cancel order id
     * @param {string} symbol unified symbol of the market to create an order in
     * @param {string} type 'market' or 'limit'
     * @param {string} side 'buy' or 'sell'
     * @param {float} amount how much of currency you want to trade in units of base currency
     * @param {float} [price] the price at which the order is to be fulfilled, in units of the quote currency, ignored in market orders
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @param {string} [params.timeInForce] 'Gtc', 'Ioc', 'Alo'
     * @param {bool} [params.postOnly] true or false whether the order is post-only
     * @param {bool} [params.reduceOnly] true or false whether the order is reduce-only
     * @param {float} [params.triggerPrice] The price at which a trigger order is triggered at
     * @param {string} [params.clientOrderId] client order id, (optional 128 bit hex string e.g. 0x1234567890abcdef1234567890abcdef)
     * @param {string} [params.vaultAddress] the vault address for order
     * @returns {object} an [order structure]{@link https://docs.ccxt.com/?id=order-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> editOrderWs(Object id, Object symbol, Object type, Object side, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object amount = Helpers.getArg(optionalArgs, 0, null);
            Object price = Helpers.getArg(optionalArgs, 1, null);
            Object parameters = Helpers.getArg(optionalArgs, 2, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object market = this.market(symbol);
            Object url = Helpers.GetValue(Helpers.GetValue(Helpers.GetValue(this.urls, "api"), "ws"), "public");
            var orderglobalParamsVariable = this.parseCreateEditOrderArgs(id, symbol, type, side, amount, price, parameters);
            var order = ((java.util.List<Object>) orderglobalParamsVariable).get(0);
            var globalParams = ((java.util.List<Object>) orderglobalParamsVariable).get(1);
            Object postRequest = this.editOrdersRequest(new java.util.ArrayList<Object>(java.util.Arrays.asList(((Object)order))), globalParams);
            Object wrapped = this.wrapAsPostAction(postRequest);
            Object request = this.safeDict(wrapped, "request", new java.util.HashMap<String, Object>() {{}});
            Object requestId = this.safeString(wrapped, "requestId");
            Object response = (this.watch(url, requestId, request, requestId, null)).join();
            // response is the same as in this.editOrder
            Object responseObject = this.safeDict(response, "response", new java.util.HashMap<String, Object>() {{}});
            Object dataObject = this.safeDict(responseObject, "data", new java.util.HashMap<String, Object>() {{}});
            Object statuses = this.safeList(dataObject, "statuses", new java.util.ArrayList<Object>(java.util.Arrays.asList()));
            Object first = this.safeDict(statuses, 0, new java.util.HashMap<String, Object>() {{}});
            Object parsedOrder = this.parseOrder(first, market);
            return parsedOrder;
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name hyperliquid#cancelOrdersWs
     * @description cancel multiple orders using WebSocket post request
     * @see https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/websocket/post-requests
     * @param {string[]} ids list of order ids to cancel
     * @param {string} symbol unified symbol of the market the orders were made in
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @param {string[]} [params.clientOrderId] list of client order ids to cancel instead of order ids
     * @param {string} [params.vaultAddress] the vault address for order cancellation
     * @returns {object[]} a list of [order structures]{@link https://docs.ccxt.com/?id=order-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> cancelOrdersWs(Object ids, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object symbol = Helpers.getArg(optionalArgs, 0, null);
            Object parameters = Helpers.getArg(optionalArgs, 1, new java.util.HashMap<String, Object>() {{}});
            this.checkRequiredCredentials();
            (this.loadMarkets()).join();
            Object request = this.cancelOrdersRequest(ids, symbol, parameters);
            Object url = Helpers.GetValue(Helpers.GetValue(Helpers.GetValue(this.urls, "api"), "ws"), "public");
            Object wrapped = this.wrapAsPostAction(request);
            Object wsRequest = this.safeDict(wrapped, "request", new java.util.HashMap<String, Object>() {{}});
            Object requestId = this.safeString(wrapped, "requestId");
            Object response = (this.watch(url, requestId, wsRequest, requestId, null)).join();
            Object responseObj = this.safeDict(response, "response", new java.util.HashMap<String, Object>() {{}});
            Object data = this.safeDict(responseObj, "data", new java.util.HashMap<String, Object>() {{}});
            Object statuses = this.safeList(data, "statuses", new java.util.ArrayList<Object>(java.util.Arrays.asList()));
            Object orders = new java.util.ArrayList<Object>(java.util.Arrays.asList());
            for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(statuses)); i++)
            {
                Object status = Helpers.GetValue(statuses, i);
                ((java.util.List<Object>)orders).add(this.safeOrder(new java.util.HashMap<String, Object>() {{
                    put( "info", status );
                    put( "status", status );
                }}));
            }
            return orders;
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name hyperliquid#cancelOrderWs
     * @description cancel a single order using WebSocket post request
     * @see https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/websocket/post-requests
     * @param {string} id order id to cancel
     * @param {string} symbol unified symbol of the market the order was made in
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @param {string} [params.clientOrderId] client order id to cancel instead of order id
     * @param {string} [params.vaultAddress] the vault address for order cancellation
     * @returns {object} an [order structure]{@link https://docs.ccxt.com/?id=order-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> cancelOrderWs(Object id, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object symbol = Helpers.getArg(optionalArgs, 0, null);
            Object parameters = Helpers.getArg(optionalArgs, 1, new java.util.HashMap<String, Object>() {{}});
            Object orders = (this.cancelOrdersWs(new java.util.ArrayList<Object>(java.util.Arrays.asList(id)), symbol, parameters)).join();
            return this.safeDict(orders, 0);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name hyperliquid#watchOrderBook
     * @description watches information on open orders with bid (buy) and ask (sell) prices, volumes and other data
     * @see https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/websocket/subscriptions
     * @param {string} symbol unified symbol of the market to fetch the order book for
     * @param {int} [limit] the maximum amount of order book entries to return
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} A dictionary of [order book structures]{@link https://docs.ccxt.com/?id=order-book-structure} indexed by market symbols
     */
    public java.util.concurrent.CompletableFuture<Object> watchOrderBook(Object symbol2, Object... optionalArgs)
    {
        final Object symbol3 = symbol2;
        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {
            Object symbol = symbol3;
            Object limit = Helpers.getArg(optionalArgs, 0, null);
            Object parameters = Helpers.getArg(optionalArgs, 1, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object market = this.market(symbol);
            symbol = Helpers.GetValue(market, "symbol");
            Object messageHash = Helpers.add("orderbook:", symbol);
            Object url = Helpers.GetValue(Helpers.GetValue(Helpers.GetValue(this.urls, "api"), "ws"), "public");
            Object request = new java.util.HashMap<String, Object>() {{
                put( "method", "subscribe" );
                put( "subscription", new java.util.HashMap<String, Object>() {{
                    put( "type", "l2Book" );
                    put( "coin", ((Helpers.isTrue(Helpers.GetValue(market, "swap")))) ? Helpers.GetValue(market, "baseName") : Helpers.GetValue(market, "id") );
                }} );
            }};
            Object message = this.extend(request, parameters);
            Object orderbook = (this.watch(url, messageHash, message, messageHash, null)).join();
            return Helpers.callDynamically(orderbook, "limit", new Object[]{});
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name hyperliquid#unWatchOrderBook
     * @description unWatches information on open orders with bid (buy) and ask (sell) prices, volumes and other data
     * @see https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/websocket/subscriptions
     * @param {string} symbol unified symbol of the market to fetch the order book for
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} A dictionary of [order book structures]{@link https://docs.ccxt.com/?id=order-book-structure} indexed by market symbols
     */
    public java.util.concurrent.CompletableFuture<Object> unWatchOrderBook(Object symbol2, Object... optionalArgs)
    {
        final Object symbol3 = symbol2;
        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {
            Object symbol = symbol3;
            Object parameters = Helpers.getArg(optionalArgs, 0, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object market = this.market(symbol);
            symbol = Helpers.GetValue(market, "symbol");
            Object subMessageHash = Helpers.add("orderbook:", symbol);
            Object messageHash = Helpers.add("unsubscribe:", subMessageHash);
            Object url = Helpers.GetValue(Helpers.GetValue(Helpers.GetValue(this.urls, "api"), "ws"), "public");
            Object id = String.valueOf(this.nonce());
            Object request = new java.util.HashMap<String, Object>() {{
                put( "id", id );
                put( "method", "unsubscribe" );
                put( "subscription", new java.util.HashMap<String, Object>() {{
                    put( "type", "l2Book" );
                    put( "coin", ((Helpers.isTrue(Helpers.GetValue(market, "swap")))) ? Helpers.GetValue(market, "baseName") : Helpers.GetValue(market, "id") );
                }} );
            }};
            Object message = this.extend(request, parameters);
            return (this.watch(url, messageHash, message, messageHash, null)).join();
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public void handleOrderBook(Client client, Object message)
    {
        //
        //     {
        //         "channel": "l2Book",
        //         "data": {
        //             "coin": "BTC",
        //             "time": 1710131872708,
        //             "levels": [
        //                 [
        //                     {
        //                         "px": "68674.0",
        //                         "sz": "0.97139",
        //                         "n": 4
        //                     }
        //                 ],
        //                 [
        //                     {
        //                         "px": "68675.0",
        //                         "sz": "0.04396",
        //                         "n": 1
        //                     }
        //                 ]
        //             ]
        //         }
        //     }
        //
        Object entry = this.safeDict(message, "data", new java.util.HashMap<String, Object>() {{}});
        Object coin = this.safeString(entry, "coin");
        Object marketId = this.coinToMarketId(coin);
        Object market = this.market(marketId);
        Object symbol = Helpers.GetValue(market, "symbol");
        Object rawData = this.safeList(entry, "levels", new java.util.ArrayList<Object>(java.util.Arrays.asList()));
        Object data = new java.util.HashMap<String, Object>() {{
            put( "bids", Hyperliquid.this.safeList(rawData, 0, new java.util.ArrayList<Object>(java.util.Arrays.asList())) );
            put( "asks", Hyperliquid.this.safeList(rawData, 1, new java.util.ArrayList<Object>(java.util.Arrays.asList())) );
        }};
        Object timestamp = this.safeInteger(entry, "time");
        Object snapshot = this.parseOrderBook(data, symbol, timestamp, "bids", "asks", "px", "sz");
        if (!Helpers.isTrue((Helpers.inOp(this.orderbooks, symbol))))
        {
            Object ob = this.orderBook(snapshot);
            Helpers.addElementToObject(this.orderbooks, symbol, ob);
        }
        Object orderbook = Helpers.GetValue(this.orderbooks, symbol);
        Helpers.callDynamically(orderbook, "reset", new Object[]{snapshot});
        Object messageHash = Helpers.add("orderbook:", symbol);
        client.resolve(orderbook, messageHash);
    }

    /**
     * @method
     * @name hyperliquid#watchTicker
     * @see https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/websocket/subscriptions
     * @description watches a price ticker, a statistical calculation with the information calculated over the past 24 hours for a specific market
     * @param {string} symbol unified symbol of the market to fetch the ticker for
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a [ticker structure]{@link https://docs.ccxt.com/?id=ticker-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> watchTicker(Object symbol2, Object... optionalArgs)
    {
        final Object symbol3 = symbol2;
        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {
            Object symbol = symbol3;
            Object parameters = Helpers.getArg(optionalArgs, 0, new java.util.HashMap<String, Object>() {{}});
            Object market = this.market(symbol);
            symbol = Helpers.GetValue(market, "symbol");
            // try to infer dex from market
            Object dexName = this.safeString(this.safeDict(market, "info", new java.util.HashMap<String, Object>() {{}}), "dex");
            if (Helpers.isTrue(dexName))
            {
                
                parameters = this.extend(parameters, new java.util.HashMap<String, Object>() {{
                    put( "dex", dexName );
                }});
            }
            Object tickers = (this.watchTickers(new java.util.ArrayList<Object>(java.util.Arrays.asList(symbol)), parameters)).join();
            return Helpers.GetValue(tickers, symbol);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name hyperliquid#watchTickers
     * @description watches a price ticker, a statistical calculation with the information calculated over the past 24 hours for all markets of a specific list
     * @see https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/websocket/subscriptions
     * @param {string[]} symbols unified symbol of the market to fetch the ticker for
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @param {string} [params.dex] for for hip3 tokens subscription, eg: 'xyz' or 'flx`, if symbols are provided we will infer it from the first symbol's market
     * @returns {object} a [ticker structure]{@link https://docs.ccxt.com/?id=ticker-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> watchTickers(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object symbols = Helpers.getArg(optionalArgs, 0, null);
            Object parameters = Helpers.getArg(optionalArgs, 1, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            symbols = this.marketSymbols(symbols, null, true);
            Object messageHash = "tickers";
            Object url = Helpers.GetValue(Helpers.GetValue(Helpers.GetValue(this.urls, "api"), "ws"), "public");
            Object request = new java.util.HashMap<String, Object>() {{
                put( "method", "subscribe" );
                put( "subscription", new java.util.HashMap<String, Object>() {{
                    put( "type", "webData2" );
                    put( "user", "0x0000000000000000000000000000000000000000" );
                }} );
            }};
            Object defaultDex = this.safeString(parameters, "dex");
            Object firstSymbol = this.safeString(symbols, 0);
            if (Helpers.isTrue(!Helpers.isEqual(firstSymbol, null)))
            {
                Object market = this.market(firstSymbol);
                Object dexName = this.safeString(this.safeDict(market, "info", new java.util.HashMap<String, Object>() {{}}), "dex");
                if (Helpers.isTrue(!Helpers.isEqual(dexName, null)))
                {
                    defaultDex = dexName;
                }
            }
            if (Helpers.isTrue(!Helpers.isEqual(defaultDex, null)))
            {
                parameters = this.omit(parameters, "dex");
                messageHash = Helpers.add("tickers:", defaultDex);
                Helpers.addElementToObject(Helpers.GetValue(request, "subscription"), "type", "allMids");
                Helpers.addElementToObject(Helpers.GetValue(request, "subscription"), "dex", defaultDex);
            }
            Object tickers = (this.watch(url, messageHash, this.extend(request, parameters), messageHash, null)).join();
            if (Helpers.isTrue(this.newUpdates))
            {
                return this.filterByArrayTickers(tickers, "symbol", symbols);
            }
            return this.tickers;
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name hyperliquid#unWatchTickers
     * @description unWatches a price ticker, a statistical calculation with the information calculated over the past 24 hours for all markets of a specific list
     * @see https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/websocket/subscriptions
     * @param {string[]} symbols unified symbol of the market to fetch the ticker for
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a [ticker structure]{@link https://docs.ccxt.com/?id=ticker-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> unWatchTickers(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object symbols = Helpers.getArg(optionalArgs, 0, null);
            Object parameters = Helpers.getArg(optionalArgs, 1, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            symbols = this.marketSymbols(symbols, null, true);
            Object subMessageHash = "tickers";
            Object messageHash = Helpers.add("unsubscribe:", subMessageHash);
            Object url = Helpers.GetValue(Helpers.GetValue(Helpers.GetValue(this.urls, "api"), "ws"), "public");
            Object request = new java.util.HashMap<String, Object>() {{
                put( "method", "unsubscribe" );
                put( "subscription", new java.util.HashMap<String, Object>() {{
                    put( "type", "webData2" );
                    put( "user", "0x0000000000000000000000000000000000000000" );
                }} );
            }};
            return (this.watch(url, messageHash, this.extend(request, parameters), messageHash, null)).join();
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name hyperliquid#watchMyTrades
     * @description watches information on multiple trades made by the user
     * @see https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/websocket/subscriptions
     * @param {string} symbol unified market symbol of the market orders were made in
     * @param {int} [since] the earliest time in ms to fetch orders for
     * @param {int} [limit] the maximum number of order structures to retrieve
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @param {string} [params.user] user address, will default to this.walletAddress if not provided
     * @returns {object[]} a list of [order structures]{@link https://docs.ccxt.com/?id=order-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> watchMyTrades(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object symbol = Helpers.getArg(optionalArgs, 0, null);
            Object since = Helpers.getArg(optionalArgs, 1, null);
            Object limit = Helpers.getArg(optionalArgs, 2, null);
            Object parameters = Helpers.getArg(optionalArgs, 3, new java.util.HashMap<String, Object>() {{}});
            Object userAddress = null;
            var userAddressparametersVariable = this.handlePublicAddress("watchMyTrades", parameters);
            userAddress = ((java.util.List<Object>) userAddressparametersVariable).get(0);
            parameters = ((java.util.List<Object>) userAddressparametersVariable).get(1);
            (this.loadMarkets()).join();
            Object messageHash = "myTrades";
            if (Helpers.isTrue(!Helpers.isEqual(symbol, null)))
            {
                symbol = this.symbol(symbol);
                messageHash = Helpers.add(messageHash, Helpers.add(":", symbol));
            }
            Object url = Helpers.GetValue(Helpers.GetValue(Helpers.GetValue(this.urls, "api"), "ws"), "public");
            final Object finalUserAddress = userAddress;
            Object request = new java.util.HashMap<String, Object>() {{
                put( "method", "subscribe" );
                put( "subscription", new java.util.HashMap<String, Object>() {{
                    put( "type", "userFills" );
                    put( "user", finalUserAddress );
                }} );
            }};
            Object message = this.extend(request, parameters);
            Object trades = (this.watch(url, messageHash, message, messageHash, null)).join();
            if (Helpers.isTrue(this.newUpdates))
            {
                limit = Helpers.callDynamically(trades, "getLimit", new Object[]{symbol, limit});
            }
            return this.filterBySymbolSinceLimit(trades, symbol, since, limit, true);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name hyperliquid#unWatchMyTrades
     * @description unWatches information on multiple trades made by the user
     * @see https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/websocket/subscriptions
     * @param {string} symbol unified market symbol of the market orders were made in
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @param {string} [params.user] user address, will default to this.walletAddress if not provided
     * @returns {object[]} a list of [order structures]{@link https://docs.ccxt.com/?id=order-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> unWatchMyTrades(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object symbol = Helpers.getArg(optionalArgs, 0, null);
            Object parameters = Helpers.getArg(optionalArgs, 1, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            if (Helpers.isTrue(!Helpers.isEqual(symbol, null)))
            {
                throw new NotSupported((String)Helpers.add(this.id, " unWatchMyTrades does not support a symbol argument, unWatch from all markets only")) ;
            }
            Object userAddress = null;
            var userAddressparametersVariable = this.handlePublicAddress("unWatchMyTrades", parameters);
            userAddress = ((java.util.List<Object>) userAddressparametersVariable).get(0);
            parameters = ((java.util.List<Object>) userAddressparametersVariable).get(1);
            Object messageHash = "unsubscribe:myTrades";
            Object url = Helpers.GetValue(Helpers.GetValue(Helpers.GetValue(this.urls, "api"), "ws"), "public");
            final Object finalUserAddress = userAddress;
            Object request = new java.util.HashMap<String, Object>() {{
                put( "method", "unsubscribe" );
                put( "subscription", new java.util.HashMap<String, Object>() {{
                    put( "type", "userFills" );
                    put( "user", finalUserAddress );
                }} );
            }};
            Object message = this.extend(request, parameters);
            return (this.watch(url, messageHash, message, messageHash, null)).join();
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public Object handleWsTickers(Client client, Object message)
    {
        // hip3 mids
        // {
        //     channel: 'allMids',
        //     data: {
        //         dex: 'flx',
        //         mids: {
        //         'flx:COIN': '270.075',
        //         'flx:CRCL': '78.8175',
        //         'flx:NVDA': '180.64',
        //         'flx:TSLA': '436.075'
        //         }
        //     }
        // }
        //
        //     {
        //         "channel": "webData2",
        //         "data": {
        //             "meta": {
        //                 "universe": [
        //                     {
        //                         "szDecimals": 5,
        //                         "name": "BTC",
        //                         "maxLeverage": 50,
        //                         "onlyIsolated": false
        //                     },
        //                     ...
        //                 ],
        //             },
        //             "assetCtxs": [
        //                 {
        //                     "funding": "0.00003005",
        //                     "openInterest": "2311.50778",
        //                     "prevDayPx": "63475.0",
        //                     "dayNtlVlm": "468043329.64289033",
        //                     "premium": "0.00094264",
        //                     "oraclePx": "64712.0",
        //                     "markPx": "64774.0",
        //                     "midPx": "64773.5",
        //                     "impactPxs": [
        //                         "64773.0",
        //                         "64774.0"
        //                     ]
        //                 },
        //                 ...
        //             ],
        //             "spotAssetCtxs": [
        //                 {
        //                     "prevDayPx": "0.20937",
        //                     "dayNtlVlm": "11188888.61984999",
        //                     "markPx": "0.19722",
        //                     "midPx": "0.197145",
        //                     "circulatingSupply": "598760557.12072003",
        //                     "coin": "PURR/USDC"
        //                 },
        //                 ...
        //             ],
        //         }
        //     }
        //
        // handle hip3 mids
        Object channel = this.safeString(message, "channel");
        if (Helpers.isTrue(Helpers.isEqual(channel, "allMids")))
        {
            Object data = this.safeDict(message, "data", new java.util.HashMap<String, Object>() {{}});
            Object mids = this.safeDict(data, "mids", new java.util.HashMap<String, Object>() {{}});
            if (Helpers.isTrue(!Helpers.isEqual(mids, null)))
            {
                Object keys = new java.util.ArrayList<Object>(((java.util.Map<String, Object>)mids).keySet());
                for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(keys)); i++)
                {
                    Object name = Helpers.GetValue(keys, i);
                    Object marketId = this.coinToMarketId(name);
                    Object market = this.safeMarket(marketId, null, null, "swap");
                    Object symbol = Helpers.GetValue(market, "symbol");
                    final Object finalMids = mids;
                    Object ticker = this.parseWsTicker(new java.util.HashMap<String, Object>() {{
                        put( "price", Hyperliquid.this.safeNumber(finalMids, name) );
                    }}, market);
                    Helpers.addElementToObject(this.tickers, symbol, ticker);
                }
                Object messageHash = Helpers.add("tickers:", this.safeString(data, "dex"));
                client.resolve(this.tickers, messageHash);
                return true;
            }
        }
        // spot
        Object rawData = this.safeDict(message, "data", new java.util.HashMap<String, Object>() {{}});
        Object spotAssets = this.safeList(rawData, "spotAssetCtxs", new java.util.ArrayList<Object>(java.util.Arrays.asList()));
        Object parsedTickers = new java.util.ArrayList<Object>(java.util.Arrays.asList());
        for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(spotAssets)); i++)
        {
            Object assetObject = Helpers.GetValue(spotAssets, i);
            Object coin = this.safeString(assetObject, "coin");
            Object marketId = this.coinToMarketId(coin);
            Object market = this.safeMarket(marketId, null, null, "spot");
            Object symbol = Helpers.GetValue(market, "symbol");
            Object ticker = this.parseWsTicker(assetObject, market);
            ((java.util.List<Object>)parsedTickers).add(ticker);
            Helpers.addElementToObject(this.tickers, symbol, ticker);
        }
        // perpetuals
        Object meta = this.safeDict(rawData, "meta", new java.util.HashMap<String, Object>() {{}});
        Object universe = this.safeList(meta, "universe", new java.util.ArrayList<Object>(java.util.Arrays.asList()));
        Object assetCtxs = this.safeList(rawData, "assetCtxs", new java.util.ArrayList<Object>(java.util.Arrays.asList()));
        for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(universe)); i++)
        {
            Object data = this.extend(this.safeDict(universe, i, new java.util.HashMap<String, Object>() {{}}), this.safeDict(assetCtxs, i, new java.util.HashMap<String, Object>() {{}}));
            Object coin = this.safeString(data, "name");
            Object marketId = this.coinToMarketId(coin);
            Object market = this.safeMarket(marketId, null, null, "swap");
            Object symbol = Helpers.GetValue(market, "symbol");
            Object ticker = this.parseWsTicker(data, market);
            Helpers.addElementToObject(this.tickers, symbol, ticker);
            ((java.util.List<Object>)parsedTickers).add(ticker);
        }
        Object tickers = this.indexBy(parsedTickers, "symbol");
        client.resolve(tickers, "tickers");
        return true;
    }

    public Object parseWsTicker(Object rawTicker, Object... optionalArgs)
    {
        Object market = Helpers.getArg(optionalArgs, 0, null);
        return this.parseTicker(rawTicker, market);
    }

    public void handleMyTrades(Client client, Object message)
    {
        //
        //     {
        //         "channel": "userFills",
        //         "data": {
        //             "isSnapshot": true,
        //             "user": "0x15f43d1f2dee81424afd891943262aa90f22cc2a",
        //             "fills": [
        //                 {
        //                     "coin": "BTC",
        //                     "px": "72528.0",
        //                     "sz": "0.11693",
        //                     "side": "A",
        //                     "time": 1710208712815,
        //                     "startPosition": "0.11693",
        //                     "dir": "Close Long",
        //                     "closedPnl": "-0.81851",
        //                     "hash": "0xc5adaf35f8402750c218040b0a7bc301130051521273b6f398b3caad3e1f3f5f",
        //                     "oid": 7484888874,
        //                     "crossed": true,
        //                     "fee": "2.968244",
        //                     "liquidationMarkPx": null,
        //                     "tid": 567547935839686,
        //                     "cloid": null
        //                 }
        //             ]
        //         }
        //     }
        //
        Object entry = this.safeDict(message, "data", new java.util.HashMap<String, Object>() {{}});
        if (Helpers.isTrue(Helpers.isEqual(this.myTrades, null)))
        {
            Object limit = this.safeInteger(this.options, "tradesLimit", 1000);
            this.myTrades = new ArrayCache.ArrayCacheBySymbolById(((Number)limit).intValue());
        }
        Object trades = this.myTrades;
        Object symbols = new java.util.HashMap<String, Object>() {{}};
        Object data = this.safeList(entry, "fills", new java.util.ArrayList<Object>(java.util.Arrays.asList()));
        Object dataLength = Helpers.getArrayLength(data);
        if (Helpers.isTrue(Helpers.isEqual(dataLength, 0)))
        {
            return;
        }
        for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(data)); i++)
        {
            Object rawTrade = Helpers.GetValue(data, i);
            Object parsed = this.parseWsTrade(rawTrade);
            Object symbol = Helpers.GetValue(parsed, "symbol");
            Helpers.addElementToObject(symbols, symbol, true);
            Helpers.callDynamically(trades, "append", new Object[]{parsed});
        }
        Object keys = new java.util.ArrayList<Object>(((java.util.Map<String, Object>)symbols).keySet());
        for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(keys)); i++)
        {
            Object currentMessageHash = Helpers.add("myTrades:", Helpers.GetValue(keys, i));
            client.resolve(trades, currentMessageHash);
        }
        // non-symbol specific
        Object messageHash = "myTrades";
        client.resolve(trades, messageHash);
    }

    /**
     * @method
     * @name hyperliquid#watchTrades
     * @description watches information on multiple trades made in a market
     * @see https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/websocket/subscriptions
     * @param {string} symbol unified market symbol of the market trades were made in
     * @param {int} [since] the earliest time in ms to fetch trades for
     * @param {int} [limit] the maximum number of trade structures to retrieve
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object[]} a list of [trade structures]{@link https://docs.ccxt.com/?id=trade-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> watchTrades(Object symbol2, Object... optionalArgs)
    {
        final Object symbol3 = symbol2;
        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {
            Object symbol = symbol3;
            Object since = Helpers.getArg(optionalArgs, 0, null);
            Object limit = Helpers.getArg(optionalArgs, 1, null);
            Object parameters = Helpers.getArg(optionalArgs, 2, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object market = this.market(symbol);
            symbol = Helpers.GetValue(market, "symbol");
            Object messageHash = Helpers.add("trade:", symbol);
            Object url = Helpers.GetValue(Helpers.GetValue(Helpers.GetValue(this.urls, "api"), "ws"), "public");
            Object request = new java.util.HashMap<String, Object>() {{
                put( "method", "subscribe" );
                put( "subscription", new java.util.HashMap<String, Object>() {{
                    put( "type", "trades" );
                    put( "coin", ((Helpers.isTrue(Helpers.GetValue(market, "swap")))) ? Helpers.GetValue(market, "baseName") : Helpers.GetValue(market, "id") );
                }} );
            }};
            Object message = this.extend(request, parameters);
            Object trades = (this.watch(url, messageHash, message, messageHash, null)).join();
            if (Helpers.isTrue(this.newUpdates))
            {
                limit = Helpers.callDynamically(trades, "getLimit", new Object[]{symbol, limit});
            }
            return this.filterBySinceLimit(trades, since, limit, "timestamp", true);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name hyperliquid#unWatchTrades
     * @description unWatches information on multiple trades made in a market
     * @see https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/websocket/subscriptions
     * @param {string} symbol unified market symbol of the market trades were made in
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object[]} a list of [trade structures]{@link https://docs.ccxt.com/?id=trade-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> unWatchTrades(Object symbol2, Object... optionalArgs)
    {
        final Object symbol3 = symbol2;
        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {
            Object symbol = symbol3;
            Object parameters = Helpers.getArg(optionalArgs, 0, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object market = this.market(symbol);
            symbol = Helpers.GetValue(market, "symbol");
            Object subMessageHash = Helpers.add("trade:", symbol);
            Object messageHash = Helpers.add("unsubscribe:", subMessageHash);
            Object url = Helpers.GetValue(Helpers.GetValue(Helpers.GetValue(this.urls, "api"), "ws"), "public");
            Object request = new java.util.HashMap<String, Object>() {{
                put( "method", "unsubscribe" );
                put( "subscription", new java.util.HashMap<String, Object>() {{
                    put( "type", "trades" );
                    put( "coin", ((Helpers.isTrue(Helpers.GetValue(market, "swap")))) ? Helpers.GetValue(market, "baseName") : Helpers.GetValue(market, "id") );
                }} );
            }};
            Object message = this.extend(request, parameters);
            return (this.watch(url, messageHash, message, messageHash, null)).join();
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public void handleTrades(Client client, Object message)
    {
        //
        //     {
        //         "channel": "trades",
        //         "data": [
        //             {
        //                 "coin": "BTC",
        //                 "side": "A",
        //                 "px": "68517.0",
        //                 "sz": "0.005",
        //                 "time": 1710125266669,
        //                 "hash": "0xc872699f116e012186620407fc08a802015e0097c5cce74710697f7272e6e959",
        //                 "tid": 981894269203506
        //             }
        //         ]
        //     }
        //
        Object entry = this.safeList(message, "data", new java.util.ArrayList<Object>(java.util.Arrays.asList()));
        Object first = this.safeDict(entry, 0, new java.util.HashMap<String, Object>() {{}});
        Object coin = this.safeString(first, "coin");
        Object marketId = this.coinToMarketId(coin);
        Object market = this.market(marketId);
        Object symbol = Helpers.GetValue(market, "symbol");
        if (!Helpers.isTrue((Helpers.inOp(this.trades, symbol))))
        {
            Object limit = this.safeInteger(this.options, "tradesLimit", 1000);
            var stored = new ArrayCache(((Number)limit).intValue());
            Helpers.addElementToObject(this.trades, symbol, stored);
        }
        Object trades = Helpers.GetValue(this.trades, symbol);
        for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(entry)); i++)
        {
            Object data = this.safeDict(entry, i);
            Object trade = this.parseWsTrade(data);
            Helpers.callDynamically(trades, "append", new Object[]{trade});
        }
        Object messageHash = Helpers.add("trade:", symbol);
        client.resolve(trades, messageHash);
    }

    public Object parseWsTrade(Object trade, Object... optionalArgs)
    {
        //
        // fetchMyTrades
        //
        //     {
        //         "coin": "BTC",
        //         "px": "72528.0",
        //         "sz": "0.11693",
        //         "side": "A",
        //         "time": 1710208712815,
        //         "startPosition": "0.11693",
        //         "dir": "Close Long",
        //         "closedPnl": "-0.81851",
        //         "hash": "0xc5adaf35f8402750c218040b0a7bc301130051521273b6f398b3caad3e1f3f5f",
        //         "oid": 7484888874,
        //         "crossed": true,
        //         "fee": "2.968244",
        //         "liquidationMarkPx": null,
        //         "tid": 567547935839686,
        //         "cloid": null
        //     }
        //
        // fetchTrades
        //
        //     {
        //         "coin": "BTC",
        //         "side": "A",
        //         "px": "68517.0",
        //         "sz": "0.005",
        //         "time": 1710125266669,
        //         "hash": "0xc872699f116e012186620407fc08a802015e0097c5cce74710697f7272e6e959",
        //         "tid": 981894269203506
        //     }
        //
        Object market = Helpers.getArg(optionalArgs, 0, null);
        Object timestamp = this.safeInteger(trade, "time");
        Object price = this.safeString(trade, "px");
        Object amount = this.safeString(trade, "sz");
        Object coin = this.safeString(trade, "coin");
        Object marketId = this.coinToMarketId(coin);
        market = this.safeMarket(marketId, null);
        Object symbol = Helpers.GetValue(market, "symbol");
        Object id = this.safeString(trade, "tid");
        Object side = this.safeString(trade, "side");
        if (Helpers.isTrue(!Helpers.isEqual(side, null)))
        {
            side = ((Helpers.isTrue((Helpers.isEqual(side, "A"))))) ? "sell" : "buy";
        }
        Object fee = this.safeString(trade, "fee");
        final Object finalSide = side;
        return this.safeTrade(new java.util.HashMap<String, Object>() {{
            put( "info", trade );
            put( "timestamp", timestamp );
            put( "datetime", Hyperliquid.this.iso8601(timestamp) );
            put( "symbol", symbol );
            put( "id", id );
            put( "order", Hyperliquid.this.safeString(trade, "oid") );
            put( "type", null );
            put( "side", finalSide );
            put( "takerOrMaker", null );
            put( "price", price );
            put( "amount", amount );
            put( "cost", null );
            put( "fee", new java.util.HashMap<String, Object>() {{
                put( "cost", fee );
                put( "currency", "USDC" );
            }} );
        }}, market);
    }

    /**
     * @method
     * @name hyperliquid#watchOHLCV
     * @description watches historical candlestick data containing the open, high, low, close price, and the volume of a market
     * @see https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/websocket/subscriptions
     * @param {string} symbol unified symbol of the market to fetch OHLCV data for
     * @param {string} timeframe the length of time each candle represents
     * @param {int} [since] timestamp in ms of the earliest candle to fetch
     * @param {int} [limit] the maximum amount of candles to fetch
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {int[][]} A list of candles ordered as timestamp, open, high, low, close, volume
     */
    public java.util.concurrent.CompletableFuture<Object> watchOHLCV(Object symbol2, Object... optionalArgs)
    {
        final Object symbol3 = symbol2;
        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {
            Object symbol = symbol3;
            Object timeframe = Helpers.getArg(optionalArgs, 0, "1m");
            Object since = Helpers.getArg(optionalArgs, 1, null);
            Object limit = Helpers.getArg(optionalArgs, 2, null);
            Object parameters = Helpers.getArg(optionalArgs, 3, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object market = this.market(symbol);
            symbol = Helpers.GetValue(market, "symbol");
            Object url = Helpers.GetValue(Helpers.GetValue(Helpers.GetValue(this.urls, "api"), "ws"), "public");
            Object request = new java.util.HashMap<String, Object>() {{
                put( "method", "subscribe" );
                put( "subscription", new java.util.HashMap<String, Object>() {{
                    put( "type", "candle" );
                    put( "coin", ((Helpers.isTrue(Helpers.GetValue(market, "swap")))) ? Helpers.GetValue(market, "baseName") : Helpers.GetValue(market, "id") );
                    put( "interval", timeframe );
                }} );
            }};
            Object messageHash = Helpers.add(Helpers.add(Helpers.add("candles:", timeframe), ":"), symbol);
            Object message = this.extend(request, parameters);
            Object ohlcv = (this.watch(url, messageHash, message, messageHash, null)).join();
            if (Helpers.isTrue(this.newUpdates))
            {
                limit = Helpers.callDynamically(ohlcv, "getLimit", new Object[]{symbol, limit});
            }
            return this.filterBySinceLimit(ohlcv, since, limit, 0, true);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name hyperliquid#unWatchOHLCV
     * @description watches historical candlestick data containing the open, high, low, close price, and the volume of a market
     * @see https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/websocket/subscriptions
     * @param {string} symbol unified symbol of the market to fetch OHLCV data for
     * @param {string} timeframe the length of time each candle represents
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {int[][]} A list of candles ordered as timestamp, open, high, low, close, volume
     */
    public java.util.concurrent.CompletableFuture<Object> unWatchOHLCV(Object symbol2, Object... optionalArgs)
    {
        final Object symbol3 = symbol2;
        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {
            Object symbol = symbol3;
            Object timeframe = Helpers.getArg(optionalArgs, 0, "1m");
            Object parameters = Helpers.getArg(optionalArgs, 1, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object market = this.market(symbol);
            symbol = Helpers.GetValue(market, "symbol");
            Object url = Helpers.GetValue(Helpers.GetValue(Helpers.GetValue(this.urls, "api"), "ws"), "public");
            Object request = new java.util.HashMap<String, Object>() {{
                put( "method", "unsubscribe" );
                put( "subscription", new java.util.HashMap<String, Object>() {{
                    put( "type", "candle" );
                    put( "coin", ((Helpers.isTrue(Helpers.GetValue(market, "swap")))) ? Helpers.GetValue(market, "baseName") : Helpers.GetValue(market, "id") );
                    put( "interval", timeframe );
                }} );
            }};
            Object subMessageHash = Helpers.add(Helpers.add(Helpers.add("candles:", timeframe), ":"), symbol);
            Object messagehash = Helpers.add("unsubscribe:", subMessageHash);
            Object message = this.extend(request, parameters);
            return (this.watch(url, messagehash, message, messagehash, null)).join();
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public void handleOHLCV(Client client, Object message)
    {
        //
        //     {
        //         channel: 'candle',
        //         data: {
        //             t: 1710146280000,
        //             T: 1710146339999,
        //             s: 'BTC',
        //             i: '1m',
        //             o: '71400.0',
        //             c: '71411.0',
        //             h: '71422.0',
        //             l: '71389.0',
        //             v: '1.20407',
        //             n: 20
        //         }
        //     }
        //
        Object data = this.safeDict(message, "data", new java.util.HashMap<String, Object>() {{}});
        Object base = this.safeString(data, "s");
        Object marketId = this.coinToMarketId(base);
        Object symbol = this.safeSymbol(marketId);
        Object timeframe = this.safeString(data, "i");
        if (!Helpers.isTrue((Helpers.inOp(this.ohlcvs, symbol))))
        {
            Helpers.addElementToObject(this.ohlcvs, symbol, new java.util.HashMap<String, Object>() {{}});
        }
        if (!Helpers.isTrue((Helpers.inOp(Helpers.GetValue(this.ohlcvs, symbol), timeframe))))
        {
            Object limit = this.safeInteger(this.options, "OHLCVLimit", 1000);
            var stored = new ArrayCache.ArrayCacheByTimestamp(((Number)limit).intValue());
            Helpers.addElementToObject(Helpers.GetValue(this.ohlcvs, symbol), timeframe, stored);
        }
        Object ohlcv = Helpers.GetValue(Helpers.GetValue(this.ohlcvs, symbol), timeframe);
        Object parsed = this.parseOHLCV(data);
        Helpers.callDynamically(ohlcv, "append", new Object[]{parsed});
        Object messageHash = Helpers.add(Helpers.add(Helpers.add("candles:", timeframe), ":"), symbol);
        client.resolve(ohlcv, messageHash);
    }

    public void handleWsPost(Client client, Object message)
    {
        //    {
        //         channel: "post",
        //         data: {
        //             id: <number>,
        //             response: {
        //                  type: "info" | "action" | "error",
        //                  payload: { ... }
        //         }
        //    }
        Object data = this.safeDict(message, "data");
        Object id = this.safeString(data, "id");
        Object response = this.safeDict(data, "response");
        Object payload = this.safeDict(response, "payload");
        client.resolve(payload, id);
    }

    /**
     * @method
     * @name hyperliquid#watchOrders
     * @description watches information on multiple orders made by the user
     * @see https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/websocket/subscriptions
     * @param {string} symbol unified market symbol of the market orders were made in
     * @param {int} [since] the earliest time in ms to fetch orders for
     * @param {int} [limit] the maximum number of order structures to retrieve
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @param {string} [params.user] user address, will default to this.walletAddress if not provided
     * @returns {object[]} a list of [order structures]{@link https://docs.ccxt.com/?id=order-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> watchOrders(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object symbol = Helpers.getArg(optionalArgs, 0, null);
            Object since = Helpers.getArg(optionalArgs, 1, null);
            Object limit = Helpers.getArg(optionalArgs, 2, null);
            Object parameters = Helpers.getArg(optionalArgs, 3, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object userAddress = null;
            var userAddressparametersVariable = this.handlePublicAddress("watchOrders", parameters);
            userAddress = ((java.util.List<Object>) userAddressparametersVariable).get(0);
            parameters = ((java.util.List<Object>) userAddressparametersVariable).get(1);
            Object market = null;
            Object messageHash = "order";
            if (Helpers.isTrue(!Helpers.isEqual(symbol, null)))
            {
                market = this.market(symbol);
                symbol = Helpers.GetValue(market, "symbol");
                messageHash = Helpers.add(Helpers.add(messageHash, ":"), symbol);
            }
            Object url = Helpers.GetValue(Helpers.GetValue(Helpers.GetValue(this.urls, "api"), "ws"), "public");
            final Object finalUserAddress = userAddress;
            Object request = new java.util.HashMap<String, Object>() {{
                put( "method", "subscribe" );
                put( "subscription", new java.util.HashMap<String, Object>() {{
                    put( "type", "orderUpdates" );
                    put( "user", finalUserAddress );
                }} );
            }};
            Object message = this.extend(request, parameters);
            Object orders = (this.watch(url, messageHash, message, messageHash, null)).join();
            if (Helpers.isTrue(this.newUpdates))
            {
                limit = Helpers.callDynamically(orders, "getLimit", new Object[]{symbol, limit});
            }
            return this.filterBySymbolSinceLimit(orders, symbol, since, limit, true);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name hyperliquid#unWatchOrders
     * @description unWatches information on multiple orders made by the user
     * @see https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/websocket/subscriptions
     * @param {string} symbol unified market symbol of the market orders were made in
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @param {string} [params.user] user address, will default to this.walletAddress if not provided
     * @returns {object[]} a list of [order structures]{@link https://docs.ccxt.com/#/?id=order-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> unWatchOrders(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object symbol = Helpers.getArg(optionalArgs, 0, null);
            Object parameters = Helpers.getArg(optionalArgs, 1, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            if (Helpers.isTrue(!Helpers.isEqual(symbol, null)))
            {
                throw new NotSupported((String)Helpers.add(this.id, " unWatchOrders() does not support a symbol argument, unWatch from all markets only")) ;
            }
            Object messageHash = "unsubscribe:order";
            Object url = Helpers.GetValue(Helpers.GetValue(Helpers.GetValue(this.urls, "api"), "ws"), "public");
            Object userAddress = null;
            var userAddressparametersVariable = this.handlePublicAddress("unWatchOrders", parameters);
            userAddress = ((java.util.List<Object>) userAddressparametersVariable).get(0);
            parameters = ((java.util.List<Object>) userAddressparametersVariable).get(1);
            final Object finalUserAddress = userAddress;
            Object request = new java.util.HashMap<String, Object>() {{
                put( "method", "unsubscribe" );
                put( "subscription", new java.util.HashMap<String, Object>() {{
                    put( "type", "orderUpdates" );
                    put( "user", finalUserAddress );
                }} );
            }};
            Object message = this.extend(request, parameters);
            return (this.watch(url, messageHash, message, messageHash, null)).join();
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public void handleOrder(Client client, Object message)
    {
        //
        //     {
        //         channel: 'orderUpdates',
        //         data: [
        //             {
        //                 order: {
        //                     coin: 'BTC',
        //                     side: 'B',
        //                     limitPx: '30000.0',
        //                     sz: '0.001',
        //                     oid: 7456484275,
        //                     timestamp: 1710163596492,
        //                     origSz: '0.001'
        //                 },
        //                 status: 'open',
        //                 statusTimestamp: 1710163596492
        //             }
        //         ]
        //     }
        //
        Object data = this.safeList(message, "data", new java.util.ArrayList<Object>(java.util.Arrays.asList()));
        if (Helpers.isTrue(Helpers.isEqual(this.orders, null)))
        {
            Object limit = this.safeInteger(this.options, "ordersLimit", 1000);
            this.orders = new ArrayCache.ArrayCacheBySymbolById(((Number)limit).intValue());
        }
        Object dataLength = Helpers.getArrayLength(data);
        if (Helpers.isTrue(Helpers.isEqual(dataLength, 0)))
        {
            return;
        }
        Object stored = this.orders;
        Object messageHash = "order";
        Object marketSymbols = new java.util.HashMap<String, Object>() {{}};
        for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(data)); i++)
        {
            Object rawOrder = Helpers.GetValue(data, i);
            Object order = this.parseOrder(rawOrder);
            Helpers.callDynamically(stored, "append", new Object[]{order});
            Object symbol = this.safeString(order, "symbol");
            Helpers.addElementToObject(marketSymbols, symbol, true);
        }
        Object keys = new java.util.ArrayList<Object>(((java.util.Map<String, Object>)marketSymbols).keySet());
        for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(keys)); i++)
        {
            Object symbol = Helpers.GetValue(keys, i);
            Object innerMessageHash = Helpers.add(Helpers.add(messageHash, ":"), symbol);
            client.resolve(stored, innerMessageHash);
        }
        client.resolve(stored, messageHash);
    }

    public Object handleErrorMessage(Client client, Object message)
    {
        //
        //    {
        //      "channel": "post",
        //      "data": {
        //        "id": 1,
        //        "response": {
        //          "type": "action",
        //          "payload": {
        //            "status": "ok",
        //            "response": {
        //              "type": "order",
        //              "data": {
        //                "statuses": [
        //                  {
        //                    "error": "Order price cannot be more than 80% away from the reference price"
        //                  }
        //                ]
        //              }
        //            }
        //          }
        //        }
        //      }
        //    }
        //
        //    {
        //         "channel": "error",
        //         "data": "Error parsing JSON into valid websocket request: { \"type\": \"allMids\" }"
        //     }
        //
        Object channel = this.safeString(message, "channel", "");
        if (Helpers.isTrue(Helpers.isEqual(channel, "error")))
        {
            Object ret_msg = this.safeString(message, "data", "");
            Object errorMsg = Helpers.add(Helpers.add(this.id, " "), ret_msg);
            client.reject(errorMsg);
            return true;
        }
        Object data = this.safeDict(message, "data", new java.util.HashMap<String, Object>() {{}});
        Object id = this.safeString(message, "id");
        if (Helpers.isTrue(Helpers.isEqual(id, null)))
        {
            id = this.safeString(data, "id");
        }
        Object response = this.safeDict(data, "response", new java.util.HashMap<String, Object>() {{}});
        Object payload = this.safeDict(response, "payload", new java.util.HashMap<String, Object>() {{}});
        Object status = this.safeString(payload, "status");
        if (Helpers.isTrue(Helpers.isTrue(!Helpers.isEqual(status, null)) && Helpers.isTrue(!Helpers.isEqual(status, "ok"))))
        {
            Object errorMsg = Helpers.add(Helpers.add(this.id, " "), this.json(payload));
            client.reject(errorMsg, id);
            return true;
        }
        Object type = this.safeString(payload, "type");
        if (Helpers.isTrue(Helpers.isEqual(type, "error")))
        {
            Object error = Helpers.add(Helpers.add(this.id, " "), this.json(payload));
            client.reject(error, id);
            return true;
        }
        try
        {
            this.handleErrors(0, "", "", "", new java.util.HashMap<String, Object>() {{}}, this.json(payload), payload, new java.util.HashMap<String, Object>() {{}}, new java.util.HashMap<String, Object>() {{}});
        } catch(Exception e)
        {
            client.reject(e, id);
            return true;
        }
        return false;
    }

    public void handleOrderBookUnsubscription(Client client, Object subscription)
    {
        //
        //        "subscription":{
        //           "type":"l2Book",
        //           "coin":"BTC",
        //           "nSigFigs":5,
        //           "mantissa":null
        //        }
        //
        Object coin = this.safeString(subscription, "coin");
        Object marketId = this.coinToMarketId(coin);
        Object symbol = this.safeSymbol(marketId);
        Object subMessageHash = Helpers.add("orderbook:", symbol);
        Object messageHash = Helpers.add("unsubscribe:", subMessageHash);
        this.cleanUnsubscription(client, subMessageHash, messageHash);
        if (Helpers.isTrue(Helpers.inOp(this.orderbooks, symbol)))
        {
            ((java.util.Map<String,Object>)this.orderbooks).remove((String)symbol);
        }
    }

    public void handleTradesUnsubscription(Client client, Object subscription)
    {
        //
        Object coin = this.safeString(subscription, "coin");
        Object marketId = this.coinToMarketId(coin);
        Object symbol = this.safeSymbol(marketId);
        Object subMessageHash = Helpers.add("trade:", symbol);
        Object messageHash = Helpers.add("unsubscribe:", subMessageHash);
        this.cleanUnsubscription(client, subMessageHash, messageHash);
        if (Helpers.isTrue(Helpers.inOp(this.trades, symbol)))
        {
            ((java.util.Map<String,Object>)this.trades).remove((String)symbol);
        }
    }

    public void handleTickersUnsubscription(Client client, Object subscription)
    {
        //
        Object subMessageHash = "tickers";
        Object messageHash = Helpers.add("unsubscribe:", subMessageHash);
        this.cleanUnsubscription(client, subMessageHash, messageHash);
        Object symbols = new java.util.ArrayList<Object>(((java.util.Map<String, Object>)this.tickers).keySet());
        for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(symbols)); i++)
        {
            ((java.util.Map<String,Object>)this.tickers).remove((String)Helpers.GetValue(symbols, i));
        }
    }

    public void handleOHLCVUnsubscription(Client client, Object subscription)
    {
        Object coin = this.safeString(subscription, "coin");
        Object marketId = this.coinToMarketId(coin);
        Object symbol = this.safeSymbol(marketId);
        Object interval = this.safeString(subscription, "interval");
        Object timeframe = this.findTimeframe(interval);
        Object subMessageHash = Helpers.add(Helpers.add(Helpers.add("candles:", timeframe), ":"), symbol);
        Object messageHash = Helpers.add("unsubscribe:", subMessageHash);
        this.cleanUnsubscription(client, subMessageHash, messageHash);
        if (Helpers.isTrue(Helpers.inOp(this.ohlcvs, symbol)))
        {
            if (Helpers.isTrue(Helpers.inOp(Helpers.GetValue(this.ohlcvs, symbol), timeframe)))
            {
                ((java.util.Map<String,Object>)Helpers.GetValue(this.ohlcvs, symbol)).remove((String)timeframe);
            }
        }
    }

    public void handleOrderUnsubscription(Client client, Object subscription)
    {
        Object subHash = "order";
        Object unSubHash = Helpers.add("unsubscribe:", subHash);
        this.cleanUnsubscription(client, subHash, unSubHash, true);
        Object topicStructure = new java.util.HashMap<String, Object>() {{
            put( "topic", "orders" );
        }};
        this.cleanCache(topicStructure);
    }

    public void handleMyTradesUnsubscription(Client client, Object subscription)
    {
        Object subHash = "myTrades";
        Object unSubHash = Helpers.add("unsubscribe:", subHash);
        this.cleanUnsubscription(client, subHash, unSubHash, true);
        Object topicStructure = new java.util.HashMap<String, Object>() {{
            put( "topic", "myTrades" );
        }};
        this.cleanCache(topicStructure);
    }

    public void handleSubscriptionResponse(Client client, Object message)
    {
        // {
        //     "channel":"subscriptionResponse",
        //     "data":{
        //        "method":"unsubscribe",
        //        "subscription":{
        //           "type":"l2Book",
        //           "coin":"BTC",
        //           "nSigFigs":5,
        //           "mantissa":null
        //        }
        //     }
        // }
        //
        //  {
        //      "channel":"subscriptionResponse",
        //      "data":{
        //         "method":"unsubscribe",
        //         "subscription":{
        //            "type":"trades",
        //            "coin":"PURR/USDC"
        //         }
        //      }
        //  }
        //
        Object data = this.safeDict(message, "data", new java.util.HashMap<String, Object>() {{}});
        Object method = this.safeString(data, "method");
        if (Helpers.isTrue(Helpers.isEqual(method, "unsubscribe")))
        {
            Object subscription = this.safeDict(data, "subscription", new java.util.HashMap<String, Object>() {{}});
            Object type = this.safeString(subscription, "type");
            if (Helpers.isTrue(Helpers.isEqual(type, "l2Book")))
            {
                this.handleOrderBookUnsubscription(client, subscription);
            } else if (Helpers.isTrue(Helpers.isEqual(type, "trades")))
            {
                this.handleTradesUnsubscription(client, subscription);
            } else if (Helpers.isTrue(Helpers.isEqual(type, "webData2")))
            {
                this.handleTickersUnsubscription(client, subscription);
            } else if (Helpers.isTrue(Helpers.isEqual(type, "candle")))
            {
                this.handleOHLCVUnsubscription(client, subscription);
            } else if (Helpers.isTrue(Helpers.isEqual(type, "orderUpdates")))
            {
                this.handleOrderUnsubscription(client, subscription);
            } else if (Helpers.isTrue(Helpers.isEqual(type, "userFills")))
            {
                this.handleMyTradesUnsubscription(client, subscription);
            }
        }
    }

    public void handleMessage(Client client, Object message)
    {
        //
        // {
        //     "channel":"subscriptionResponse",
        //     "data":{
        //        "method":"unsubscribe",
        //        "subscription":{
        //           "type":"l2Book",
        //           "coin":"BTC",
        //           "nSigFigs":5,
        //           "mantissa":null
        //        }
        //     }
        // }
        //
        if (Helpers.isTrue(this.handleErrorMessage(client, message)))
        {
            return;
        }
        Object topic = this.safeString(message, "channel", "");
        Object methods = new java.util.HashMap<String, Object>() {{
            put( "pong", "handlePong");
            put( "trades", "handleTrades");
            put( "l2Book", "handleOrderBook");
            put( "candle", "handleOHLCV");
            put( "orderUpdates", "handleOrder");
            put( "userFills", "handleMyTrades");
            put( "webData2", "handleWsTickers");
            put( "allMids", "handleWsTickers");
            put( "post", "handleWsPost");
            put( "subscriptionResponse", "handleSubscriptionResponse");
        }};
        Object exacMethod = this.safeValue(methods, topic);
        if (Helpers.isTrue(!Helpers.isEqual(exacMethod, null)))
        {
            Helpers.callDynamically(this, exacMethod, new Object[] {client, message});
            return;
        }
        Object keys = new java.util.ArrayList<Object>(((java.util.Map<String, Object>)methods).keySet());
        for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(keys)); i++)
        {
            Object key = Helpers.GetValue(keys, i);
            if (Helpers.isTrue(Helpers.isGreaterThanOrEqual(Helpers.getIndexOf(topic, Helpers.GetValue(keys, i)), 0)))
            {
                Object method = Helpers.GetValue(methods, key);
                Helpers.callDynamically(this, method, new Object[] {client, message});
                return;
            }
        }
    }

    public Object ping(Client client)
    {
        return new java.util.HashMap<String, Object>() {{
            put( "method", "ping" );
        }};
    }

    public Object handlePong(Client client, Object message)
    {
        //
        //   {
        //       "channel": "pong"
        //   }
        //
        client.lastPong = ((Number)this.safeInteger(message, "pong")).longValue();
        return message;
    }

    public Object requestId()
    {
        Object requestId = this.sum(this.safeInteger(this.options, "requestId", 0), 1);
        Helpers.addElementToObject(this.options, "requestId", requestId);
        return requestId;
    }

    public Object wrapAsPostAction(Object request)
    {
        Object requestId = this.requestId();
        return new java.util.HashMap<String, Object>() {{
            put( "requestId", requestId );
            put( "request", new java.util.HashMap<String, Object>() {{
                put( "method", "post" );
                put( "id", requestId );
                put( "request", new java.util.HashMap<String, Object>() {{
                    put( "type", "action" );
                    put( "payload", request );
                }} );
            }} );
        }};
    }
}
