package io.github.ccxt.exchanges.pro;
import io.github.ccxt.base.Precise;
import io.github.ccxt.errors.*;
import io.github.ccxt.Helpers;
import io.github.ccxt.ws.*;
import io.github.ccxt.Client;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

public class Paradex extends io.github.ccxt.exchanges.Paradex
{
   public Paradex () {
       super();
   }

   public Paradex (Object options) {
       super(options);
   }

    public Object describe()
    {
        return this.deepExtend(super.describe(), new java.util.HashMap<String, Object>() {{
            put( "has", new java.util.HashMap<String, Object>() {{
                put( "ws", true );
                put( "watchTicker", true );
                put( "watchTickers", true );
                put( "watchOrderBook", true );
                put( "watchOrders", false );
                put( "watchTrades", true );
                put( "watchTradesForSymbols", false );
                put( "watchBalance", false );
                put( "watchOHLCV", false );
            }} );
            put( "urls", new java.util.HashMap<String, Object>() {{
                put( "logo", "https://x.com/tradeparadex/photo" );
                put( "api", new java.util.HashMap<String, Object>() {{
                    put( "ws", "wss://ws.api.prod.paradex.trade/v1" );
                }} );
                put( "test", new java.util.HashMap<String, Object>() {{
                    put( "ws", "wss://ws.api.testnet.paradex.trade/v1" );
                }} );
                put( "www", "https://www.paradex.trade/" );
                put( "doc", "https://docs.api.testnet.paradex.trade/" );
                put( "fees", "https://docs.paradex.trade/getting-started/trading-fees" );
                put( "referral", "" );
            }} );
            put( "options", new java.util.HashMap<String, Object>() {{}} );
            put( "streaming", new java.util.HashMap<String, Object>() {{}} );
        }});
    }

    /**
     * @method
     * @name paradex#watchTrades
     * @description get the list of most recent trades for a particular symbol
     * @see https://docs.paradex.trade/ws/web-socket-channels/trades/trades
     * @param {string} symbol unified symbol of the market to fetch trades for
     * @param {int} [since] timestamp in ms of the earliest trade to fetch
     * @param {int} [limit] the maximum amount of trades to fetch
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object[]} a list of [trade structures]{@link https://docs.ccxt.com/?id=public-trades}
     */
    public java.util.concurrent.CompletableFuture<Object> watchTrades(Object symbol2, Object... optionalArgs)
    {
        final Object symbol3 = symbol2;
        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {
            Object symbol = symbol3;
            Object since = Helpers.getArg(optionalArgs, 0, null);
            Object limit = Helpers.getArg(optionalArgs, 1, null);
            Object parameters = Helpers.getArg(optionalArgs, 2, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object messageHash = "trades.";
            if (Helpers.isTrue(!Helpers.isEqual(symbol, null)))
            {
                Object market = this.market(symbol);
                messageHash = Helpers.add(messageHash, Helpers.GetValue(market, "id"));
            } else
            {
                messageHash = Helpers.add(messageHash, "ALL");
            }
            Object url = Helpers.GetValue(Helpers.GetValue(this.urls, "api"), "ws");
            final Object finalMessageHash = messageHash;
            Object request = new java.util.HashMap<String, Object>() {{
                put( "jsonrpc", "2.0" );
                put( "method", "subscribe" );
                put( "params", new java.util.HashMap<String, Object>() {{
                    put( "channel", finalMessageHash );
                }} );
            }};
            Object trades = (this.watch(url, messageHash, this.deepExtend(request, parameters), messageHash, null)).join();
            if (Helpers.isTrue(this.newUpdates))
            {
                limit = Helpers.callDynamically(trades, "getLimit", new Object[]{symbol, limit});
            }
            return this.filterBySinceLimit(trades, since, limit, "timestamp", true);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public Object handleTrade(Client client, Object message)
    {
        //
        //     {
        //         "jsonrpc": "2.0",
        //         "method": "subscription",
        //         "params": {
        //             "channel": "trades.ALL",
        //             "data": {
        //                 "id": "1718179273230201709233240002",
        //                 "market": "kBONK-USD-PERP",
        //                 "side": "BUY",
        //                 "size": "34028",
        //                 "price": "0.028776",
        //                 "created_at": 1718179273230,
        //                 "trade_type": "FILL"
        //             }
        //         }
        //     }
        //
        Object parameters = this.safeDict(message, "params", new java.util.HashMap<String, Object>() {{}});
        Object data = this.safeDict(parameters, "data", new java.util.HashMap<String, Object>() {{}});
        Object parsedTrade = this.parseTrade(data);
        Object symbol = Helpers.GetValue(parsedTrade, "symbol");
        Object messageHash = this.safeString(parameters, "channel");
        Object stored = this.safeValue(this.trades, symbol);
        if (Helpers.isTrue(Helpers.isEqual(stored, null)))
        {
            stored = new ArrayCache(((Number)this.safeInteger(this.options, "tradesLimit", 1000)).intValue());
            Helpers.addElementToObject(this.trades, symbol, stored);
        }
        Helpers.callDynamically(stored, "append", new Object[]{parsedTrade});
        client.resolve(stored, messageHash);
        return message;
    }

    /**
     * @method
     * @name paradex#watchOrderBook
     * @description watches information on open orders with bid (buy) and ask (sell) prices, volumes and other data
     * @see https://docs.paradex.trade/ws/web-socket-channels/order-book/order-book
     * @param {string} symbol unified symbol of the market to fetch the order book for
     * @param {int} [limit] the maximum amount of order book entries to return
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} A dictionary of [order book structures]{@link https://docs.ccxt.com/?id=order-book-structure} indexed by market symbols
     */
    public java.util.concurrent.CompletableFuture<Object> watchOrderBook(Object symbol, Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object limit = Helpers.getArg(optionalArgs, 0, null);
            Object parameters = Helpers.getArg(optionalArgs, 1, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            Object market = this.market(symbol);
            Object messageHash = Helpers.add(Helpers.add("order_book.", Helpers.GetValue(market, "id")), ".snapshot@15@100ms");
            Object url = Helpers.GetValue(Helpers.GetValue(this.urls, "api"), "ws");
            Object request = new java.util.HashMap<String, Object>() {{
                put( "jsonrpc", "2.0" );
                put( "method", "subscribe" );
                put( "params", new java.util.HashMap<String, Object>() {{
                    put( "channel", messageHash );
                }} );
            }};
            Object orderbook = (this.watch(url, messageHash, this.deepExtend(request, parameters), messageHash, null)).join();
            return Helpers.callDynamically(orderbook, "limit", new Object[]{});
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public void handleOrderBook(Client client, Object message)
    {
        //
        //     {
        //         "jsonrpc": "2.0",
        //         "method": "subscription",
        //         "params": {
        //             "channel": "order_book.BTC-USD-PERP.snapshot@15@50ms",
        //             "data": {
        //                 "seq_no": 14127815,
        //                 "market": "BTC-USD-PERP",
        //                 "last_updated_at": 1718267837265,
        //                 "update_type": "s",
        //                 "inserts": [
        //                     {
        //                         "side": "BUY",
        //                         "price": "67629.7",
        //                         "size": "0.992"
        //                     },
        //                     {
        //                         "side": "SELL",
        //                         "price": "69378.6",
        //                         "size": "3.137"
        //                     }
        //                 ],
        //                 "updates": [],
        //                 "deletes": []
        //             }
        //         }
        //     }
        //
        Object parameters = this.safeDict(message, "params", new java.util.HashMap<String, Object>() {{}});
        Object data = this.safeDict(parameters, "data", new java.util.HashMap<String, Object>() {{}});
        Object marketId = this.safeString(data, "market");
        Object market = this.safeMarket(marketId);
        Object timestamp = this.safeInteger(data, "last_updated_at");
        Object symbol = Helpers.GetValue(market, "symbol");
        if (!Helpers.isTrue((Helpers.inOp(this.orderbooks, symbol))))
        {
            Helpers.addElementToObject(this.orderbooks, symbol, this.orderBook());
        }
        Object orderbookData = new java.util.HashMap<String, Object>() {{
            put( "bids", new java.util.ArrayList<Object>(java.util.Arrays.asList()) );
            put( "asks", new java.util.ArrayList<Object>(java.util.Arrays.asList()) );
        }};
        Object inserts = this.safeList(data, "inserts");
        for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(inserts)); i++)
        {
            Object insert = this.safeDict(inserts, i);
            Object side = this.safeString(insert, "side");
            Object price = this.safeString(insert, "price");
            Object size = this.safeString(insert, "size");
            if (Helpers.isTrue(Helpers.isEqual(side, "BUY")))
            {
                ((java.util.List<Object>)Helpers.GetValue(orderbookData, "bids")).add(new java.util.ArrayList<Object>(java.util.Arrays.asList(price, size)));
            } else
            {
                ((java.util.List<Object>)Helpers.GetValue(orderbookData, "asks")).add(new java.util.ArrayList<Object>(java.util.Arrays.asList(price, size)));
            }
        }
        Object orderbook = Helpers.GetValue(this.orderbooks, symbol);
        Object snapshot = this.parseOrderBook(orderbookData, symbol, timestamp, "bids", "asks");
        Helpers.addElementToObject(snapshot, "nonce", this.safeNumber(data, "seq_no"));
        Helpers.callDynamically(orderbook, "reset", new Object[]{snapshot});
        Object messageHash = this.safeString(parameters, "channel");
        client.resolve(orderbook, messageHash);
    }

    /**
     * @method
     * @name paradex#watchTicker
     * @description watches a price ticker, a statistical calculation with the information calculated over the past 24 hours for a specific market
     * @see https://docs.paradex.trade/ws/web-socket-channels/markets-summary/markets-summary
     * @param {string} symbol unified symbol of the market to fetch the ticker for
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a [ticker structure]{@link https://docs.ccxt.com/?id=ticker-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> watchTicker(Object symbol2, Object... optionalArgs)
    {
        final Object symbol3 = symbol2;
        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {
            Object symbol = symbol3;
            Object parameters = Helpers.getArg(optionalArgs, 0, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            symbol = this.symbol(symbol);
            Object channel = "markets_summary";
            Object url = Helpers.GetValue(Helpers.GetValue(this.urls, "api"), "ws");
            Object request = new java.util.HashMap<String, Object>() {{
                put( "jsonrpc", "2.0" );
                put( "method", "subscribe" );
                put( "params", new java.util.HashMap<String, Object>() {{
                    put( "channel", channel );
                }} );
            }};
            Object messageHash = Helpers.add(Helpers.add(channel, "."), symbol);
            return (this.watch(url, messageHash, this.deepExtend(request, parameters), messageHash, null)).join();
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    /**
     * @method
     * @name paradex#watchTickers
     * @description watches a price ticker, a statistical calculation with the information calculated over the past 24 hours for all markets of a specific list
     * @see https://docs.paradex.trade/ws/web-socket-channels/markets-summary/markets-summary
     * @param {string[]} symbols unified symbol of the market to fetch the ticker for
     * @param {object} [params] extra parameters specific to the exchange API endpoint
     * @returns {object} a [ticker structure]{@link https://docs.ccxt.com/?id=ticker-structure}
     */
    public java.util.concurrent.CompletableFuture<Object> watchTickers(Object... optionalArgs)
    {

        return java.util.concurrent.CompletableFuture.supplyAsync(() -> {

            Object symbols = Helpers.getArg(optionalArgs, 0, null);
            Object parameters = Helpers.getArg(optionalArgs, 1, new java.util.HashMap<String, Object>() {{}});
            (this.loadMarkets()).join();
            symbols = this.marketSymbols(symbols);
            Object channel = "markets_summary";
            Object url = Helpers.GetValue(Helpers.GetValue(this.urls, "api"), "ws");
            Object request = new java.util.HashMap<String, Object>() {{
                put( "jsonrpc", "2.0" );
                put( "method", "subscribe" );
                put( "params", new java.util.HashMap<String, Object>() {{
                    put( "channel", channel );
                }} );
            }};
            Object messageHashes = new java.util.ArrayList<Object>(java.util.Arrays.asList());
            if (Helpers.isTrue(((symbols instanceof java.util.List) || (symbols.getClass().isArray()))))
            {
                for (var i = 0; Helpers.isLessThan(i, Helpers.getArrayLength(symbols)); i++)
                {
                    Object messageHash = Helpers.add(Helpers.add(channel, "."), Helpers.GetValue(symbols, i));
                    ((java.util.List<Object>)messageHashes).add(messageHash);
                }
            } else
            {
                ((java.util.List<Object>)messageHashes).add(channel);
            }
            Object newTickers = (this.watchMultiple(url, messageHashes, this.deepExtend(request, parameters), messageHashes, null)).join();
            if (Helpers.isTrue(this.newUpdates))
            {
                Object result = new java.util.HashMap<String, Object>() {{}};
                Helpers.addElementToObject(result, Helpers.GetValue(newTickers, "symbol"), newTickers);
                return result;
            }
            return this.filterByArray(this.tickers, "symbol", symbols);
        }, io.github.ccxt.Exchange.VIRTUAL_EXECUTOR);

    }

    public Object handleTicker(Client client, Object message)
    {
        //
        //     {
        //         "jsonrpc": "2.0",
        //         "method": "subscription",
        //         "params": {
        //             "channel": "markets_summary",
        //             "data": {
        //                 "symbol": "ORDI-USD-PERP",
        //                 "oracle_price": "49.80885481",
        //                 "mark_price": "49.80885481",
        //                 "last_traded_price": "62.038",
        //                 "bid": "49.822",
        //                 "ask": "58.167",
        //                 "volume_24h": "0",
        //                 "total_volume": "54542628.66054200416",
        //                 "created_at": 1718334307698,
        //                 "underlying_price": "47.93",
        //                 "open_interest": "6999.5",
        //                 "funding_rate": "0.03919997509811",
        //                 "price_change_rate_24h": ""
        //             }
        //         }
        //     }
        //
        Object parameters = this.safeDict(message, "params", new java.util.HashMap<String, Object>() {{}});
        Object data = this.safeDict(parameters, "data", new java.util.HashMap<String, Object>() {{}});
        Object marketId = this.safeString(data, "symbol");
        Object market = this.safeMarket(marketId);
        Object symbol = Helpers.GetValue(market, "symbol");
        Object channel = this.safeString(parameters, "channel");
        Object messageHash = Helpers.add(Helpers.add(channel, "."), symbol);
        Object ticker = this.parseTicker(data, market);
        Helpers.addElementToObject(this.tickers, symbol, ticker);
        client.resolve(ticker, channel);
        client.resolve(ticker, messageHash);
        return message;
    }

    public Object handleErrorMessage(Client client, Object message)
    {
        //
        //     {
        //         "jsonrpc": "2.0",
        //         "id": 0,
        //         "error": {
        //             "code": -32600,
        //             "message": "invalid subscribe request",
        //             "data": "invalid channel"
        //         },
        //         "usIn": 1718179125962419,
        //         "usDiff": 76,
        //         "usOut": 1718179125962495
        //     }
        //
        Object error = this.safeDict(message, "error");
        if (Helpers.isTrue(Helpers.isEqual(error, null)))
        {
            return true;
        } else
        {
            Object errorCode = this.safeString(error, "code");
            if (Helpers.isTrue(!Helpers.isEqual(errorCode, null)))
            {
                Object feedback = Helpers.add(Helpers.add(this.id, " "), this.json(error));
                this.throwExactlyMatchedException(Helpers.GetValue(this.exceptions, "exact"), "-32600", feedback);
                Object messageString = this.safeValue(error, "message");
                if (Helpers.isTrue(!Helpers.isEqual(messageString, null)))
                {
                    this.throwBroadlyMatchedException(Helpers.GetValue(this.exceptions, "broad"), messageString, feedback);
                }
            }
            return false;
        }
    }

    public void handleMessage(Client client, Object message)
    {
        if (!Helpers.isTrue(this.handleErrorMessage(client, message)))
        {
            return;
        }
        //
        //     {
        //         "jsonrpc": "2.0",
        //         "method": "subscription",
        //         "params": {
        //             "channel": "trades.ALL",
        //             "data": {
        //                 "id": "1718179273230201709233240002",
        //                 "market": "kBONK-USD-PERP",
        //                 "side": "BUY",
        //                 "size": "34028",
        //                 "price": "0.028776",
        //                 "created_at": 1718179273230,
        //                 "trade_type": "FILL"
        //             }
        //         }
        //     }
        //
        Object data = this.safeDict(message, "params");
        if (Helpers.isTrue(!Helpers.isEqual(data, null)))
        {
            Object channel = this.safeString(data, "channel");
            Object parts = Helpers.split(channel, ".");
            Object name = this.safeString(parts, 0);
            Object methods = new java.util.HashMap<String, Object>() {{
                put( "trades", "handleTrade");
                put( "order_book", "handleOrderBook");
                put( "markets_summary", "handleTicker");
            }};
            Object method = this.safeValue(methods, name);
            if (Helpers.isTrue(!Helpers.isEqual(method, null)))
            {
                Helpers.callDynamically(this, method, new Object[] {client, message});
            }
        }
    }
}
